
_EXCEPTION_POINTERS struc ; (sizeof=0x8, standard type)
ExceptionRecord	dd ?	; offset
ContextRecord dd ?	; offset
_EXCEPTION_POINTERS ends


_FILETIME struc	; (sizeof=0x8, standard	type)
dwLowDateTime dd ?
dwHighDateTime dd ?
_FILETIME ends


IO_COUNTERS struc ; (sizeof=0x30, standard type)
ReadOperationCount dq ?
WriteOperationCount dq ?
OtherOperationCount dq ?
ReadTransferCount dq ?
WriteTransferCount dq ?
OtherTransferCount dq ?
IO_COUNTERS ends


_LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E struc	; (sizeof=0x8, standard	type)
LowPart	dd ?
HighPart dd ?
_LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E ends


LARGE_INTEGER union ; (sizeof=0x8, standard type)
anonymous_0 _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E ?
u _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E ?
QuadPart dq ?
LARGE_INTEGER ends


_EH4_SCOPETABLE_RECORD struc ; (sizeof=0xC, standard type)
EnclosingLevel dd ?
FilterFunc dd ?		; offset
HandlerFunc dd ?	; offset
_EH4_SCOPETABLE_RECORD ends


CPPEH_RECORD struc ; (sizeof=0x18, standard type)
old_esp	dd ?
exc_ptr	dd ?		; offset
prev_er	dd ?		; offset
handler	dd ?		; offset
msEH_ptr dd ?		; offset
disabled dd ?
CPPEH_RECORD ends


_EH4_SCOPETABLE	struc ;	(sizeof=0x10, variable size)
GSCookieOffset dd ?
GSCookieXOROffset dd ?
EHCookieOffset dd ?
EHCookieXOROffset dd ?
ScopeRecord _EH4_SCOPETABLE_RECORD 0 dup(?)
_EH4_SCOPETABLE	ends


;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2010 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-B231-7414-99			    |
; |		       NCFTA Canada/Concordia University		    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	50C534DD23EFF7F65F89F36FDAA9BB74
; Input	CRC32 :	1A0791E8

; File Name   :	C:\Program Files (x86)\Mozilla Firefox\firefox.exe
; Format      :	Portable executable for	80386 (PE)
; Imagebase   :	400000
; Section 1. (virtual address 00001000)
; Virtual size			: 00001A7A (   6778.)
; Section size in file		: 00001C00 (   7168.)
; Offset to raw	data for section: 00000400
; Flags	60000020: Text Executable Readable
; Alignment	: default
; OS type	  :  MS	Windows
; Application type:  Executable	32bit

include	uni.inc	; see unicode subdir of	ida for	info on	unicode

.686p
.mmx
.model flat


; Segment type:	Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use32
assume cs:_text
;org 401000h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



sub_401000 proc	near

var_4= dword ptr -4
arg_0= dword ptr  4
arg_4= dword ptr  8

push	ecx
mov	edx, [esp+4+arg_0]
mov	eax, [ecx+4]
mov	[esp+4+var_4], ecx
mov	ecx, [esp+4+arg_4]
push	ebx
lea	ebx, [edx+ecx*2]
push	edi
mov	edi, edx
cmp	edx, ebx
jnb	loc_401135
push	ebp
mov	ebp, 3FFh
push	esi

loc_401025:
movzx	edx, word ptr [edi]
test	edx, 0FF80h
jnz	short loc_401038
mov	[eax], dl
inc	eax
jmp	loc_40111A

loc_401038:
test	edx, 0F800h
jnz	short loc_40105B
mov	ecx, edx
shr	ecx, 6
and	dl, 3Fh
or	cl, 0C0h
or	dl, 80h
mov	[eax], cl
mov	[eax+1], dl
add	eax, 2
jmp	loc_40111A

loc_40105B:
mov	esi, edx
mov	ecx, edx
and	ecx, 0FFFFF800h
cmp	ecx, 0D800h
jz	short loc_401095
mov	cx, dx
shr	cx, 0Ch
or	cl, 0E0h
mov	[eax], cl
mov	ecx, edx
shr	ecx, 6
and	cl, 3Fh
or	cl, 80h
and	dl, 3Fh
or	dl, 80h
mov	[eax+1], cl
mov	[eax+2], dl
jmp	loc_401117

loc_401095:
and	esi, 0FFFFFC00h
cmp	esi, 0D800h
jnz	short loc_40110E
add	edi, 2
cmp	edi, ebx
jz	short loc_401127
movzx	esi, word ptr [edi]
mov	ecx, esi
and	ecx, 0FFFFFC00h
cmp	ecx, 0DC00h
jnz	short loc_4010FD
and	edx, ebp
add	edx, 40h
shl	edx, 0Ah
and	esi, ebp
add	edx, esi
mov	ecx, edx
shr	ecx, 12h
or	cl, 0F0h
mov	[eax], cl
mov	ecx, edx
shr	ecx, 0Ch
and	cl, 3Fh
or	cl, 80h
mov	[eax+1], cl
mov	ecx, edx
shr	ecx, 6
and	cl, 3Fh
and	dl, 3Fh
or	cl, 80h
or	dl, 80h
mov	[eax+2], cl
mov	[eax+3], dl
add	eax, 4
jmp	short loc_40111A

loc_4010FD:
mov	word ptr [eax],	0BFEFh
mov	byte ptr [eax+2], 0BDh
add	eax, 3
sub	edi, 2
jmp	short loc_40111A

loc_40110E:
mov	word ptr [eax],	0BFEFh
mov	byte ptr [eax+2], 0BDh

loc_401117:
add	eax, 3

loc_40111A:
add	edi, 2
cmp	edi, ebx
jb	loc_401025
jmp	short loc_401133

loc_401127:
mov	word ptr [eax],	0BFEFh
mov	byte ptr [eax+2], 0BDh
add	eax, 3

loc_401133:
pop	esi
pop	ebp

loc_401135:
mov	ecx, [esp+0Ch+var_4]
pop	edi
mov	[ecx+4], eax
pop	ebx
pop	ecx
retn	8
sub_401000 endp




sub_401142 proc	near

lpValue= dword ptr -4

push	ecx
push	ebx
push	ebp
mov	ebp, ds:GetEnvironmentVariableW
push	esi
push	0		; nSize
push	0		; lpBuffer
mov	ebx, offset Name ; "PATH"
push	ebx		; lpName
call	ebp ; GetEnvironmentVariableW
mov	esi, eax
test	esi, esi
jz	short loc_4011D2
push	edi
xor	ecx, ecx
push	2
pop	edx
mul	edx
seto	cl
neg	ecx
or	ecx, eax
push	ecx
call	unknown_libname_1 ; Microsoft VisualC 2-10/net runtime
pop	ecx
push	esi		; nSize
mov	edi, eax
push	edi		; lpBuffer
push	ebx		; lpName
call	ebp ; GetEnvironmentVariableW
dec	esi
cmp	esi, eax
jnz	short loc_4011CA
mov	esi, ds:ExpandEnvironmentStringsW
push	0		; nSize
push	0		; lpDst
push	edi		; lpSrc
call	esi ; ExpandEnvironmentStringsW
mov	ebp, eax
test	ebp, ebp
jz	short loc_4011CA
xor	ecx, ecx
push	2
pop	edx
mul	edx
seto	cl
neg	ecx
or	ecx, eax
push	ecx
call	unknown_libname_1 ; Microsoft VisualC 2-10/net runtime
pop	ecx
push	ebp		; nSize
push	eax		; lpDst
push	edi		; lpSrc
mov	[esp+20h+lpValue], eax
call	esi ; ExpandEnvironmentStringsW
test	eax, eax
jz	short loc_4011C0
push	[esp+14h+lpValue] ; lpValue
push	ebx		; lpName
call	ds:SetEnvironmentVariableW

loc_4011C0:		; void *
push	[esp+14h+lpValue]
call	??_V@YAXPAX@Z	; operator delete[](void *)
pop	ecx

loc_4011CA:		; void *
push	edi
call	??_V@YAXPAX@Z	; operator delete[](void *)
pop	ecx
pop	edi

loc_4011D2:
pop	esi
pop	ebp
pop	ebx
pop	ecx
retn
sub_401142 endp




; int __cdecl sub_4011D7(int, LPWCH lpFilename)
sub_4011D7 proc	near

lpFilename= dword ptr  8

push	104h		; nSize
push	[esp+4+lpFilename] ; lpFilename
push	0		; hModule
call	ds:GetModuleFileNameW
neg	eax
sbb	eax, eax
and	eax, 7FFFBFFBh
add	eax, 80004005h
retn
sub_4011D7 endp



; Attributes: bp-based frame

; int __cdecl sub_4011F7(char *Format, char ArgList)
sub_4011F7 proc	near

Text= word ptr -1804h
MultiByteStr= byte ptr -804h
var_4= dword ptr -4
Format=	dword ptr  8
ArgList= byte ptr  0Ch

push	ebp
mov	ebp, esp
mov	eax, 1804h
call	__alloca_probe
mov	eax, ___security_cookie
xor	eax, ebp
mov	[ebp+var_4], eax
push	esi
lea	eax, [ebp+ArgList]
push	eax		; ArgList
push	[ebp+Format]	; Format
mov	esi, 800h
push	0FFFFFFFFh	; MaxCount
lea	eax, [ebp+MultiByteStr]
push	esi		; DstSize
push	eax		; DstBuf
call	ds:_vsnprintf_s
add	esp, 14h
push	esi		; cchWideChar
lea	eax, [ebp+Text]
push	eax		; lpWideCharStr
push	0FFFFFFFFh	; cbMultiByte
lea	eax, [ebp+MultiByteStr]
push	eax		; lpMultiByteStr
push	0		; dwFlags
push	0FDE9h		; CodePage
call	ds:MultiByteToWideChar
push	10010h		; uType
push	offset Caption	; "Firefox"
lea	eax, [ebp+Text]
push	eax		; lpText
push	0		; hWnd
call	ds:MessageBoxW
mov	ecx, [ebp+var_4]
xor	ecx, ebp
pop	esi
call	@__security_check_cookie@4 ; __security_check_cookie(x)
leave
retn
sub_4011F7 endp




sub_401272 proc	near
call	ds:GetTickCount
mov	ecx, eax
mov	eax, dword_404048
cmp	eax, ecx
jbe	short loc_401292
sub	eax, ecx
cmp	eax, 40000000h
jbe	short loc_401292
inc	dword_40404C

loc_401292:
mov	edx, dword_40404C
push	esi
xor	esi, esi
xor	eax, eax
or	edx, esi
mov	dword_404048, ecx
or	eax, ecx
pop	esi
retn
sub_401272 endp



; Attributes: bp-based frame

sub_4012A9 proc	near

var_C= byte ptr	-0Ch
arg_0= dword ptr  8
arg_4= dword ptr  0Ch

push	ebp
mov	ebp, esp
sub	esp, 0Ch
push	esi
mov	esi, ecx
push	esi
call	sub_401C6D
push	2
push	[ebp+arg_4]
lea	eax, [ebp+var_C]
push	[ebp+arg_0]
push	eax
call	sub_401C9B
push	esi
lea	eax, [ebp+var_C]
push	1
push	eax
call	sub_401CB8
lea	eax, [ebp+var_C]
push	eax
call	sub_401CAC
add	esp, 24h
mov	eax, esi
pop	esi
leave
retn	8
sub_4012A9 endp



; Attributes: bp-based frame

; int __cdecl sub_4012E8(int, LPSTR lpMultiByteStr)
sub_4012E8 proc	near

Filename= word ptr -20Ch
var_4= dword ptr -4
arg_0= dword ptr  8
lpMultiByteStr=	dword ptr  0Ch

push	ebp
mov	ebp, esp
sub	esp, 20Ch
mov	eax, ___security_cookie
xor	eax, ebp
mov	[ebp+var_4], eax
push	esi
mov	esi, [ebp+lpMultiByteStr]
lea	eax, [ebp+Filename]
push	eax		; lpFilename
push	[ebp+arg_0]	; int
call	sub_4011D7
pop	ecx
pop	ecx
mov	ecx, eax
shr	ecx, 1Fh
test	cl, 1
jnz	short loc_40133B
xor	eax, eax
push	eax		; lpUsedDefaultChar
push	eax		; lpDefaultChar
push	104h		; cbMultiByte
push	esi		; lpMultiByteStr
push	0FFFFFFFFh	; cchWideChar
lea	ecx, [ebp+Filename]
push	ecx		; lpWideCharStr
push	eax		; dwFlags
push	0FDE9h		; CodePage
call	ds:WideCharToMultiByte
xor	eax, eax

loc_40133B:
mov	ecx, [ebp+var_4]
xor	ecx, ebp
pop	esi
call	@__security_check_cookie@4 ; __security_check_cookie(x)
leave
retn
sub_4012E8 endp




sub_401348 proc	near

arg_0= dword ptr  4
arg_4= dword ptr  8

push	esi
mov	esi, [esp+4+arg_0]
mov	eax, [esi]
test	eax, eax
jz	short loc_40135C
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+8]
and	dword ptr [esi], 0

loc_40135C:
mov	eax, [esp+4+arg_4]
mov	[esi], eax
pop	esi
test	eax, eax
jz	short locret_40136D
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+4]

locret_40136D:
retn
sub_401348 endp



; Attributes: bp-based frame fpd=19Ch

sub_40136E proc	near

var_21C= byte ptr -21Ch
var_210= dword ptr -210h
Filename= word ptr -20Ch
var_4= dword ptr -4
arg_0= dword ptr  8
arg_4= dword ptr  0Ch

push	ebp
lea	ebp, [esp-19Ch]
sub	esp, 21Ch
mov	eax, ___security_cookie
xor	eax, ebp
mov	[ebp+19Ch+var_4], eax
and	[ebp+19Ch+var_210], 0
push	esi
mov	esi, [ebp+19Ch+arg_4]
push	edi
lea	eax, [ebp+19Ch+Filename]
push	eax		; lpFilename
push	[ebp+19Ch+arg_0] ; int
call	sub_4011D7
mov	edi, eax
shr	eax, 1Fh
pop	ecx
test	al, 1
mov	eax, [ebp+19Ch+var_210]
pop	ecx
jz	short loc_4013C0

loc_4013B2:
test	eax, eax
jz	short loc_4013BC
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+8]

loc_4013BC:
mov	eax, edi
jmp	short loc_40141F

loc_4013C0:
and	[ebp+19Ch+var_210], 0
test	eax, eax
jz	short loc_4013CE
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+8]

loc_4013CE:
push	2
push	0FFFFFFFFh
lea	eax, [ebp+19Ch+Filename]
push	eax
lea	eax, [ebp+19Ch+var_21C]
push	eax
call	sub_401C7E
lea	eax, [ebp+19Ch+var_210]
push	eax
lea	eax, [ebp+19Ch+var_21C]
push	1
push	eax
call	sub_401C5C
mov	edi, eax
lea	eax, [ebp+19Ch+var_21C]
push	eax
call	sub_401C8F
mov	eax, edi
shr	eax, 1Fh
add	esp, 20h
test	al, 1
mov	eax, [ebp+19Ch+var_210]
jnz	short loc_4013B2
mov	[esi], eax
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+4]
mov	eax, [ebp+19Ch+var_210]
test	eax, eax
jz	short loc_40141D
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+8]

loc_40141D:
xor	eax, eax

loc_40141F:
mov	ecx, [ebp+19Ch+var_4]
pop	edi
xor	ecx, ebp
pop	esi
call	@__security_check_cookie@4 ; __security_check_cookie(x)
add	ebp, 19Ch
leave
retn
sub_40136E endp



; Attributes: bp-based frame fpd=0E4h

sub_401436 proc	near

Dst= byte ptr -164h
var_160= byte ptr -160h
var_140= dword ptr -140h
var_128= byte ptr -128h
var_11C= dword ptr -11Ch
var_118= dword ptr -118h
var_114= dword ptr -114h
var_110= dword ptr -110h
var_10C= dword ptr -10Ch
EnvString= byte	ptr -108h
var_4= dword ptr -4
arg_0= dword ptr  8
arg_4= dword ptr  0Ch
arg_8= dword ptr  10h

push	ebp
lea	ebp, [esp-0E4h]
sub	esp, 164h
mov	eax, ___security_cookie
xor	eax, ebp
mov	[ebp+0E4h+var_4], eax
mov	eax, [ebp+0E4h+arg_8]
push	ebx
mov	ebx, [ebp+0E4h+arg_4]
push	esi
push	edi
xor	edi, edi
push	offset VarName	; "XUL_APP_FILE"
mov	[ebp+0E4h+var_11C], eax
mov	[ebp+0E4h+var_10C], edi
call	ds:getenv
mov	esi, eax
pop	ecx
cmp	esi, edi
jz	short loc_4014CB
cmp	byte ptr [esi],	0
jz	short loc_4014CB
mov	eax, [ebp+0E4h+var_10C]
mov	[ebp+0E4h+var_10C], edi
cmp	eax, edi
jz	short loc_40148F
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+8]

loc_40148F:
lea	eax, [ebp+0E4h+var_10C]
push	eax
push	esi
call	dword_404044
shr	eax, 1Fh
pop	ecx
pop	ecx
test	al, 1
jz	loc_4015A2
push	esi		; ArgList
push	offset aInvalidPathFou ; "Invalid path found: '%s'"
call	sub_4011F7
pop	ecx

loc_4014B3:
pop	ecx

loc_4014B4:
mov	eax, [ebp+0E4h+var_10C]
cmp	eax, edi

loc_4014B9:
jz	short loc_4014C1
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+8]

loc_4014C1:
mov	eax, 0FFh
jmp	loc_4016F5

loc_4014CB:
cmp	[ebp+0E4h+arg_0], 1
jle	loc_4015A2
mov	eax, [ebx+4]
mov	cl, [eax]
cmp	cl, 2Dh
jnz	short loc_4014FE
inc	eax
cmp	[eax], cl
jnz	short loc_4014E8

loc_4014E7:
inc	eax

loc_4014E8:		; "app"
push	offset Str2
push	eax		; Str1
call	ds:_stricmp
neg	eax
pop	ecx
sbb	al, al
pop	ecx
inc	al
jmp	short loc_401505

loc_4014FE:
cmp	cl, 2Fh
jz	short loc_4014E7
xor	al, al

loc_401505:
test	al, al
jz	loc_4015A2
cmp	[ebp+0E4h+arg_0], 2
jnz	short loc_401522
push	offset aIncorrectNumbe ; "Incorrect number of arguments	passed to"...

loc_40151B:
call	sub_4011F7
jmp	short loc_4014B3

loc_401522:
mov	eax, [ebp+0E4h+var_10C]
mov	[ebp+0E4h+var_10C], edi
cmp	eax, edi
jz	short loc_401532
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+8]

loc_401532:
lea	eax, [ebp+0E4h+var_10C]
push	eax
push	dword ptr [ebx+8]
call	dword_404044
pop	ecx
shr	eax, 1Fh
pop	ecx
push	dword ptr [ebx+8] ; ArgList
test	al, 1
jz	short loc_401561
push	offset aApplication_in ; "application.ini path not recognized: '%"...

loc_401550:
call	sub_4011F7
mov	eax, [ebp+0E4h+var_10C]
pop	ecx
pop	ecx
test	eax, eax
jmp	loc_4014B9

loc_401561:		; "XUL_APP_FILE=%s"
push	offset Format
lea	eax, [ebp+0E4h+EnvString]
push	104h		; Count
push	eax		; Dest
call	ds:_snprintf
lea	eax, [ebp+0E4h+EnvString]
push	eax		; EnvString
call	ds:_putenv
add	esp, 14h
test	eax, eax
jz	short loc_401591
lea	eax, [ebp+0E4h+EnvString]
push	eax
push	offset aCouldnTSetS_ ; "Couldn't set %s.\n"
jmp	short loc_401550

loc_401591:
mov	eax, [ebx]
sub	[ebp+0E4h+arg_0], 2
mov	[ebx+8], eax
add	ebx, 8
xor	edi, edi

loc_4015A2:
cmp	[ebp+0E4h+var_10C], edi
jz	short loc_4015F9
lea	eax, [ebp+0E4h+var_110]
push	eax
push	[ebp+0E4h+var_10C]
call	dword_40402C
shr	eax, 1Fh
pop	ecx
pop	ecx
test	al, 1
jz	short loc_4015C7
push	offset aCouldnTReadApp ; "Couldn't read application.ini"
jmp	loc_40151B

loc_4015C7:
mov	eax, [ebp+0E4h+var_110]
mov	ecx, [ebp+0E4h+var_11C]
push	edi
mov	[eax+24h], ecx
push	[ebp+0E4h+var_110]
push	ebx
push	[ebp+0E4h+arg_0]
call	dword_404040
push	[ebp+0E4h+var_110]
mov	esi, eax
call	dword_404034
mov	eax, [ebp+0E4h+var_10C]
add	esp, 14h
cmp	eax, edi
jmp	loc_4016EB

loc_4015F9:		; "<"
push	offset asc_403300
lea	ecx, [ebp+0E4h+Dst] ; Dst
call	sub_401F05
lea	eax, [ebp+0E4h+var_118]
push	eax
push	dword ptr [ebx]
mov	[ebp+0E4h+var_118], edi
call	sub_40136E
shr	eax, 1Fh
pop	ecx
pop	ecx
test	al, 1
jz	short loc_401642
push	offset aCouldnTFindThe ; "Couldn't find the application directory"...
call	sub_4011F7
mov	eax, [ebp+0E4h+var_118]
pop	ecx
cmp	eax, edi
jz	short loc_401635
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+8]

loc_401635:
lea	ecx, [ebp+0E4h+Dst]
call	sub_401FDF
jmp	loc_4014B4

loc_401642:
mov	[ebp+0E4h+var_114], edi
mov	edi, [ebp+0E4h+var_118]
mov	eax, [edi]
lea	ecx, [ebp+0E4h+var_114]
push	ecx
push	edi
call	dword ptr [eax+0B8h]
mov	eax, [ebp+0E4h+var_114]
and	[ebp+0E4h+var_110], 0
mov	ecx, [eax]
lea	edx, [ebp+0E4h+var_110]
push	edx
push	eax
call	dword ptr [ecx+0ACh]
mov	esi, [ebp+0E4h+var_110]
push	2
push	7
lea	eax, [ebp+0E4h+var_128]
push	offset aBrowser	; "browser"
push	eax
call	sub_401C7E
mov	eax, [esi]
add	esp, 10h
lea	ecx, [ebp+0E4h+var_128]
push	ecx
push	esi
call	dword ptr [eax+0Ch]
lea	eax, [ebp+0E4h+var_128]
push	eax
call	sub_401C8F
push	[ebp+0E4h+var_110]
lea	eax, [ebp+0E4h+var_160]
push	eax
call	sub_401348
mov	eax, [ebp+0E4h+var_11C]
mov	[ebp+0E4h+var_140], eax
push	0
lea	eax, [ebp+0E4h+Dst]
push	eax
push	ebx
push	[ebp+0E4h+arg_0]
call	dword_404040
mov	esi, eax
mov	eax, [ebp+0E4h+var_110]
add	esp, 1Ch
test	eax, eax
jz	short loc_4016CB
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+8]

loc_4016CB:
mov	eax, [ebp+0E4h+var_114]
test	eax, eax
jz	short loc_4016D8
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+8]

loc_4016D8:
mov	eax, [edi]
push	edi
call	dword ptr [eax+8]
lea	ecx, [ebp+0E4h+Dst]
call	sub_401FDF
mov	eax, [ebp+0E4h+var_10C]
test	eax, eax

loc_4016EB:
jz	short loc_4016F3
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+8]

loc_4016F3:
mov	eax, esi

loc_4016F5:
mov	ecx, [ebp+0E4h+var_4]
pop	edi
pop	esi
xor	ecx, ebp
pop	ebx
call	@__security_check_cookie@4 ; __security_check_cookie(x)
add	ebp, 0E4h
leave
retn
sub_401436 endp



; Attributes: bp-based frame

sub_40170D proc	near

var_320= byte ptr -320h
var_314= dword ptr -314h
FileName= word ptr -310h
MultiByteStr= byte ptr -108h
var_4= dword ptr -4
arg_0= dword ptr  8
arg_4= dword ptr  0Ch

push	ebp
mov	ebp, esp
sub	esp, 320h
mov	eax, ___security_cookie
xor	eax, ebp
mov	[ebp+var_4], eax
mov	eax, [ebp+arg_4]
push	esi
mov	[ebp+var_314], eax
push	edi
lea	eax, [ebp+MultiByteStr]
push	eax		; lpMultiByteStr
push	[ebp+arg_0]	; int
call	sub_4012E8
mov	esi, eax
shr	eax, 1Fh
pop	ecx
pop	ecx
test	al, 1
jz	short loc_401754
push	offset aCouldnTFindThe ; "Couldn't find the application directory"...
call	sub_4011F7
pop	ecx

loc_401750:
mov	eax, esi
jmp	short loc_4017CE

loc_401754:
lea	eax, [ebp+MultiByteStr]
push	5Ch		; Ch
push	eax		; Str
call	ds:strrchr
mov	esi, eax
pop	ecx
pop	ecx
test	esi, esi
jz	short loc_4017C9
lea	ecx, [ebp+MultiByteStr]
sub	eax, ecx
cmp	eax, 0FBh
ja	short loc_4017C9
lea	eax, [esi+1]
push	offset Source	; "xul.dll"
push	eax		; Dest
call	strcpy
pop	ecx
pop	ecx
push	104h		; cchWideChar
lea	eax, [ebp+FileName]
push	eax		; lpWideCharStr
push	0FFFFFFFFh	; cbMultiByte
lea	eax, [ebp+MultiByteStr]
push	eax		; lpMultiByteStr
push	0		; dwFlags
push	0FDE9h		; CodePage
call	ds:MultiByteToWideChar
lea	eax, [ebp+FileName]
push	eax		; lpFileName
call	ds:GetFileAttributesW
cmp	eax, 0FFFFFFFFh
jnz	short loc_4017DC
push	offset aCouldNotFindTh ; "Could	not find the Mozilla runtime.\n"
call	sub_4011F7
pop	ecx

loc_4017C9:
mov	eax, 80004005h

loc_4017CE:
mov	ecx, [ebp+var_4]
pop	edi
xor	ecx, ebp
pop	esi
call	@__security_check_cookie@4 ; __security_check_cookie(x)
leave
retn

loc_4017DC:
call	sub_401C54
lea	eax, [ebp+MultiByteStr]
push	eax		; Src
call	sub_401CF9
mov	edi, eax
shr	eax, 1Fh
pop	ecx
test	al, 1
jz	short loc_401806
push	offset aCouldnTLoadXpc ; "Couldn't load XPCOM.\n"

loc_4017FC:
call	sub_4011F7
pop	ecx
mov	eax, edi
jmp	short loc_4017CE

loc_401806:
push	offset off_403340
call	sub_401BDD
mov	edi, eax
shr	eax, 1Fh
pop	ecx
test	al, 1
jz	short loc_401821
push	offset aCouldnTLoadXre ; "Couldn't load XRE functions.\n"
jmp	short loc_4017FC

loc_401821:
call	sub_401CE1
push	[ebp+var_314]
lea	eax, [ebp+MultiByteStr]
push	0
push	0FFFFFFFFh
push	eax
lea	ecx, [ebp+var_320]
mov	byte ptr [esi],	0
call	sub_4012A9
push	eax
call	sub_401C5C
mov	esi, eax
lea	eax, [ebp+var_320]
push	eax
call	sub_401C8F
add	esp, 10h
jmp	loc_401750
sub_40170D endp



; Attributes: bp-based frame

sub_401861 proc	near

var_74=	dword ptr -74h
var_70=	dword ptr -70h
Frequency= LARGE_INTEGER ptr -6Ch
var_64=	dword ptr -64h
var_4C=	dword ptr -4Ch
var_48=	dword ptr -48h
IoCounters= IO_COUNTERS	ptr -34h
var_4= dword ptr -4
arg_0= dword ptr  8
arg_4= dword ptr  0Ch

push	ebp
mov	ebp, esp
sub	esp, 74h
mov	eax, ___security_cookie
xor	eax, ebp
mov	[ebp+var_4], eax
push	ebx
mov	ebx, [ebp+arg_4]
push	esi
push	edi
lea	eax, [ebp+Frequency]
push	eax		; lpFrequency
call	ds:QueryPerformanceFrequency
push	offset ModuleName ; "kernel32.dll"
call	ds:GetModuleHandleW
push	offset ProcName	; "GetTickCount64"
push	eax		; hModule
call	ds:GetProcAddress
mov	dword_404050, eax
test	eax, eax
jnz	short loc_4018AB
mov	eax, offset sub_401272
mov	dword_404050, eax

loc_4018AB:
call	eax
push	dword ptr [ebp+Frequency+4]
push	dword ptr [ebp+Frequency]
push	edx
push	eax
call	__allmul
mov	esi, ds:GetCurrentProcess
mov	dword ptr [ebp+Frequency], eax
lea	eax, [ebp+IoCounters]
push	eax		; lpIoCounters
mov	dword ptr [ebp+Frequency+4], edx
call	esi ; GetCurrentProcess
mov	edi, ds:GetProcessIoCounters
push	eax		; hProcess
call	edi ; GetProcessIoCounters
mov	[ebp+var_74], eax
lea	eax, [ebp+var_70]
push	eax
push	dword ptr [ebx]
call	sub_40170D
shr	eax, 1Fh
pop	ecx
pop	ecx
test	al, 1
jz	short loc_4018F6
mov	eax, 0FFh
jmp	loc_40198A

loc_4018F6:
push	dword ptr [ebp+Frequency+4]
push	dword ptr [ebp+Frequency]
push	1
call	dword_40403C
add	esp, 0Ch
call	dword_404038
cmp	[ebp+var_74], 0
jz	short loc_401972
push	dword ptr [ebp+IoCounters.ReadOperationCount]
push	34h
call	dword_404030
mov	eax, dword ptr [ebp+IoCounters.ReadTransferCount]
mov	ecx, dword ptr [ebp+IoCounters.ReadTransferCount+4]
shrd	eax, ecx, 0Ah
push	eax
push	35h
shr	ecx, 0Ah
call	dword_404030
add	esp, 10h
lea	eax, [ebp+var_64]
push	eax		; lpIoCounters
call	esi ; GetCurrentProcess
push	eax		; hProcess
call	edi ; GetProcessIoCounters
test	eax, eax
jz	short loc_401972
mov	eax, [ebp+var_64]
sub	eax, dword ptr [ebp+IoCounters.ReadOperationCount]
push	eax
push	36h
call	dword_404030
mov	eax, [ebp+var_4C]
sub	eax, dword ptr [ebp+IoCounters.ReadTransferCount]
mov	ecx, [ebp+var_48]
sbb	ecx, dword ptr [ebp+IoCounters.ReadTransferCount+4]
shrd	eax, ecx, 0Ah
push	eax
push	37h
shr	ecx, 0Ah
call	dword_404030
add	esp, 10h

loc_401972:
push	[ebp+var_70]
push	ebx
push	[ebp+arg_0]
call	sub_401436
add	esp, 0Ch
mov	esi, eax
call	sub_401CED
mov	eax, esi

loc_40198A:
mov	ecx, [ebp+var_4]
pop	edi
pop	esi
xor	ecx, ebp
pop	ebx
call	@__security_check_cookie@4 ; __security_check_cookie(x)
leave
retn
sub_401861 endp



; Attributes: bp-based frame

_wmain proc near

var_18=	dword ptr -18h
var_14=	dword ptr -14h
var_10=	dword ptr -10h
var_C= dword ptr -0Ch
var_8= dword ptr -8
var_4= dword ptr -4
arg_0= dword ptr  8
arg_4= dword ptr  0Ch

push	ebp
mov	ebp, esp
sub	esp, 18h
push	esi
push	edi
call	sub_401142
push	offset unk_403544
call	ds:SetDllDirectoryW
mov	edi, [ebp+arg_0]
xor	ecx, ecx
push	4
pop	edx
lea	eax, [edi+1]
mul	edx
seto	cl
neg	ecx
or	ecx, eax
push	ecx
call	unknown_libname_1 ; Microsoft VisualC 2-10/net runtime
mov	esi, eax
pop	ecx
mov	[ebp+var_10], esi
test	esi, esi
jnz	short loc_4019DD
push	7Fh
pop	eax
jmp	loc_401ACA

loc_4019DD:
and	[ebp+var_4], 0
push	ebx
test	edi, edi
jle	short loc_401A48
mov	eax, [ebp+arg_4]
sub	eax, esi
mov	[ebp+arg_0], esi
mov	[ebp+var_8], eax
jmp	short loc_4019F6

loc_4019F3:
mov	eax, [ebp+var_8]

loc_4019F6:
mov	ecx, [ebp+arg_0]
mov	ebx, [eax+ecx]
push	ebx		; Str
call	ds:wcslen
mov	[ebp+var_C], eax
imul	eax, 3
inc	eax
push	eax
call	unknown_libname_1 ; Microsoft VisualC 2-10/net runtime
mov	esi, eax
pop	ecx
pop	ecx
test	esi, esi
jz	short loc_401A30
push	[ebp+var_C]
lea	ecx, [ebp+var_18]
push	ebx
mov	[ebp+var_18], esi
mov	[ebp+var_14], esi
call	sub_401000
mov	eax, [ebp+var_14]
mov	byte ptr [eax],	0

loc_401A30:
mov	eax, [ebp+arg_0]
mov	[eax], esi
test	esi, esi
jz	short loc_401AAC
inc	[ebp+var_4]
add	[ebp+arg_0], 4
cmp	[ebp+var_4], edi
jl	short loc_4019F3
mov	esi, [ebp+var_10]

loc_401A48:
and	dword ptr [esi+edi*4], 0
xor	ecx, ecx
push	4
pop	edx
lea	eax, [edi+1]
mul	edx
seto	cl
neg	ecx
or	ecx, eax
push	ecx
call	unknown_libname_1 ; Microsoft VisualC 2-10/net runtime
mov	ebx, eax
pop	ecx
test	ebx, ebx
jz	short loc_401AA1
test	edi, edi
jle	short loc_401A82
mov	ecx, esi
sub	ecx, ebx
mov	[ebp+arg_0], edi

loc_401A75:
mov	edx, [ecx+eax]
mov	[eax], edx
add	eax, 4
dec	[ebp+arg_0]
jnz	short loc_401A75

loc_401A82:
push	esi
push	edi
call	sub_401861
push	esi		; void *
mov	[ebp+arg_0], eax
call	??_V@YAXPAX@Z	; operator delete[](void *)
add	esp, 0Ch
jmp	short loc_401ABB

loc_401A97:
dec	edi
push	dword ptr [esi+edi*4] ;	void *
call	??_V@YAXPAX@Z	; operator delete[](void *)
pop	ecx

loc_401AA1:
test	edi, edi
jnz	short loc_401A97
push	esi		; void *
call	??_V@YAXPAX@Z	; operator delete[](void *)
pop	ecx

loc_401AAC:
push	7Fh
pop	eax
jmp	short loc_401AC9

loc_401AB1:
dec	edi
push	dword ptr [ebx+edi*4] ;	void *
call	??_V@YAXPAX@Z	; operator delete[](void *)
pop	ecx

loc_401ABB:
test	edi, edi
jnz	short loc_401AB1
push	ebx		; void *
call	??_V@YAXPAX@Z	; operator delete[](void *)
mov	eax, [ebp+arg_0]
pop	ecx

loc_401AC9:
pop	ebx

loc_401ACA:
pop	edi
pop	esi
leave
retn
_wmain endp



; Attributes: bp-based frame

; int __cdecl sub_401ACE(LPCSTR	lpMultiByteStr,	char)
sub_401ACE proc	near

LibFileName= word ptr -20Ch
var_4= dword ptr -4
lpMultiByteStr=	dword ptr  8
arg_4= byte ptr	 0Ch

push	ebp
mov	ebp, esp
sub	esp, 20Ch
mov	eax, ___security_cookie
xor	eax, ebp
mov	[ebp+var_4], eax
mov	eax, [ebp+lpMultiByteStr]
push	104h		; cchWideChar
lea	ecx, [ebp+LibFileName]
push	ecx		; lpWideCharStr
push	0FFFFFFFFh	; cbMultiByte
push	eax		; lpMultiByteStr
push	0		; dwFlags
push	0FDE9h		; CodePage
call	ds:MultiByteToWideChar
cmp	[ebp+arg_4], 0
jz	short loc_401B13
lea	eax, [ebp+LibFileName]
push	eax		; lpFileName
call	sub_40219C
pop	ecx

loc_401B13:
push	esi
push	8		; dwFlags
push	0		; hFile
lea	eax, [ebp+LibFileName]
push	eax		; lpLibFileName
call	ds:LoadLibraryExW
mov	esi, eax
test	esi, esi
jnz	short loc_401B33
call	ds:GetLastError
jmp	short loc_401B4F

loc_401B33:		; unsigned int
push	8
call	??2@YAPAXI@Z	; operator new(uint)
pop	ecx
test	eax, eax
jz	short loc_401B4F
mov	ecx, dword_404144
mov	[eax+4], ecx
mov	[eax], esi
mov	dword_404144, eax

loc_401B4F:
mov	ecx, [ebp+var_4]
test	esi, esi
setnz	al
xor	ecx, ebp
pop	esi
call	@__security_check_cookie@4 ; __security_check_cookie(x)
leave
retn
sub_401ACE endp



; Attributes: bp-based frame

; int __cdecl sub_401B61(LPCSTR	lpMultiByteStr,	wchar_t	*Mode)
sub_401B61 proc	near

Filename= word ptr -20Ch
var_4= dword ptr -4
lpMultiByteStr=	dword ptr  8
Mode= dword ptr	 0Ch

push	ebp
mov	ebp, esp
sub	esp, 20Ch
mov	eax, ___security_cookie
xor	eax, ebp
mov	[ebp+var_4], eax
mov	eax, [ebp+lpMultiByteStr]
push	esi
mov	esi, [ebp+Mode]
push	104h		; cchWideChar
lea	ecx, [ebp+Filename]
push	ecx		; lpWideCharStr
push	0FFFFFFFFh	; cbMultiByte
push	eax		; lpMultiByteStr
push	0		; dwFlags
push	0FDE9h		; CodePage
call	ds:MultiByteToWideChar
lea	eax, [ebp+Filename]
push	esi		; Mode
push	eax		; Filename
call	ds:_wfopen
pop	ecx
pop	ecx
mov	ecx, [ebp+var_4]
xor	ecx, ebp
pop	esi
call	@__security_check_cookie@4 ; __security_check_cookie(x)
leave
retn
sub_401B61 endp




sub_401BB4 proc	near
jmp	short loc_401BD3

loc_401BB6:		; hLibModule
push	dword ptr [eax]
call	ds:FreeLibrary
mov	eax, dword_404144
mov	ecx, [eax+4]
push	eax		; void *
mov	dword_404144, ecx
call	??3@YAXPAX@Z	; operator delete(void *)
pop	ecx

loc_401BD3:
mov	eax, dword_404144
test	eax, eax
jnz	short loc_401BB6
retn
sub_401BB4 endp	; sp-analysis failed



; Attributes: bp-based frame

sub_401BDD proc	near

ProcName= byte ptr -204h
var_4= dword ptr -4
arg_0= dword ptr  8

push	ebp
mov	ebp, esp
sub	esp, 204h
mov	eax, ___security_cookie
xor	eax, ebp
mov	[ebp+var_4], eax
push	esi
mov	esi, [ebp+arg_0]
push	edi
xor	edi, edi
jmp	short loc_401C3E

loc_401BF9:
push	eax
push	offset aS	; "%s"
lea	eax, [ebp+ProcName]
push	200h		; Count
push	eax		; Dest
call	ds:_snprintf
mov	eax, dword_404144
mov	eax, [eax]
add	esp, 10h
lea	ecx, [ebp+ProcName]
push	ecx		; lpProcName
push	eax		; hModule
call	ds:GetProcAddress
mov	ecx, [esi+4]
mov	[ecx], eax
mov	eax, [esi+4]
cmp	dword ptr [eax], 0
jnz	short loc_401C3B
mov	edi, 80460003h

loc_401C3B:
add	esi, 8

loc_401C3E:
mov	eax, [esi]
test	eax, eax
jnz	short loc_401BF9
mov	ecx, [ebp+var_4]
mov	eax, edi
pop	edi
xor	ecx, ebp
pop	esi
call	@__security_check_cookie@4 ; __security_check_cookie(x)
leave
retn
sub_401BDD endp




sub_401C54 proc	near
mov	byte_404148, 1
retn
sub_401C54 endp




sub_401C5C proc	near
mov	eax, dword_404078
test	eax, eax
jnz	short loc_401C6B
mov	eax, 0C1F30001h
retn

loc_401C6B:
jmp	eax
sub_401C5C endp




sub_401C6D proc	near
mov	eax, dword_404090
test	eax, eax
jnz	short loc_401C7C
mov	eax, 0C1F30001h
retn

loc_401C7C:
jmp	eax
sub_401C6D endp




sub_401C7E proc	near
mov	eax, dword_4040DC
test	eax, eax
jnz	short loc_401C8D
mov	eax, 0C1F30001h
retn

loc_401C8D:
jmp	eax
sub_401C7E endp




sub_401C8F proc	near
mov	eax, dword_404094
test	eax, eax
jz	short locret_401C9A
jmp	eax

locret_401C9A:
retn
sub_401C8F endp




sub_401C9B proc	near
mov	eax, dword_4040E0
test	eax, eax
jnz	short loc_401CAA
mov	eax, 0C1F30001h
retn

loc_401CAA:
jmp	eax
sub_401C9B endp




sub_401CAC proc	near
mov	eax, dword_4040AC
test	eax, eax
jz	short locret_401CB7
jmp	eax

locret_401CB7:
retn
sub_401CAC endp




sub_401CB8 proc	near
mov	eax, dword_4040C0
test	eax, eax
jnz	short loc_401CC7
mov	eax, 0C1F30001h
retn

loc_401CC7:
jmp	eax
sub_401CB8 endp




sub_401CC9 proc	near
mov	eax, dword_4040D0
test	eax, eax
jnz	short loc_401CD3
retn

loc_401CD3:
jmp	eax
sub_401CC9 endp




sub_401CD5 proc	near
mov	eax, dword_4040D8
test	eax, eax
jz	short locret_401CE0
jmp	eax

locret_401CE0:
retn
sub_401CD5 endp




sub_401CE1 proc	near
mov	eax, dword_4040F4
test	eax, eax
jz	short locret_401CEC
jmp	eax

locret_401CEC:
retn
sub_401CE1 endp




sub_401CED proc	near
mov	eax, dword_4040F8
test	eax, eax
jz	short locret_401CF8
jmp	eax

locret_401CF8:
retn
sub_401CED endp



; Attributes: bp-based frame fpd=190h

; int __cdecl sub_401CF9(void *Src)
sub_401CF9 proc	near

File= dword ptr	-210h
Buf= byte ptr -20Ch
Dst= byte ptr -108h
Dest= byte ptr -107h
var_4= dword ptr -4
Src= dword ptr	8

push	ebp
lea	ebp, [esp-190h]
sub	esp, 210h
mov	eax, ___security_cookie
xor	eax, ebp
mov	[ebp+190h+var_4], eax
mov	eax, [ebp+190h+Src]
mov	dword_404058, 1
mov	dword_40405C, 0ECh
test	eax, eax
jnz	short loc_401D37
mov	eax, offset Source ; "xul.dll"

loc_401D37:
mov	cl, [eax]
push	ebx
push	esi
xor	esi, esi
push	edi
mov	edi, eax
test	cl, cl
jz	short loc_401D9D

loc_401D44:		; "/\\"
mov	ebx, offset asc_4035AC
mov	dl, 2Fh

loc_401D4B:
cmp	dl, cl
jnz	short loc_401D51
mov	esi, edi

loc_401D51:
inc	ebx
mov	dl, [ebx]
test	dl, dl
jnz	short loc_401D4B
inc	edi
mov	cl, [edi]
test	cl, cl
jnz	short loc_401D44
test	esi, esi
jz	short loc_401D9D
sub	esi, eax
cmp	esi, 0F0h
ja	loc_401EB6
push	esi		; Size
push	eax		; Src
lea	eax, [ebp+190h+Dst]
push	eax		; Dst
call	memcpy
lea	eax, [ebp+esi+190h+Dst]
push	offset aDependentlibs_ ; "\\dependentlibs.list"
push	eax		; Dest
call	strcpy
add	esp, 14h
lea	ebx, [ebp+esi+190h+Dest]
jmp	short loc_401DB6

loc_401D9D:
lea	eax, [ebp+190h+Dst]
push	offset aDependentlib_0 ; "dependentlibs.list"
push	eax		; Dest
call	strcpy
pop	ecx
pop	ecx
lea	ebx, [ebp+190h+Dst]

loc_401DB6:		; "MOZ_RUN_GTEST"
push	offset aMoz_run_gtest
call	ds:getenv
pop	ecx
test	eax, eax
jz	short loc_401DD9
lea	eax, [ebp+190h+Dst]
push	offset a_gtest	; ".gtest"
push	eax		; Dest
call	strcat
pop	ecx
pop	ecx

loc_401DD9:
lea	eax, [ebp+190h+Dst]
push	offset Mode	; "rt"
push	eax		; lpMultiByteStr
call	sub_401B61
pop	ecx
pop	ecx
mov	[ebp+190h+File], eax
test	eax, eax
jz	loc_401EB6
mov	edi, ds:fgets
mov	byte ptr [ebx],	0
push	eax
mov	esi, 104h
jmp	short loc_401E5E

loc_401E08:
lea	eax, [ebp+190h+Buf]
push	eax		; Str
call	strlen
pop	ecx
test	eax, eax
jz	short loc_401E5B
cmp	[ebp+190h+Buf],	23h
jz	short loc_401E5B
lea	ecx, [ebp+eax+190h+File+3]
cmp	byte ptr [ecx],	0Ah
jnz	short loc_401E28
mov	byte ptr [ecx],	0

loc_401E28:
lea	ecx, [ebp+190h+Dst]
sub	eax, ecx
add	eax, ebx
cmp	eax, esi
ja	short loc_401EAC
lea	eax, [ebp+190h+Buf]
push	eax		; Source
push	ebx		; Dest
call	strcpy
movzx	eax, byte_404148
push	eax		; char
lea	eax, [ebp+190h+Dst]
push	eax		; lpMultiByteStr
call	sub_401ACE
add	esp, 10h
test	al, al
jz	short loc_401EBD

loc_401E5B:		; File
push	[ebp+190h+File]

loc_401E5E:
lea	eax, [ebp+190h+Buf]
push	esi		; MaxCount
push	eax		; Buf
call	edi ; fgets
add	esp, 0Ch
test	eax, eax
jnz	short loc_401E08
mov	eax, dword_404144
mov	eax, [eax]
push	offset aNs_getfrozenfu ; "NS_GetFrozenFunctions"
push	eax		; hModule
call	ds:GetProcAddress
mov	esi, eax
test	esi, esi
jz	short loc_401EBD
push	[ebp+190h+File]	; File
call	ds:fclose
pop	ecx
push	0
push	offset dword_404058
call	esi
mov	esi, eax
shr	eax, 1Fh
pop	ecx
pop	ecx
test	al, 1
jz	short loc_401EC4
call	sub_401BB4
mov	eax, esi
jmp	short loc_401EC6

loc_401EAC:		; File
push	[ebp+190h+File]
call	ds:fclose
pop	ecx

loc_401EB6:
mov	eax, 80040111h
jmp	short loc_401EC6

loc_401EBD:
call	sub_401BB4
jmp	short loc_401EAC

loc_401EC4:
xor	eax, eax

loc_401EC6:
mov	ecx, [ebp+190h+var_4]
pop	edi
pop	esi
xor	ecx, ebp
pop	ebx
call	@__security_check_cookie@4 ; __security_check_cookie(x)
add	ebp, 190h
leave
retn
sub_401CF9 endp




; int __cdecl sub_401EDE(int, char *Src)
sub_401EDE proc	near

arg_0= dword ptr  4
Src= dword ptr	8

push	esi
mov	esi, [esp+4+arg_0]
push	dword ptr [esi]
call	sub_401CD5
cmp	[esp+8+Src], 0
pop	ecx
jz	short loc_401F00
push	[esp+4+Src]	; Src
call	sub_4021B5
pop	ecx
mov	[esi], eax
pop	esi
retn

loc_401F00:
and	dword ptr [esi], 0
pop	esi
retn
sub_401EDE endp




; int __thiscall sub_401F05(void *Dst, int)
sub_401F05 proc	near

arg_0= dword ptr  4

push	esi
push	edi
push	3Ch		; Size
mov	edi, ecx
push	0		; Val
push	edi		; Dst
call	memset
mov	esi, [esp+14h+arg_0]
mov	eax, [esi]
mov	[edi], eax
push	dword ptr [esi+8] ; Src
lea	eax, [edi+8]
push	eax		; int
call	sub_401EDE
push	dword ptr [esi+0Ch] ; Src
lea	eax, [edi+0Ch]
push	eax		; int
call	sub_401EDE
push	dword ptr [esi+10h] ; Src
lea	eax, [edi+10h]
push	eax		; int
call	sub_401EDE
push	dword ptr [esi+14h] ; Src
lea	eax, [edi+14h]
push	eax		; int
call	sub_401EDE
push	dword ptr [esi+18h] ; Src
lea	eax, [edi+18h]
push	eax		; int
call	sub_401EDE
push	dword ptr [esi+1Ch] ; Src
lea	eax, [edi+1Ch]
push	eax		; int
call	sub_401EDE
push	dword ptr [esi+34h] ; Src
lea	eax, [edi+34h]
push	eax		; int
call	sub_401EDE
add	esp, 44h
push	dword ptr [esi+4]
lea	eax, [edi+4]
push	eax
call	sub_401348
mov	eax, [esi+20h]
pop	ecx
mov	[edi+20h], eax
cmp	dword ptr [esi], 24h
pop	ecx
jbe	short loc_401FB2
push	dword ptr [esi+24h]
lea	eax, [edi+24h]
push	eax
call	sub_401348
push	dword ptr [esi+28h] ; Src
lea	eax, [edi+28h]
push	eax		; int
call	sub_401EDE
push	dword ptr [esi+2Ch] ; Src
lea	eax, [edi+2Ch]
push	eax		; int
call	sub_401EDE
add	esp, 18h

loc_401FB2:
cmp	dword ptr [esi], 30h
jbe	short loc_401FC5
push	dword ptr [esi+30h] ; Src
lea	eax, [edi+30h]
push	eax		; int
call	sub_401EDE
pop	ecx
pop	ecx

loc_401FC5:
cmp	dword ptr [esi], 38h
jbe	short loc_401FD8
push	dword ptr [esi+38h] ; Src
lea	eax, [edi+38h]
push	eax		; int
call	sub_401EDE
pop	ecx
pop	ecx

loc_401FD8:
mov	eax, edi
pop	edi
pop	esi
retn	4
sub_401F05 endp




sub_401FDF proc	near
push	esi
mov	esi, ecx
push	edi
push	dword ptr [esi+8]
call	sub_401CD5
xor	edi, edi
mov	[esi+8], edi
push	dword ptr [esi+0Ch]
call	sub_401CD5
mov	[esi+0Ch], edi
push	dword ptr [esi+10h]
call	sub_401CD5
mov	[esi+10h], edi
push	dword ptr [esi+14h]
call	sub_401CD5
mov	[esi+14h], edi
push	dword ptr [esi+18h]
call	sub_401CD5
mov	[esi+18h], edi
push	dword ptr [esi+1Ch]
call	sub_401CD5
mov	[esi+1Ch], edi
push	dword ptr [esi+34h]
call	sub_401CD5
mov	[esi+34h], edi
mov	eax, [esi+4]
add	esp, 1Ch
cmp	eax, edi
jz	short loc_402045
mov	ecx, [eax]
push	eax
call	dword ptr [ecx+8]
mov	[esi+4], edi

loc_402045:
lea	eax, [esi+24h]
push	edi
push	eax
call	sub_401348
push	dword ptr [esi+28h]
call	sub_401CD5
mov	[esi+28h], edi
push	dword ptr [esi+2Ch]
call	sub_401CD5
mov	[esi+2Ch], edi
push	dword ptr [esi+30h]
call	sub_401CD5
mov	[esi+30h], edi
push	dword ptr [esi+38h]
call	sub_401CD5
add	esp, 18h
mov	[esi+38h], edi
pop	edi
pop	esi
retn
sub_401FDF endp



; Attributes: bp-based frame fpd=0FF94h

; int __cdecl sub_402081(HANDLE	hFile, LARGE_INTEGER liDistanceToMove)
sub_402081 proc	near

NewFilePointer=	LARGE_INTEGER ptr -10014h
NumberOfBytesRead= dword ptr -1000Ch
var_10008= dword ptr -10008h
Buffer=	byte ptr -10004h
var_4= dword ptr -4
hFile= dword ptr  8
liDistanceToMove= LARGE_INTEGER	ptr  0Ch

push	ebp
lea	ebp, [esp-0FF94h]
mov	eax, 10014h
call	__alloca_probe
mov	eax, ___security_cookie
xor	eax, ebp
mov	[ebp+0FF94h+var_4], eax
push	ebx
mov	ebx, [ebp+0FF94h+hFile]
push	esi
mov	esi, ds:SetFilePointerEx
push	edi
push	1		; dwMoveMethod
lea	edx, [ebp+0FF94h+NewFilePointer]
push	edx		; lpNewFilePointer
xor	ecx, ecx
push	ecx
xor	eax, eax
push	eax		; liDistanceToMove
push	ebx		; hFile
xor	edi, edi
call	esi ; SetFilePointerEx
test	eax, eax
jz	short loc_402124
cmp	dword ptr [ebp+0FF94h+liDistanceToMove], edi
jz	short loc_4020DE
push	edi		; dwMoveMethod
push	edi		; lpNewFilePointer
xor	eax, eax
push	eax
push	dword ptr [ebp+0FF94h+liDistanceToMove]	; liDistanceToMove
push	ebx		; hFile
call	esi ; SetFilePointerEx
test	eax, eax
jz	short loc_402124

loc_4020DE:
mov	[ebp+0FF94h+var_10008],	edi
cmp	dword ptr [ebp+0FF94h+liDistanceToMove+4], edi
jbe	short loc_402119
mov	edi, 10000h

loc_4020EE:		; lpOverlapped
push	0
lea	eax, [ebp+0FF94h+NumberOfBytesRead]
push	eax		; lpNumberOfBytesRead
push	edi		; nNumberOfBytesToRead
lea	eax, [ebp+0FF94h+Buffer]
push	eax		; lpBuffer
push	ebx		; hFile
call	ds:ReadFile
test	eax, eax
jz	short loc_402117
cmp	[ebp+0FF94h+NumberOfBytesRead],	edi
jnz	short loc_402117
add	[ebp+0FF94h+var_10008],	edi
mov	eax, [ebp+0FF94h+var_10008]
cmp	eax, dword ptr [ebp+0FF94h+liDistanceToMove+4]
jb	short loc_4020EE

loc_402117:
xor	edi, edi

loc_402119:		; dwMoveMethod
push	edi
push	edi		; lpNewFilePointer
push	dword ptr [ebp+0FF94h+NewFilePointer+4]
push	dword ptr [ebp+0FF94h+NewFilePointer] ;	liDistanceToMove
push	ebx		; hFile
call	esi ; SetFilePointerEx

loc_402124:
mov	ecx, [ebp+0FF94h+var_4]
pop	edi
pop	esi
xor	ecx, ebp
pop	ebx
call	@__security_check_cookie@4 ; __security_check_cookie(x)
add	ebp, 0FF94h
leave
retn
sub_402081 endp



; Attributes: bp-based frame

; int __cdecl sub_40213C(LPCWSTR lpFileName, LARGE_INTEGER liDistanceToMove, int)
sub_40213C proc	near

lpFileName= dword ptr  8
liDistanceToMove= LARGE_INTEGER	ptr  0Ch
arg_C= dword ptr  14h

push	ebp
mov	ebp, esp
cmp	[ebp+lpFileName], 0
jnz	short loc_402151
mov	eax, [ebp+arg_C]
test	eax, eax
jz	short loc_40219A
or	dword ptr [eax], 0FFFFFFFFh
pop	ebp
retn

loc_402151:
push	esi
push	edi
push	0		; hTemplateFile
push	8000000h	; dwFlagsAndAttributes
push	3		; dwCreationDisposition
push	0		; lpSecurityAttributes
push	1		; dwShareMode
push	80000000h	; dwDesiredAccess
push	[ebp+lpFileName] ; lpFileName
call	ds:CreateFileW
mov	edi, [ebp+arg_C]
mov	esi, eax
test	edi, edi
jz	short loc_402179
mov	[edi], esi

loc_402179:
cmp	esi, 0FFFFFFFFh
jz	short loc_402198
push	dword ptr [ebp+liDistanceToMove+4]
push	dword ptr [ebp+liDistanceToMove] ; liDistanceToMove
push	esi		; hFile
call	sub_402081
add	esp, 0Ch
test	edi, edi
jnz	short loc_402198
push	esi		; hObject
call	ds:CloseHandle

loc_402198:
pop	edi
pop	esi

loc_40219A:
pop	ebp
retn
sub_40213C endp




; int __cdecl sub_40219C(LPCWSTR lpFileName)
sub_40219C proc	near

lpFileName= dword ptr  4

xor	eax, eax
cmp	[esp+lpFileName], eax
jz	short locret_4021B4
push	eax		; int
push	0FFFFFFFFh
push	eax		; liDistanceToMove
push	[esp+0Ch+lpFileName] ; lpFileName
call	sub_40213C
add	esp, 10h

locret_4021B4:
retn
sub_40219C endp




; int __cdecl sub_4021B5(char *Src)
sub_4021B5 proc	near

Src= dword ptr	4

push	esi
push	edi
push	[esp+8+Src]	; Str
call	strlen
mov	esi, eax
lea	eax, [esi+1]
push	eax
call	sub_401CC9
mov	edi, eax
pop	ecx
pop	ecx
test	edi, edi
jz	short loc_4021E5
push	esi		; Size
push	[esp+0Ch+Src]	; Src
push	edi		; Dst
call	memcpy
add	esp, 0Ch
mov	byte ptr [edi+esi], 0

loc_4021E5:
mov	eax, edi
pop	edi
pop	esi
retn
sub_4021B5 endp

; [0000004B BYTES: COLLAPSED FUNCTION _pre_cpp_init. PRESS KEYPAD "+" TO EXPAND]
; [00000189 BYTES: COLLAPSED FUNCTION ___tmainCRTStartup. PRESS	KEYPAD "+" TO EXPAND]
; [000000BA BYTES: COLLAPSED FUNCTION $LN33. PRESS KEYPAD "+" TO EXPAND]
; [0000000A BYTES: COLLAPSED FUNCTION start. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION operator delete[](void *). PRESS KEYPAD "+" TO EXPAND]
; [0000000B BYTES: COLLAPSED FUNCTION unknown_libname_1. PRESS KEYPAD "+" TO EXPAND]
; [0000000F BYTES: COLLAPSED FUNCTION __security_check_cookie(x). PRESS	KEYPAD "+" TO EXPAND]
align 10h
; [0000002B BYTES: COLLAPSED FUNCTION __alloca_probe. PRESS KEYPAD "+" TO EXPAND]
align 10h
; [00000034 BYTES: COLLAPSED FUNCTION __allmul.	PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION strcpy. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION operator new(uint). PRESS	KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION operator delete(void *). PRESS KEYPAD "+"	TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION strlen. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION strcat. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION memcpy. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION memset. PRESS KEYPAD "+" TO EXPAND]
; [00000042 BYTES: COLLAPSED FUNCTION __CxxUnhandledExceptionFilter(_EXCEPTION_POINTERS	*). PRESS KEYPAD "+" TO	EXPAND]
; [0000000E BYTES: COLLAPSED FUNCTION $LN5. PRESS KEYPAD "+" TO	EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _amsg_exit. PRESS	KEYPAD "+" TO EXPAND]
; [000000A1 BYTES: COLLAPSED FUNCTION __onexit.	PRESS KEYPAD "+" TO EXPAND]
; [00000017 BYTES: COLLAPSED FUNCTION _atexit. PRESS KEYPAD "+"	TO EXPAND]



sub_40264C proc	near
mov	edi, edi
push	esi
mov	eax, offset unk_403888
mov	esi, offset unk_403888
push	edi
mov	edi, eax
cmp	eax, esi
jnb	short loc_40266F

loc_402660:
mov	eax, [edi]
test	eax, eax
jz	short loc_402668
call	eax

loc_402668:
add	edi, 4
cmp	edi, esi
jb	short loc_402660

loc_40266F:
pop	edi
pop	esi
retn
sub_40264C endp




; void __cdecl sub_402672()
sub_402672 proc	near
mov	edi, edi
push	esi
mov	eax, offset unk_403890
mov	esi, offset unk_403890
push	edi
mov	edi, eax
cmp	eax, esi
jnb	short loc_402695

loc_402686:
mov	eax, [edi]
test	eax, eax
jz	short loc_40268E
call	eax

loc_40268E:
add	edi, 4
cmp	edi, esi
jb	short loc_402686

loc_402695:
pop	edi
pop	esi
retn
sub_402672 endp

; [00000006 BYTES: COLLAPSED FUNCTION _XcptFilter. PRESS KEYPAD	"+" TO EXPAND]
align 10h
; [00000035 BYTES: COLLAPSED FUNCTION __ValidateImageBase. PRESS KEYPAD	"+" TO EXPAND]
align 10h
; [00000044 BYTES: COLLAPSED FUNCTION __FindPESection. PRESS KEYPAD "+"	TO EXPAND]
align 10h
; [000000BC BYTES: COLLAPSED FUNCTION __IsNonwritableInCurrentImage. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _initterm. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _initterm_e. PRESS KEYPAD	"+" TO EXPAND]
align 10h
; [00000045 BYTES: COLLAPSED FUNCTION __SEH_prolog4. PRESS KEYPAD "+" TO EXPAND]
; [00000014 BYTES: COLLAPSED FUNCTION __SEH_epilog4. PRESS KEYPAD "+" TO EXPAND]
; [00000025 BYTES: COLLAPSED FUNCTION __except_handler4. PRESS KEYPAD "+" TO EXPAND]
; [00000028 BYTES: COLLAPSED FUNCTION __setdefaultprecision. PRESS KEYPAD "+" TO EXPAND]
; [00000003 BYTES: COLLAPSED FUNCTION $LN7_0. PRESS KEYPAD "+" TO EXPAND]
; [0000009B BYTES: COLLAPSED FUNCTION ___security_init_cookie. PRESS KEYPAD "+"	TO EXPAND]
; [00000106 BYTES: COLLAPSED FUNCTION ___report_gsfailure. PRESS KEYPAD	"+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION terminate(void). PRESS KEYPAD "+"	TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _unlock. PRESS KEYPAD "+"	TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION __dllonexit. PRESS KEYPAD	"+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _lock. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _except_handler4_common. PRESS KEYPAD "+"	TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _invoke_watson. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _controlfp_s. PRESS KEYPAD "+" TO	EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _crt_debugger_hook. PRESS	KEYPAD "+" TO EXPAND]
align 4
dd 61h dup(0)
dd 100h	dup(?)
_text ends

; Section 2. (virtual address 00003000)
; Virtual size			: 00000FB4 (   4020.)
; Section size in file		: 00001000 (   4096.)
; Offset to raw	data for section: 00002000
; Flags	40000040: Data Readable
; Alignment	: default
;
; Imports from KERNEL32.dll
;

; Segment type:	Externs
; _idata
; BOOL __stdcall SetEnvironmentVariableW(LPCWSTR lpName, LPCWSTR lpValue)
extrn SetEnvironmentVariableW:dword
; DWORD	__stdcall ExpandEnvironmentStringsW(LPCWSTR lpSrc, LPWSTR lpDst, DWORD nSize)
extrn ExpandEnvironmentStringsW:dword
; DWORD	__stdcall GetEnvironmentVariableW(LPCWSTR lpName, LPWSTR lpBuffer, DWORD nSize)
extrn GetEnvironmentVariableW:dword
; DWORD	__stdcall GetModuleFileNameW(HMODULE hModule, LPWCH lpFilename,	DWORD nSize)
extrn GetModuleFileNameW:dword
; int __stdcall	MultiByteToWideChar(UINT CodePage, DWORD dwFlags, LPCSTR lpMultiByteStr, int cbMultiByte, LPWSTR lpWideCharStr,	int cchWideChar)
extrn MultiByteToWideChar:dword
; DWORD	__stdcall GetTickCount()
extrn GetTickCount:dword
; FARPROC __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName)
extrn GetProcAddress:dword
; HMODULE __stdcall GetModuleHandleW(LPCWSTR lpModuleName)
extrn GetModuleHandleW:dword
; BOOL __stdcall QueryPerformanceFrequency(LARGE_INTEGER *lpFrequency)
extrn QueryPerformanceFrequency:dword
; DWORD	__stdcall GetFileAttributesW(LPCWSTR lpFileName)
extrn GetFileAttributesW:dword
; int __stdcall	WideCharToMultiByte(UINT CodePage, DWORD dwFlags, LPCWSTR lpWideCharStr, int cchWideChar, LPSTR	lpMultiByteStr,	int cbMultiByte, LPCSTR	lpDefaultChar, LPBOOL lpUsedDefaultChar)
extrn WideCharToMultiByte:dword
; BOOL __stdcall GetProcessIoCounters(HANDLE hProcess, PIO_COUNTERS lpIoCounters)
extrn GetProcessIoCounters:dword
; HANDLE __stdcall GetCurrentProcess()
extrn GetCurrentProcess:dword
extrn SetDllDirectoryW:dword
; BOOL __stdcall IsDebuggerPresent()
extrn IsDebuggerPresent:dword
; LONG __stdcall UnhandledExceptionFilter(struct _EXCEPTION_POINTERS *ExceptionInfo)
extrn UnhandledExceptionFilter:dword
; void __stdcall GetSystemTimeAsFileTime(LPFILETIME lpSystemTimeAsFileTime)
extrn GetSystemTimeAsFileTime:dword
; DWORD	__stdcall GetCurrentProcessId()
extrn GetCurrentProcessId:dword
; DWORD	__stdcall GetCurrentThreadId()
extrn GetCurrentThreadId:dword
; BOOL __stdcall QueryPerformanceCounter(LARGE_INTEGER *lpPerformanceCount)
extrn QueryPerformanceCounter:dword
; PVOID	__stdcall DecodePointer(PVOID Ptr)
extrn DecodePointer:dword
; LPTOP_LEVEL_EXCEPTION_FILTER __stdcall SetUnhandledExceptionFilter(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter)
extrn SetUnhandledExceptionFilter:dword
; PVOID	__stdcall EncodePointer(PVOID Ptr)
extrn EncodePointer:dword
; BOOL __stdcall HeapSetInformation(HANDLE HeapHandle, HEAP_INFORMATION_CLASS HeapInformationClass, PVOID HeapInformation, SIZE_T HeapInformationLength)
extrn HeapSetInformation:dword
; LONG __stdcall InterlockedCompareExchange(volatile LONG *Destination,	LONG Exchange, LONG Comperand)
extrn InterlockedCompareExchange:dword
; void __stdcall Sleep(DWORD dwMilliseconds)
extrn Sleep:dword
; LONG __stdcall InterlockedExchange(volatile LONG *Target, LONG Value)
extrn InterlockedExchange:dword
; HANDLE __stdcall CreateFileW(LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD	dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile)
extrn CreateFileW:dword
; BOOL __stdcall CloseHandle(HANDLE hObject)
extrn CloseHandle:dword
; BOOL __stdcall SetFilePointerEx(HANDLE hFile,	LARGE_INTEGER liDistanceToMove,	PLARGE_INTEGER lpNewFilePointer, DWORD dwMoveMethod)
extrn SetFilePointerEx:dword
; BOOL __stdcall ReadFile(HANDLE hFile,	LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped)
extrn ReadFile:dword
; BOOL __stdcall FreeLibrary(HMODULE hLibModule)
extrn FreeLibrary:dword
; HMODULE __stdcall LoadLibraryExW(LPCWSTR lpLibFileName, HANDLE hFile,	DWORD dwFlags)
extrn LoadLibraryExW:dword
; DWORD	__stdcall GetLastError()
extrn GetLastError:dword
; BOOL __stdcall TerminateProcess(HANDLE hProcess, UINT	uExitCode)
extrn TerminateProcess:dword

;
; Imports from MSVCR100.dll
;
extrn __imp__amsg_exit:dword
extrn __wgetmainargs:dword
; void __cdecl cexit()
extrn _cexit:dword
; void __cdecl exit(int	Code)
extrn _exit:dword
; void __cdecl exit(int	Code)
extrn exit:dword
extrn __winitenv:dword
extrn __imp__initterm:dword
extrn __imp__initterm_e:dword
extrn _configthreadlocale:dword
extrn __setusermatherr:dword
extrn _commode:dword
; int fmode
extrn _fmode:dword
extrn __set_app_type:dword
; int __cdecl vsnprintf_s(char *DstBuf,	size_t DstSize,	size_t MaxCount, const char *Format, va_list ArgList)
extrn _vsnprintf_s:dword
; __declspec(dllimport)	void __cdecl terminate(void)
extrn __imp_?terminate@@YAXXZ:dword
extrn __imp__unlock:dword
extrn __imp___dllonexit:dword
extrn __imp__lock:dword
; _onexit_t __cdecl onexit(_onexit_t Func)
extrn _onexit:dword
extrn __imp__except_handler4_common:dword
extrn __imp__invoke_watson:dword
; errno_t __cdecl _controlfp_s(unsigned	int *CurrentState, unsigned int	NewValue, unsigned int Mask)
extrn __imp__controlfp_s:dword
extrn __imp__crt_debugger_hook:dword
; void *__cdecl	memset(void *Dst, int Val, size_t Size)
extrn __imp_memset:dword
; void *__cdecl	memcpy(void *Dst, const	void *Src, size_t Size)
extrn __imp_memcpy:dword
; char *__cdecl	strcat(char *Dest, const char *Source)
extrn __imp_strcat:dword
; char *__cdecl	fgets(char *Buf, int MaxCount, FILE *File)
extrn fgets:dword
; size_t __cdecl strlen(const char *Str)
extrn __imp_strlen:dword
; __declspec(dllimport)	void __cdecl operator delete(void *)
extrn __imp_??3@YAXPAX@Z:dword
; int __cdecl fclose(FILE *File)
extrn fclose:dword
; FILE *__cdecl	wfopen(const wchar_t *Filename,	const wchar_t *Mode)
extrn _wfopen:dword
; __declspec(dllimport)	void * __cdecl operator	new(unsigned int)
extrn __imp_??2@YAPAXI@Z:dword
; char *__cdecl	strcpy(char *Dest, const char *Source)
extrn __imp_strcpy:dword
; char *__cdecl	getenv(const char *VarName)
extrn getenv:dword
; int snprintf(char *Dest, size_t Count, const char *Format, ...)
extrn _snprintf:dword
; int __cdecl stricmp(const char *Str1,	const char *Str2)
extrn _stricmp:dword
; size_t __cdecl wcslen(const wchar_t *Str)
extrn wcslen:dword
; __declspec(dllimport)	void __cdecl operator delete[](void *)
extrn __imp_??_V@YAXPAX@Z:dword
; char *__cdecl	strrchr(const char *Str, int Ch)
extrn strrchr:dword
extrn __imp__XcptFilter:dword
; int __cdecl putenv(const char	*EnvString)
extrn _putenv:dword

;
; Imports from USER32.dll
;
; int __stdcall	MessageBoxW(HWND hWnd, LPCWSTR lpText, LPCWSTR lpCaption, UINT uType)
extrn MessageBoxW:dword



; Segment type:	Pure data
; Segment permissions: Read
_rdata segment para public 'DATA' use32
assume cs:_rdata
;org 403140h
unk_403140 db	 0
db    0
db    0
db    0
dd offset _pre_cpp_init
unk_403148 db	 0
db    0
db    0
db    0
unk_40314C db	 0
db    0
db    0
db    0
dd offset $LN33		; _pre_c_init
dd offset $LN5
unk_403158 db	 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db  6Bh	; k
db 0E1h	; ·
db  38h	; 8
db  52h	; R
db    0
db    0
db    0
db    0
db    2
db    0
db    0
db    0
db  76h	; v
db    0
db    0
db    0
db    0
db  38h	; 8
db    0
db    0
db    0
db  28h	; (
db    0
db    0
aXre_disablewri	db 'XRE_DisableWritePoisoning',0
db    0
db    0
aXre_main db 'XRE_main',0
db    0
db    0
db    0
aXre_startuptim	db 'XRE_StartupTimelineRecord',0
db    0
db    0
aXre_telemetrya	db 'XRE_TelemetryAccumulate',0
aXre_setupdllbl	db 'XRE_SetupDllBlocklist',0
db    0
db    0
aXre_freeappdat	db 'XRE_FreeAppData',0
aXre_createappd	db 'XRE_CreateAppData',0
db    0
db    0
aXre_getfilefro	db 'XRE_GetFileFromPath',0
aTestconsoleid db 'testconsoleid=',0
align 4
aHttpsCrashRepo	db 'https://crash-reports.mozilla.com/s'
db 'ubmit?id={ec8030f7-c20a-464f-9b0e-1'
db '3a3a9e97384}&version=25.0&buildid=2'
db '0130917123208',0
align 10h
aEc8030f7C20a46	db '{ec8030f7-c20a-464f-9b0e-13a3a9e973'
db '84}',0
align 4
a20130917123208	db '20130917123208',0
align 4
a25_0 db '25.0',0
align 10h
aFirefox db 'Firefox',0
aMozilla db 'Mozilla',0
asc_403300 db '<',0
align 8
dd offset aMozilla	; "Mozilla"
dd offset aFirefox	; "Firefox"
dd offset a25_0		; "25.0"
dd offset a20130917123208 ; "20130917123208"
dd offset aEc8030f7C20a46 ; "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}"
align 10h
db  0Eh
db    0
db    0
db    0
db    0
db    0
db    0
db    0
dd offset a25_0		; "25.0"
dd offset a25_0		; "25.0"
dd offset aHttpsCrashRepo ; "https://crash-reports.mozilla.com/submi"...
align 10h
off_403340 dd offset aXre_getfilefro ; "XRE_GetFileFromPath"
dd offset dword_404044
dd offset aXre_createappd ; "XRE_CreateAppData"
dd offset dword_40402C
dd offset aXre_freeappdat ; "XRE_FreeAppData"
dd offset dword_404034
dd offset aXre_setupdllbl ; "XRE_SetupDllBlocklist"
dd offset dword_404038
dd offset aXre_telemetrya ; "XRE_TelemetryAccumulate"
dd offset dword_404030
dd offset aXre_startuptim ; "XRE_StartupTimelineRecord"
dd offset dword_40403C
dd offset aXre_main	; "XRE_main"
dd offset dword_404040
dd offset aXre_disablewri ; "XRE_DisableWritePoisoning"
dd offset unk_404028
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
; const	WCHAR Name
Name:
unicode	0, <PATH>,0
align 4
; const	WCHAR Caption
Caption:
unicode	0, <Firefox>,0
; char ProcName[]
ProcName db 'GetTickCount64',0
align 4
; const	WCHAR ModuleName
ModuleName:
unicode	0, <kernel32.dll>,0
align 10h
aBrowser:
unicode	0, <browser>,0
; char aCouldnTFindThe[]
aCouldnTFindThe	db 'Couldn',27h,'t find the application di'
db 'rectory.',0Ah,0
align 4
aCouldnTReadApp	db 'Couldn',27h,'t read application.ini',0
align 4
aCouldnTSetS_ db 'Couldn',27h,'t set %s.',0Ah,0
align 10h
; char Format[]
Format db 'XUL_APP_FILE=%s',0
; char aApplication_in[]
aApplication_in	db 'application.ini path not recognized'
db ': ',27h,'%s',27h,0
align 4
; char aIncorrectNumbe[]
aIncorrectNumbe	db 'Incorrect number of arguments passe'
db 'd to -app',0
align 4
; char Str2[]
Str2 db	'app',0
; char aInvalidPathFou[]
aInvalidPathFou	db 'Invalid path found: ',27h,'%s',27h,0
align 4
; char VarName[]
VarName	db 'XUL_APP_FILE',0
align 4
aCouldnTLoadXre	db 'Couldn',27h,'t load XRE functions.',0Ah,0
align 4
; char aCouldnTLoadXpc[]
aCouldnTLoadXpc	db 'Couldn',27h,'t load XPCOM.',0Ah,0
align 4
; char aCouldNotFindTh[]
aCouldNotFindTh	db 'Could not find the Mozilla runtime.'
db 0Ah,0
align 4
; char Source[]
Source db 'xul.dll',0
unk_403544 db	 0
db    0
db    0
db    0
; char aS[]
aS db '%s',0
align 4
; char aNs_getfrozenfu[]
aNs_getfrozenfu	db 'NS_GetFrozenFunctions',0
align 4
; wchar_t Mode
Mode:
unicode	0, <rt>,0
align 4
; char a_gtest[]
a_gtest	db '.gtest',0
align 4
; char aMoz_run_gtest[]
aMoz_run_gtest db 'MOZ_RUN_GTEST',0
align 4
; char aDependentlib_0[]
aDependentlib_0	db 'dependentlibs.list',0
align 4
; char aDependentlibs_[]
aDependentlibs_	db '\dependentlibs.list',0
asc_4035AC db '/\',0
db    0
db    0
db    1
db    2
db    3
db    4
db    5
db    6
db    7
db    8
db    9
db  0Ah
db  0Bh
db  0Ch
db  0Dh
db  0Eh
db  0Fh
db  10h
db  11h
db  12h
db  13h
db  14h
db  15h
db  16h
db  17h
db  18h
db  19h
db  1Ah
db  1Bh
db  1Ch
db  1Dh
db  1Eh
db  1Fh
db  20h
db  21h	; !
db  22h	; "
db  23h	; #
db  24h	; $
db  25h	; %
db  26h	; &
db  27h	; '
db  28h	; (
db  29h	; )
db  2Ah	; *
db  2Bh	; +
db  2Ch	; ,
db  2Dh	; -
db  2Eh	; .
db  2Fh	; /
db  30h	; 0
db  31h	; 1
db  32h	; 2
db  33h	; 3
db  34h	; 4
db  35h	; 5
db  36h	; 6
db  37h	; 7
db  38h	; 8
db  39h	; 9
db  3Ah	; :
db  3Bh	; ;
db  3Ch	; <
db  3Dh	; =
db  3Eh	; >
db  3Fh	; ?
db  40h	; @
db  61h	; a
db  62h	; b
db  63h	; c
db  64h	; d
db  65h	; e
db  66h	; f
db  67h	; g
db  68h	; h
db  69h	; i
db  6Ah	; j
db  6Bh	; k
db  6Ch	; l
db  6Dh	; m
db  6Eh	; n
db  6Fh	; o
db  70h	; p
db  71h	; q
db  72h	; r
db  73h	; s
db  74h	; t
db  75h	; u
db  76h	; v
db  77h	; w
db  78h	; x
db  79h	; y
db  7Ah	; z
db  5Bh	; [
db  5Ch	; \
db  5Dh	; ]
db  5Eh	; ^
db  5Fh	; _
db  60h	; `
db  61h	; a
db  62h	; b
db  63h	; c
db  64h	; d
db  65h	; e
db  66h	; f
db  67h	; g
db  68h	; h
db  69h	; i
db  6Ah	; j
db  6Bh	; k
db  6Ch	; l
db  6Dh	; m
db  6Eh	; n
db  6Fh	; o
db  70h	; p
db  71h	; q
db  72h	; r
db  73h	; s
db  74h	; t
db  75h	; u
db  76h	; v
db  77h	; w
db  78h	; x
db  79h	; y
db  7Ah	; z
db  7Bh	; {
db  7Ch	; |
db  7Dh	; }
db  7Eh	; ~
db  7Fh	; 
db  80h	; Ä
db  81h	; Å
db  82h	; Ç
db  83h	; É
db  84h	; Ñ
db  85h	; Ö
db  86h	; Ü
db  87h	; á
db  88h	; à
db  89h	; â
db  8Ah	; ä
db  8Bh	; ã
db  8Ch	; å
db  8Dh	; ç
db  8Eh	; é
db  8Fh	; è
db  90h	; ê
db  91h	; ë
db  92h	; í
db  93h	; ì
db  94h	; î
db  95h	; ï
db  96h	; ñ
db  97h	; ó
db  98h	; ò
db  99h	; ô
db  9Ah	; ö
db  9Bh	; õ
db  9Ch	; ú
db  9Dh	; ù
db  9Eh	; û
db  9Fh	; ü
db 0A0h	; †
db 0A1h	; °
db 0A2h	; ¢
db 0A3h	; £
db 0A4h	; §
db 0A5h	; •
db 0A6h	; ¶
db 0A7h	; ß
db 0A8h	; ®
db 0A9h	; ©
db 0AAh	; ™
db 0ABh	; ´
db 0ACh	; ¨
db 0ADh	; ≠
db 0AEh	; Æ
db 0AFh	; Ø
db 0B0h	; ∞
db 0B1h	; ±
db 0B2h	; ≤
db 0B3h	; ≥
db 0B4h	; ¥
db 0B5h	; µ
db 0B6h	; ∂
db 0B7h	; ∑
db 0B8h	; ∏
db 0B9h	; π
db 0BAh	; ∫
db 0BBh	; ª
db 0BCh	; º
db 0BDh	; Ω
db 0BEh	; æ
db 0BFh	; ø
db 0C0h	; ¿
db 0C1h	; ¡
db 0C2h	; ¬
db 0C3h	; √
db 0C4h	; ƒ
db 0C5h	; ≈
db 0C6h	; ∆
db 0C7h	; «
db 0C8h	; »
db 0C9h	; …
db 0CAh	;  
db 0CBh	; À
db 0CCh	; Ã
db 0CDh	; Õ
db 0CEh	; Œ
db 0CFh	; œ
db 0D0h	; –
db 0D1h	; —
db 0D2h	; “
db 0D3h	; ”
db 0D4h	; ‘
db 0D5h	; ’
db 0D6h	; ÷
db 0D7h	; ◊
db 0D8h	; ÿ
db 0D9h	; Ÿ
db 0DAh	; ⁄
db 0DBh	; €
db 0DCh	; ‹
db 0DDh	; ›
db 0DEh	; ﬁ
db 0DFh	; ﬂ
db 0E0h	; ‡
db 0E1h	; ·
db 0E2h	; ‚
db 0E3h	; „
db 0E4h	; ‰
db 0E5h	; Â
db 0E6h	; Ê
db 0E7h	; Á
db 0E8h	; Ë
db 0E9h	; È
db 0EAh	; Í
db 0EBh	; Î
db 0ECh	; Ï
db 0EDh	; Ì
db 0EEh	; Ó
db 0EFh	; Ô
db 0F0h	; 
db 0F1h	; Ò
db 0F2h	; Ú
db 0F3h	; Û
db 0F4h	; Ù
db 0F5h	; ı
db 0F6h	; ˆ
db 0F7h	; ˜
db 0F8h	; ¯
db 0F9h	; ˘
db 0FAh	; ˙
db 0FBh	; ˚
db 0FCh	; ¸
db 0FDh	; ˝
db 0FEh	; ˛
db 0FFh
db    0
db    1
db    2
db    3
db    4
db    5
db    6
db    7
db    8
db    9
db  0Ah
db  0Bh
db  0Ch
db  0Dh
db  0Eh
db  0Fh
db  10h
db  11h
db  12h
db  13h
db  14h
db  15h
db  16h
db  17h
db  18h
db  19h
db  1Ah
db  1Bh
db  1Ch
db  1Dh
db  1Eh
db  1Fh
db  20h
db  21h	; !
db  22h	; "
db  23h	; #
db  24h	; $
db  25h	; %
db  26h	; &
db  27h	; '
db  28h	; (
db  29h	; )
db  2Ah	; *
db  2Bh	; +
db  2Ch	; ,
db  2Dh	; -
db  2Eh	; .
db  2Fh	; /
db  30h	; 0
db  31h	; 1
db  32h	; 2
db  33h	; 3
db  34h	; 4
db  35h	; 5
db  36h	; 6
db  37h	; 7
db  38h	; 8
db  39h	; 9
db  3Ah	; :
db  3Bh	; ;
db  3Ch	; <
db  3Dh	; =
db  3Eh	; >
db  3Fh	; ?
db  40h	; @
db  41h	; A
db  42h	; B
db  43h	; C
db  44h	; D
db  45h	; E
db  46h	; F
db  47h	; G
db  48h	; H
db  49h	; I
db  4Ah	; J
db  4Bh	; K
db  4Ch	; L
db  4Dh	; M
db  4Eh	; N
db  4Fh	; O
db  50h	; P
db  51h	; Q
db  52h	; R
db  53h	; S
db  54h	; T
db  55h	; U
db  56h	; V
db  57h	; W
db  58h	; X
db  59h	; Y
db  5Ah	; Z
db  5Bh	; [
db  5Ch	; \
db  5Dh	; ]
db  5Eh	; ^
db  5Fh	; _
db  60h	; `
db  41h	; A
db  42h	; B
db  43h	; C
db  44h	; D
db  45h	; E
db  46h	; F
db  47h	; G
db  48h	; H
db  49h	; I
db  4Ah	; J
db  4Bh	; K
db  4Ch	; L
db  4Dh	; M
db  4Eh	; N
db  4Fh	; O
db  50h	; P
db  51h	; Q
db  52h	; R
db  53h	; S
db  54h	; T
db  55h	; U
db  56h	; V
db  57h	; W
db  58h	; X
db  59h	; Y
db  5Ah	; Z
db  7Bh	; {
db  7Ch	; |
db  7Dh	; }
db  7Eh	; ~
db  7Fh	; 
db  80h	; Ä
db  81h	; Å
db  82h	; Ç
db  83h	; É
db  84h	; Ñ
db  85h	; Ö
db  86h	; Ü
db  87h	; á
db  88h	; à
db  89h	; â
db  8Ah	; ä
db  8Bh	; ã
db  8Ch	; å
db  8Dh	; ç
db  8Eh	; é
db  8Fh	; è
db  90h	; ê
db  91h	; ë
db  92h	; í
db  93h	; ì
db  94h	; î
db  95h	; ï
db  96h	; ñ
db  97h	; ó
db  98h	; ò
db  99h	; ô
db  9Ah	; ö
db  9Bh	; õ
db  9Ch	; ú
db  9Dh	; ù
db  9Eh	; û
db  9Fh	; ü
db 0A0h	; †
db 0A1h	; °
db 0A2h	; ¢
db 0A3h	; £
db 0A4h	; §
db 0A5h	; •
db 0A6h	; ¶
db 0A7h	; ß
db 0A8h	; ®
db 0A9h	; ©
db 0AAh	; ™
db 0ABh	; ´
db 0ACh	; ¨
db 0ADh	; ≠
db 0AEh	; Æ
db 0AFh	; Ø
db 0B0h	; ∞
db 0B1h	; ±
db 0B2h	; ≤
db 0B3h	; ≥
db 0B4h	; ¥
db 0B5h	; µ
db 0B6h	; ∂
db 0B7h	; ∑
db 0B8h	; ∏
db 0B9h	; π
db 0BAh	; ∫
db 0BBh	; ª
db 0BCh	; º
db 0BDh	; Ω
db 0BEh	; æ
db 0BFh	; ø
db 0C0h	; ¿
db 0C1h	; ¡
db 0C2h	; ¬
db 0C3h	; √
db 0C4h	; ƒ
db 0C5h	; ≈
db 0C6h	; ∆
db 0C7h	; «
db 0C8h	; »
db 0C9h	; …
db 0CAh	;  
db 0CBh	; À
db 0CCh	; Ã
db 0CDh	; Õ
db 0CEh	; Œ
db 0CFh	; œ
db 0D0h	; –
db 0D1h	; —
db 0D2h	; “
db 0D3h	; ”
db 0D4h	; ‘
db 0D5h	; ’
db 0D6h	; ÷
db 0D7h	; ◊
db 0D8h	; ÿ
db 0D9h	; Ÿ
db 0DAh	; ⁄
db 0DBh	; €
db 0DCh	; ‹
db 0DDh	; ›
db 0DEh	; ﬁ
db 0DFh	; ﬂ
db 0E0h	; ‡
db 0E1h	; ·
db 0E2h	; ‚
db 0E3h	; „
db 0E4h	; ‰
db 0E5h	; Â
db 0E6h	; Ê
db 0E7h	; Á
db 0E8h	; Ë
db 0E9h	; È
db 0EAh	; Í
db 0EBh	; Î
db 0ECh	; Ï
db 0EDh	; Ì
db 0EEh	; Ó
db 0EFh	; Ô
db 0F0h	; 
db 0F1h	; Ò
db 0F2h	; Ú
db 0F3h	; Û
db 0F4h	; Ù
db 0F5h	; ı
db 0F6h	; ˆ
db 0F7h	; ˜
db 0F8h	; ¯
db 0F9h	; ˘
db 0FAh	; ˙
db 0FBh	; ˚
db 0FCh	; ¸
db 0FDh	; ˝
db 0FEh	; ˛
db 0FFh
; struct _EXCEPTION_POINTERS ExceptionInfo
ExceptionInfo _EXCEPTION_POINTERS <offset dword_404180,\
		     offset dword_4041D8>
__load_config_used dd 48h ; Size
dd 0			; Time stamp
dw 2 dup(0)		; Version: 0.0
dd 0			; GlobalFlagsClear
dd 0			; GlobalFlagsSet
dd 0			; CriticalSectionDefaultTimeout
dd 0			; DeCommitFreeBlockThreshold
dd 0			; DeCommitTotalFreeThreshold
dd 0			; LockPrefixTable
dd 0			; MaximumAllocationSize
dd 0			; VirtualMemoryThreshold
dd 0			; ProcessAffinityMask
dd 0			; ProcessHeapFlags
dw 0			; CSDVersion
dw 0			; Reserved1
dd 0			; EditList
dd offset ___security_cookie ; SecurityCookie
dd offset ___safe_se_handler_table ; SEHandlerTable
dd 1			; SEHandlerCount
db  52h	; R
db  53h	; S
db  44h	; D
db  53h	; S
db  71h	; q
db  46h	; F
db 0A5h	; •
db 0BBh	; ª
db  46h	; F
db  3Dh	; =
db 0A7h	; ß
db  4Bh	; K
db 0A7h	; ß
db 0C4h	; ƒ
db  47h	; G
db  5Eh	; ^
db 0F0h	; 
db 0FDh	; ˝
db  4Bh	; K
db  83h	; É
db    2
db    0
db    0
db    0
db  65h	; e
db  3Ah	; :
db  5Ch	; \
db  62h	; b
db  75h	; u
db  69h	; i
db  6Ch	; l
db  64h	; d
db  73h	; s
db  5Ch	; \
db  6Dh	; m
db  6Fh	; o
db  7Ah	; z
db  32h	; 2
db  5Fh	; _
db  73h	; s
db  6Ch	; l
db  61h	; a
db  76h	; v
db  65h	; e
db  5Ch	; \
db  72h	; r
db  65h	; e
db  6Ch	; l
db  2Dh	; -
db  6Dh	; m
db  2Dh	; -
db  62h	; b
db  65h	; e
db  74h	; t
db  61h	; a
db  2Dh	; -
db  77h	; w
db  33h	; 3
db  32h	; 2
db  5Fh	; _
db  62h	; b
db  6Ch	; l
db  64h	; d
db  2Dh	; -
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  5Ch	; \
db  62h	; b
db  75h	; u
db  69h	; i
db  6Ch	; l
db  64h	; d
db  5Ch	; \
db  6Fh	; o
db  62h	; b
db  6Ah	; j
db  2Dh	; -
db  66h	; f
db  69h	; i
db  72h	; r
db  65h	; e
db  66h	; f
db  6Fh	; o
db  78h	; x
db  5Ch	; \
db  62h	; b
db  72h	; r
db  6Fh	; o
db  77h	; w
db  73h	; s
db  65h	; e
db  72h	; r
db  5Ch	; \
db  61h	; a
db  70h	; p
db  70h	; p
db  5Ch	; \
db  66h	; f
db  69h	; i
db  72h	; r
db  65h	; e
db  66h	; f
db  6Fh	; o
db  78h	; x
db  2Eh	; .
db  70h	; p
db  64h	; d
db  62h	; b
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
___safe_se_handler_table dd rva	__except_handler4
align 8
unk_403888 db	 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
unk_403890 db	 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
stru_403898 dd 0FFFFFFFEh	    ; GSCookieOffset ; SEH scope table for function 402235
dd 0			; GSCookieXOROffset
dd 0FFFFFFD0h		; EHCookieOffset
dd 0			; EHCookieXOROffset
dd 0FFFFFFFEh		; ScopeRecord.EnclosingLevel
dd offset $LN35		; ScopeRecord.FilterFunc
dd offset $LN22		; ScopeRecord.HandlerFunc
align 8
stru_4038B8 dd 0FFFFFFFEh	    ; GSCookieOffset ; SEH scope table for function 402594
dd 0			; GSCookieXOROffset
dd 0FFFFFFCCh		; EHCookieOffset
dd 0			; EHCookieXOROffset
dd 0FFFFFFFEh		; ScopeRecord.EnclosingLevel
dd 0			; ScopeRecord.FilterFunc
dd offset $LN8		; ScopeRecord.HandlerFunc
align 8
unk_4038D8 db 0FEh ; ˛
db 0FFh
db 0FFh
db 0FFh
db    0
db    0
db    0
db    0
db 0D8h	; ÿ
db 0FFh
db 0FFh
db 0FFh
db    0
db    0
db    0
db    0
db 0FEh	; ˛
db 0FFh
db 0FFh
db 0FFh
dd offset $LN13
dd offset $LN8_0
__IMPORT_DESCRIPTOR_KERNEL32 dd	rva off_403944 ; Import	Name Table
dd 0			; Time stamp
dd 0			; Forwarder Chain
dd rva aKernel32_dll	; DLL Name
dd rva SetEnvironmentVariableW ; Import	Address	Table
__IMPORT_DESCRIPTOR_USER32 dd rva off_403A7C ; Import Name Table
dd 0			; Time stamp
dd 0			; Forwarder Chain
dd rva aUser32_dll	; DLL Name
dd rva MessageBoxW	; Import Address Table
__IMPORT_DESCRIPTOR_MSVCR100 dd	rva off_4039D4 ; Import	Name Table
dd 0			; Time stamp
dd 0			; Forwarder Chain
dd rva aMsvcr100_dll	; DLL Name
dd rva __imp__amsg_exit	; Import Address Table
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
;
; Import names for KERNEL32.dll
;
off_403944 dd rva word_403A84
dd rva word_403A9E
dd rva word_403ABA
dd rva word_403AD4
dd rva word_403AEA
dd rva word_403B00
dd rva word_403B10
dd rva word_403B22
dd rva word_403B36
dd rva word_403B52
dd rva word_403B68
dd rva word_403B7E
dd rva word_403B96
dd rva word_403BAA
dd rva word_403F96
dd rva word_403F7A
dd rva word_403F4C
dd rva word_403F36
dd rva word_403F20
dd rva word_403F06
dd rva word_403EF6
dd rva word_403ED8
dd rva word_403EC8
dd rva word_403EB2
dd rva word_403E94
dd rva word_403E8C
dd rva word_403E76
dd rva word_403E68
dd rva word_403E5A
dd rva word_403E46
dd rva word_403E3A
dd rva word_403E2C
dd rva word_403E1A
dd rva word_403E0A
dd rva word_403F66
dd 0
;
; Import names for MSVCR100.dll
;
off_4039D4 dd rva word_403C9A
dd rva word_403CA8
dd rva word_403CBA
dd rva word_403CC4
dd rva word_403CDA
dd rva word_403CE2
dd rva word_403CF0
dd rva word_403CFC
dd rva word_403D0A
dd rva word_403D20
dd rva word_403D34
dd rva word_403D40
dd rva word_403D4A
dd rva word_403D6A
dd rva word_403D7A
dd rva word_403D8E
dd rva word_403D98
dd rva word_403DA6
dd rva word_403DAE
dd rva word_403DB8
dd rva word_403DD2
dd rva word_403DE4
dd rva word_403DF4
dd rva word_403C90
dd rva word_403C86
dd rva word_403C7C
dd rva word_403C74
dd rva word_403C6A
dd rva word_403C5A
dd rva word_403C50
dd rva word_403C46
dd rva word_403C36
dd rva word_403C2C
dd rva word_403C22
dd rva word_403C16
dd rva word_403C0A
dd rva word_403C00
dd rva word_403BF0
dd rva word_403BE6
dd rva word_403CCC
dd rva word_403FAA
dd 0
;
; Import names for USER32.dll
;
off_403A7C dd rva word_403BCC
dd 0
word_403A84 dw 4FAh
db 'SetEnvironmentVariableW',0
word_403A9E dw 171h
db 'ExpandEnvironmentStringsW',0
word_403ABA dw 242h
db 'GetEnvironmentVariableW',0
word_403AD4 dw 27Dh
db 'GetModuleFileNameW',0
align 2
word_403AEA dw 3ECh
db 'MultiByteToWideChar',0
word_403B00 dw 310h
db 'GetTickCount',0
align 10h
word_403B10 dw 2B5h
db 'GetProcAddress',0
align 2
word_403B22 dw 281h
db 'GetModuleHandleW',0
align 2
word_403B36 dw 43Dh
db 'QueryPerformanceFrequency',0
word_403B52 dw 24Eh
db 'GetFileAttributesW',0
align 4
word_403B68 dw 5DDh
db 'WideCharToMultiByte',0
word_403B7E dw 2BFh
db 'GetProcessIoCounters',0
align 2
word_403B96 dw 223h
db 'GetCurrentProcess',0
word_403BAA dw 4F4h
db 'SetDllDirectoryW',0
align 2
aKernel32_dll db 'KERNEL32.dll',0
align 4
word_403BCC dw 24Bh
db 'MessageBoxW',0
aUser32_dll db 'USER32.dll',0
align 2
word_403BE6 dw 608h
db 'strrchr',0
word_403BF0 dw 7Ah
db '??_V@YAXPAX@Z',0
word_403C00 dw 637h
db 'wcslen',0
align 2
word_403C0A dw 441h
db '_stricmp',0
align 2
word_403C16 dw 410h
db '_snprintf',0
word_403C22 dw 59Bh
db 'getenv',0
align 4
word_403C2C dw 5FAh
db 'strcpy',0
align 2
word_403C36 dw 63h
db '??2@YAPAXI@Z',0
align 2
word_403C46 dw 513h
db '_wfopen',0
word_403C50 dw 576h
db 'fclose',0
align 2
word_403C5A dw 65h
db '??3@YAXPAX@Z',0
align 2
word_403C6A dw 600h
db 'strlen',0
align 4
word_403C74 dw 57Ch
db 'fgets',0
word_403C7C dw 5F5h
db 'strcat',0
align 2
word_403C86 dw 5CFh
db 'memcpy',0
align 10h
word_403C90 dw 5D3h
db 'memset',0
align 2
word_403C9A dw 1C5h
db '_amsg_exit',0
align 4
word_403CA8 dw 1B6h
db '__wgetmainargs',0
align 2
word_403CBA dw 1DCh
db '_cexit',0
align 4
word_403CC4 dw 22Ah
db '_exit',0
word_403CCC dw 12Dh
db '_XcptFilter',0
word_403CDA dw 573h
db 'exit',0
align 2
word_403CE2 dw 1B7h
db '__winitenv',0
align 10h
word_403CF0 dw 2B0h
db '_initterm',0
word_403CFC dw 2B1h
db '_initterm_e',0
word_403D0A dw 1ECh
db '_configthreadlocale',0
word_403D20 dw 1A2h
db '__setusermatherr',0
align 4
word_403D34 dw 1EBh
db '_commode',0
align 10h
word_403D40 dw 245h
db '_fmode',0
align 2
word_403D4A dw 19Fh
db '__set_app_type',0
align 4
aMsvcr100_dll db 'MSVCR100.dll',0
align 2
word_403D6A dw 4B5h
db '_vsnprintf_s',0
align 2
word_403D7A dw 102h
db '?terminate@@YAXXZ',0
word_403D8E dw 48Dh
db '_unlock',0
word_403D98 dw 15Bh
db '__dllonexit',0
word_403DA6 dw 323h
db '_lock',0
word_403DAE dw 3C9h
db '_onexit',0
word_403DB8 dw 221h
db '_except_handler4_common',0
word_403DD2 dw 2B8h
db '_invoke_watson',0
align 4
word_403DE4 dw 1EFh
db '_controlfp_s',0
align 4
word_403DF4 dw 1FBh
db '_crt_debugger_hook',0
align 2
word_403E0A dw 26Ah
db 'GetLastError',0
align 2
word_403E1A dw 3C2h
db 'LoadLibraryExW',0
align 4
word_403E2C dw 1B8h
db 'FreeLibrary',0
word_403E3A dw 458h
db 'ReadFile',0
align 2
word_403E46 dw 509h
db 'SetFilePointerEx',0
align 2
word_403E5A dw 8Eh
db 'CloseHandle',0
word_403E68 dw 0D6h
db 'CreateFileW',0
word_403E76 dw 36Eh
db 'InterlockedExchange',0
word_403E8C dw 55Fh
db 'Sleep',0
word_403E94 dw 36Bh
db 'InterlockedCompareExchange',0
align 2
word_403EB2 dw 355h
db 'HeapSetInformation',0
align 4
word_403EC8 dw 13Ch
db 'EncodePointer',0
word_403ED8 dw 550h
db 'SetUnhandledExceptionFilter',0
word_403EF6 dw 117h
db 'DecodePointer',0
word_403F06 dw 43Ch
db 'QueryPerformanceCounter',0
word_403F20 dw 228h
db 'GetCurrentThreadId',0
align 2
word_403F36 dw 224h
db 'GetCurrentProcessId',0
word_403F4C dw 2F4h
db 'GetSystemTimeAsFileTime',0
word_403F66 dw 56Fh
db 'TerminateProcess',0
align 2
word_403F7A dw 590h
db 'UnhandledExceptionFilter',0
align 2
word_403F96 dw 383h
db 'IsDebuggerPresent',0
word_403FAA dw 3DBh
db '_putenv',0
align 80h
_rdata ends

; Section 3. (virtual address 00004000)
; Virtual size			: 000004BC (   1212.)
; Section size in file		: 00000200 (	512.)
; Offset to raw	data for section: 00003000
; Flags	C0000040: Data Readable	Writable
; Alignment	: default

; Segment type:	Pure data
; Segment permissions: Read/Write
_data segment para public 'DATA' use32
assume cs:_data
;org 404000h
dd offset aTestconsoleid ; "testconsoleid="
___security_cookie dd 0BB40E64Eh
dword_404008 dd	44BF19B1h
align 10h
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
dword_404020 dd	0FFFFFFFEh
dword_404024 dd	1
unk_404028 db	 0
db    0
db    0
db    0
dword_40402C dd	0
dword_404030 dd	0
dword_404034 dd	0
dword_404038 dd	0
dword_40403C dd	0
dword_404040 dd	0
dword_404044 dd	0
dword_404048 dd	0
dword_40404C dd	0
dword_404050 dd	0
align 8
dword_404058 dd	0
dword_40405C dd	0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
dword_404078 dd	0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
dword_404090 dd	0
dword_404094 dd	0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
dword_4040AC dd	0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
dword_4040C0 dd	0
align 10h
dword_4040D0 dd	0
align 8
dword_4040D8 dd	0
dword_4040DC dd	0
dword_4040E0 dd	0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
dword_4040F4 dd	0
dword_4040F8 dd	0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
; void *dword_404144
dword_404144 dd	0
byte_404148 db 0
align 4
dword_40414C dd	0
dword_404150 dd	0
dword_404154 dd	0
dword_404158 dd	0
dword_40415C dd	0
dword_404160 dd	0
dword_404164 dd	0
dword_404168 dd	0
dword_40416C dd	0
dword_404170 dd	0
dword_404174 dd	0
dword_404178 dd	0
align 10h
dword_404180 dd	0
dword_404184 dd	0
db    0
db    0
db    0
db    0
dword_40418C dd	0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
dword_4041D0 dd	0
align 8
dword_4041D8 dd	0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
word_404264 dw ?
align 4
word_404268 dw ?
align 4
word_40426C dw ?
align 10h
word_404270 dw ?
align 4
dword_404274 dd	?
dword_404278 dd	?
dword_40427C dd	?
dword_404280 dd	?
dword_404284 dd	?
dword_404288 dd	?
dword_40428C dd	?
dword_404290 dd	?
word_404294 dw ?
align 4
dword_404298 dd	?
dword_40429C dd	?
word_4042A0 dw ?
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
dword_4044A4 dd	?
; volatile LONG	Destination
Destination dd ?
; PVOID	dword_4044AC
dword_4044AC dd	?
; PVOID	Ptr
Ptr dd ?
dword_4044B4 dd	?
dword_4044B8 dd	?
align 1000h
_data ends


end start
