
_EXCEPTION_POINTERS struc ; (sizeof=0x8, standard type)
ExceptionRecord	dd ?	; offset
ContextRecord dd ?	; offset
_EXCEPTION_POINTERS ends


_FILETIME struc	; (sizeof=0x8, standard	type)
dwLowDateTime dd ?
dwHighDateTime dd ?
_FILETIME ends


IO_COUNTERS struc ; (sizeof=0x30, standard type)
ReadOperationCount dq ?
WriteOperationCount dq ?
OtherOperationCount dq ?
ReadTransferCount dq ?
WriteTransferCount dq ?
OtherTransferCount dq ?
IO_COUNTERS ends


_LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E struc	; (sizeof=0x8, standard	type)
LowPart	dd ?
HighPart dd ?
_LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E ends


LARGE_INTEGER union ; (sizeof=0x8, standard type)
anonymous_0 _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E ?
u _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E ?
QuadPart dq ?
LARGE_INTEGER ends


_EH4_SCOPETABLE_RECORD struc ; (sizeof=0xC, standard type)
EnclosingLevel dd ?
FilterFunc dd ?		; offset
HandlerFunc dd ?	; offset
_EH4_SCOPETABLE_RECORD ends


CPPEH_RECORD struc ; (sizeof=0x18, standard type)
old_esp	dd ?
exc_ptr	dd ?		; offset
prev_er	dd ?		; offset
handler	dd ?		; offset
msEH_ptr dd ?		; offset
disabled dd ?
CPPEH_RECORD ends


_EH4_SCOPETABLE	struc ;	(sizeof=0x10, variable size)
GSCookieOffset dd ?
GSCookieXOROffset dd ?
EHCookieOffset dd ?
EHCookieXOROffset dd ?
ScopeRecord _EH4_SCOPETABLE_RECORD 0 dup(?)
_EH4_SCOPETABLE	ends


;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2010 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-B231-7414-99			    |
; |		       NCFTA Canada/Concordia University		    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	A6FE3BD4E3FC9C5583C92DF311A9C258
; Input	CRC32 :	D6026CAF

; File Name   :	C:\Program Files (x86)\Mozilla Firefox\firefox.exe
; Format      :	Portable executable for	80386 (PE)
; Imagebase   :	400000
; Section 1. (virtual address 00001000)
; Virtual size			: 00002015 (   8213.)
; Section size in file		: 00002200 (   8704.)
; Offset to raw	data for section: 00000400
; Flags	60000020: Text Executable Readable
; Alignment	: default
; OS type	  :  MS	Windows
; Application type:  Executable	32bit

include	uni.inc	; see unicode subdir of	ida for	info on	unicode

.686p
.mmx
.model flat


; Segment type:	Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use32
assume cs:_text
;org 401000h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



sub_401000 proc	near

var_270= dword ptr -270h
var_26C= dword ptr -26Ch
var_268= dword ptr -268h
Dst= dword ptr -264h
var_260= dword ptr -260h
var_25C= dword ptr -25Ch
var_258= dword ptr -258h
var_254= dword ptr -254h
var_250= dword ptr -250h
var_24C= dword ptr -24Ch
var_248= dword ptr -248h
var_244= dword ptr -244h
var_240= dword ptr -240h
var_23C= dword ptr -23Ch
var_238= dword ptr -238h
var_234= dword ptr -234h
var_230= dword ptr -230h
var_22C= dword ptr -22Ch
var_228= dword ptr -228h
var_224= dword ptr -224h
var_220= dword ptr -220h
var_21C= byte ptr -21Ch
var_210= dword ptr -210h
Dest= word ptr -20Ch
var_4= dword ptr -4
arg_0= dword ptr  4
arg_4= dword ptr  8

; FUNCTION CHUNK AT 004027B4 SIZE 0000031C BYTES

sub	esp, 270h
mov	eax, ___security_cookie
xor	eax, esp
mov	[esp+270h+var_4], eax
push	ebx
push	ebp
mov	ebp, [esp+278h+arg_4]
push	esi
push	edi
mov	ebx, ecx
xor	edi, edi
push	offset VarName	; "XUL_APP_FILE"
mov	[esp+284h+var_220], ebx
mov	[esp+284h+var_210], ebp
mov	[esp+284h+var_270], edi
call	ds:getenv
add	esp, 4
cmp	eax, edi
jnz	loc_4027B4

loc_401045:
cmp	[esp+280h+arg_0], 1
jle	short loc_40107D
mov	eax, [ebx+4]
mov	cl, [eax]
cmp	cl, 2Dh
jnz	loc_402804
inc	eax
cmp	[eax], cl
jz	loc_4027FE

loc_401066:		; "app"
push	offset Str2
push	eax		; Str1
call	ds:_stricmp
add	esp, 8
test	eax, eax
jz	loc_402825

loc_40107D:
mov	eax, [esp+280h+var_270]
cmp	eax, edi
jnz	loc_402963
push	3Ch		; Size
lea	edx, [esp+284h+Dst]
push	edi		; Val
push	edx		; Dst
call	ds:memset
mov	eax, dword_405418
mov	ebp, ds:Str
add	esp, 0Ch
mov	[esp+280h+Dst],	3Ch
cmp	eax, edi
jz	short loc_4010C0
mov	ecx, [esp+280h+var_25C]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_4010C0:
mov	ebx, ds:strlen
cmp	ebp, edi
jz	loc_4029BE
push	ebp		; Str
call	ebx ; strlen
mov	edi, eax
mov	eax, dword_405410
add	esp, 4
test	eax, eax
jz	loc_4029B7
lea	edx, [edi+1]
push	edx
call	eax ; dword_405410
mov	esi, eax
add	esp, 4
test	esi, esi
jz	short loc_401102
push	edi		; Size
push	ebp		; Src
push	esi		; Dst
call	ds:memcpy
add	esp, 0Ch
mov	byte ptr [esi+edi], 0

loc_401102:
mov	eax, dword_405418
mov	[esp+280h+var_25C], esi

loc_40110B:
mov	ebp, ds:off_404504
test	eax, eax
jz	short loc_401124
mov	ecx, [esp+280h+var_258]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_401124:
test	ebp, ebp
jz	loc_4029CE
push	ebp		; Str
call	ebx ; strlen
mov	edi, eax
mov	eax, dword_405410
add	esp, 4
test	eax, eax
jz	loc_4029C7
lea	edx, [edi+1]
push	edx
call	eax ; dword_405410
mov	esi, eax
add	esp, 4
test	esi, esi
jz	short loc_401160
push	edi		; Size
push	ebp		; Src
push	esi		; Dst
call	ds:memcpy
add	esp, 0Ch
mov	byte ptr [esi+edi], 0

loc_401160:
mov	eax, dword_405418
mov	[esp+280h+var_258], esi

loc_401169:
mov	ebp, ds:off_404508
test	eax, eax
jz	short loc_401182
mov	ecx, [esp+280h+var_254]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_401182:
test	ebp, ebp
jz	loc_4029E2
push	ebp		; Str
call	ebx ; strlen
mov	edi, eax
mov	eax, dword_405410
add	esp, 4
test	eax, eax
jz	loc_4029DB
lea	edx, [edi+1]
push	edx
call	eax ; dword_405410
mov	esi, eax
add	esp, 4
test	esi, esi
jz	short loc_4011BE
push	edi		; Size
push	ebp		; Src
push	esi		; Dst
call	ds:memcpy
add	esp, 0Ch
mov	byte ptr [esi+edi], 0

loc_4011BE:
mov	eax, dword_405418
mov	[esp+280h+var_254], esi

loc_4011C7:
mov	ebp, ds:off_40450C
test	eax, eax
jz	short loc_4011E0
mov	ecx, [esp+280h+var_250]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_4011E0:
test	ebp, ebp
jz	loc_4029F6
push	ebp		; Str
call	ebx ; strlen
mov	edi, eax
mov	eax, dword_405410
add	esp, 4
test	eax, eax
jz	loc_4029EF
lea	edx, [edi+1]
push	edx
call	eax ; dword_405410
mov	esi, eax
add	esp, 4
test	esi, esi
jz	short loc_40121C
push	edi		; Size
push	ebp		; Src
push	esi		; Dst
call	ds:memcpy
add	esp, 0Ch
mov	byte ptr [esi+edi], 0

loc_40121C:
mov	eax, dword_405418
mov	[esp+280h+var_250], esi

loc_401225:
mov	ebp, ds:off_404510
xor	esi, esi
cmp	eax, esi
jz	short loc_401240
mov	ecx, [esp+280h+var_24C]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_401240:
cmp	ebp, esi
jz	loc_402A03
push	ebp		; Str
call	ebx ; strlen
mov	edi, eax
mov	eax, dword_405410
add	esp, 4
cmp	eax, esi
jz	short loc_401278
lea	edx, [edi+1]
push	edx
call	eax ; dword_405410
mov	esi, eax
add	esp, 4
test	esi, esi
jz	short loc_401278
push	edi		; Size
push	ebp		; Src
push	esi		; Dst
call	ds:memcpy
add	esp, 0Ch
mov	byte ptr [esi+edi], 0

loc_401278:
mov	eax, dword_405418
mov	[esp+280h+var_24C], esi
xor	esi, esi

loc_401283:
cmp	eax, esi
jz	short loc_401296
mov	ecx, [esp+280h+var_248]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_401296:
mov	[esp+280h+var_248], esi
cmp	eax, esi
jz	short loc_4012AD
mov	edx, [esp+280h+var_230]
push	edx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_4012AD:
mov	ecx, [esp+280h+var_260]
mov	[esp+280h+var_230], esi
cmp	ecx, esi
jnz	loc_402A0C

loc_4012BD:
mov	ecx, [esp+280h+var_240]
mov	[esp+280h+var_260], esi
mov	[esp+280h+var_244], 0Eh
cmp	ecx, esi
jnz	loc_402A1E

loc_4012D5:
mov	ebp, ds:off_404520
mov	[esp+280h+var_240], esi
test	eax, eax
jz	short loc_4012F2
mov	ecx, [esp+280h+var_23C]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_4012F2:
test	ebp, ebp
jz	loc_402A37
push	ebp		; Str
call	ebx ; strlen
mov	edi, eax
mov	eax, dword_405410
add	esp, 4
test	eax, eax
jz	loc_402A30
lea	edx, [edi+1]
push	edx
call	eax ; dword_405410
mov	esi, eax
add	esp, 4
test	esi, esi
jz	short loc_40132E
push	edi		; Size
push	ebp		; Src
push	esi		; Dst
call	ds:memcpy
add	esp, 0Ch
mov	byte ptr [esi+edi], 0

loc_40132E:
mov	eax, dword_405418
mov	[esp+280h+var_23C], esi

loc_401337:
mov	ebp, ds:off_404524
test	eax, eax
jz	short loc_401350
mov	ecx, [esp+280h+var_238]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_401350:
test	ebp, ebp
jz	loc_402A4B
push	ebp		; Str
call	ebx ; strlen
mov	edi, eax
mov	eax, dword_405410
add	esp, 4
test	eax, eax
jz	loc_402A44
lea	edx, [edi+1]
push	edx
call	eax ; dword_405410
mov	esi, eax
add	esp, 4
test	esi, esi
jz	short loc_40138C
push	edi		; Size
push	ebp		; Src
push	esi		; Dst
call	ds:memcpy
add	esp, 0Ch
mov	byte ptr [esi+edi], 0

loc_40138C:
mov	eax, dword_405418
mov	[esp+280h+var_238], esi

loc_401395:
mov	ebp, ds:off_404528
xor	esi, esi
cmp	eax, esi
jz	short loc_4013B0
mov	ecx, [esp+280h+var_234]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_4013B0:
cmp	ebp, esi
jz	loc_402A58
push	ebp		; Str
call	ebx ; strlen
mov	edi, eax
mov	eax, dword_405410
add	esp, 4
cmp	eax, esi
jz	short loc_4013E8
lea	edx, [edi+1]
push	edx
call	eax ; dword_405410
mov	esi, eax
add	esp, 4
test	esi, esi
jz	short loc_4013E8
push	edi		; Size
push	ebp		; Src
push	esi		; Dst
call	ds:memcpy
add	esp, 0Ch
mov	byte ptr [esi+edi], 0

loc_4013E8:
mov	eax, dword_405418
mov	[esp+280h+var_234], esi
xor	esi, esi

loc_4013F3:
mov	edi, ds:dword_404530
cmp	eax, esi
jz	short loc_401407
mov	ecx, [esp+280h+var_22C]
push	ecx
call	eax ; dword_405418
add	esp, 4

loc_401407:
cmp	edi, esi
jnz	loc_402A61
mov	[esp+280h+var_22C], esi

loc_401413:		; nSize
push	104h
lea	edx, [esp+284h+Dest]
push	edx		; lpFilename
xor	ebx, ebx
push	esi		; hModule
mov	[esp+28Ch+var_224], ebx
mov	[esp+28Ch+var_268], esi
call	ds:GetModuleFileNameW
test	eax, eax
jz	loc_402A73
xor	edi, edi

loc_401438:
test	edi, edi
js	loc_402A7D
mov	eax, [esp+280h+var_268]
mov	[esp+280h+var_268], esi
cmp	eax, esi
jnz	loc_402A8C

loc_401450:
mov	eax, dword_40541C
cmp	eax, esi
jz	short loc_40146C
push	2
push	0FFFFFFFFh
lea	ecx, [esp+288h+Dest]
push	ecx
lea	edx, [esp+28Ch+var_21C]
push	edx
call	eax ; dword_40541C
add	esp, 10h

loc_40146C:
mov	eax, dword_4053B8
cmp	eax, esi
jz	loc_402A99
lea	ecx, [esp+280h+var_268]
push	ecx
lea	edx, [esp+284h+var_21C]
push	1
push	edx
call	eax ; dword_4053B8
add	esp, 0Ch
mov	edi, eax

loc_40148C:
mov	eax, dword_4053D4
cmp	eax, esi
jz	short loc_40149F
lea	ecx, [esp+280h+var_21C]
push	ecx
call	eax ; dword_4053D4
add	esp, 4

loc_40149F:
test	edi, edi
js	loc_402AA3
mov	ebx, [esp+280h+var_268]
mov	eax, [ebx]
mov	ecx, [eax+4]
push	ebx
mov	[esp+284h+var_224], ebx
call	ecx
mov	eax, [esp+280h+var_268]
cmp	eax, esi
jz	short loc_4014C7
mov	edx, [eax]
push	eax
mov	eax, [edx+8]
call	eax

loc_4014C7:
xor	edi, edi

loc_4014C9:
test	edi, edi
js	loc_402879
lea	edx, [esp+280h+var_228]
mov	[esp+280h+var_228], esi
mov	ecx, [ebx]
mov	eax, [ecx+0B8h]
push	edx
push	ebx
call	eax
mov	eax, [esp+280h+var_228]
lea	edx, [esp+280h+var_26C]
mov	[esp+280h+var_26C], esi
mov	ecx, [eax]
push	edx
push	eax
mov	eax, [ecx+0ACh]
call	eax
mov	eax, dword_40541C
mov	edi, [esp+280h+var_26C]
cmp	eax, esi
jz	short loc_40151D
push	2
push	7
lea	ecx, [esp+288h+var_21C]
push	offset aBrowser	; "browser"
push	ecx
call	eax ; dword_40541C
add	esp, 10h

loc_40151D:
mov	edx, [edi]
mov	ecx, [edx+0Ch]
lea	eax, [esp+280h+var_21C]
push	eax
push	edi
call	ecx
mov	eax, dword_4053D4
cmp	eax, esi
jz	short loc_40153D
lea	edx, [esp+280h+var_21C]
push	edx
call	eax ; dword_4053D4
add	esp, 4

loc_40153D:
mov	eax, [esp+280h+var_260]
mov	edi, [esp+280h+var_26C]
cmp	eax, esi
jnz	loc_402AB2

loc_40154D:
mov	[esp+280h+var_260], edi
cmp	edi, esi
jz	short loc_40155D
mov	eax, [edi]
mov	ecx, [eax+4]
push	edi
call	ecx

loc_40155D:
mov	edx, [esp+280h+var_210]
mov	ecx, [esp+280h+var_220]
push	esi
lea	eax, [esp+284h+Dst]
push	eax
mov	[esp+288h+var_240], edx
mov	edx, [esp+288h+arg_0]
push	ecx
push	edx
call	dword_405390
mov	edi, eax
mov	eax, [esp+290h+var_26C]
add	esp, 10h
cmp	eax, esi
jz	short loc_401593
mov	ecx, [eax]
mov	edx, [ecx+8]
push	eax
call	edx

loc_401593:
mov	eax, [esp+280h+var_228]
cmp	eax, esi
jz	short loc_4015A3
mov	ecx, [eax]
mov	edx, [ecx+8]
push	eax
call	edx

loc_4015A3:
mov	eax, [ebx]
mov	ecx, [eax+8]
push	ebx
call	ecx
mov	eax, dword_405418
cmp	eax, esi
jz	short loc_4015C3
mov	edx, [esp+280h+var_25C]
push	edx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_4015C3:
mov	[esp+280h+var_25C], esi
cmp	eax, esi
jz	short loc_4015DA
mov	ecx, [esp+280h+var_258]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_4015DA:
mov	[esp+280h+var_258], esi
cmp	eax, esi
jz	short loc_4015F1
mov	edx, [esp+280h+var_254]
push	edx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_4015F1:
mov	[esp+280h+var_254], esi
cmp	eax, esi
jz	short loc_401608
mov	ecx, [esp+280h+var_250]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_401608:
mov	[esp+280h+var_250], esi
cmp	eax, esi
jz	short loc_40161F
mov	edx, [esp+280h+var_24C]
push	edx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_40161F:
mov	[esp+280h+var_24C], esi
cmp	eax, esi
jz	short loc_401636
mov	ecx, [esp+280h+var_248]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_401636:
mov	[esp+280h+var_248], esi
cmp	eax, esi
jz	short loc_40164D
mov	edx, [esp+280h+var_230]
push	edx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_40164D:
mov	ecx, [esp+280h+var_260]
mov	[esp+280h+var_230], esi
cmp	ecx, esi
jz	short loc_40166A
mov	eax, [ecx]
push	ecx
mov	ecx, [eax+8]
call	ecx
mov	eax, dword_405418
mov	[esp+280h+var_260], esi

loc_40166A:
mov	ecx, [esp+280h+var_240]
cmp	ecx, esi
jz	short loc_40167F
mov	edx, [ecx]
mov	eax, [edx+8]
push	ecx
call	eax
mov	eax, dword_405418

loc_40167F:
mov	[esp+280h+var_240], esi
cmp	eax, esi
jz	short loc_401696
mov	ecx, [esp+280h+var_23C]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_401696:
mov	[esp+280h+var_23C], esi
cmp	eax, esi
jz	short loc_4016AD
mov	edx, [esp+280h+var_238]
push	edx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_4016AD:
mov	[esp+280h+var_238], esi
cmp	eax, esi
jz	short loc_4016C4
mov	ecx, [esp+280h+var_234]
push	ecx
call	eax ; dword_405418
mov	eax, dword_405418
add	esp, 4

loc_4016C4:
mov	[esp+280h+var_234], esi
cmp	eax, esi
jz	short loc_4016D6
mov	edx, [esp+280h+var_22C]
push	edx
call	eax ; dword_405418
add	esp, 4

loc_4016D6:
mov	eax, [esp+280h+var_270]
cmp	eax, esi
jnz	loc_402ABF

loc_4016E2:
mov	eax, edi

loc_4016E4:
mov	ecx, [esp+280h+var_4]
pop	edi
pop	esi
pop	ebp
pop	ebx
xor	ecx, esp
call	@__security_check_cookie@4 ; __security_check_cookie(x)
add	esp, 270h
retn
sub_401000 endp

align 10h



_wmain proc near

File= dword ptr	-108C4h
var_108C0= byte	ptr -108C0h
var_108BC= dword ptr -108BCh
var_108B8= dword ptr -108B8h
Dest= dword ptr	-108B4h
var_108B0= dword ptr -108B0h
NumberOfBytesRead= dword ptr -108ACh
Frequency= LARGE_INTEGER ptr -108A8h
NewFilePointer=	LARGE_INTEGER ptr -108A0h
var_10894= dword ptr -10894h
var_10890= dword ptr -10890h
var_1088C= dword ptr -1088Ch
var_10888= byte	ptr -10888h
IoCounters= IO_COUNTERS	ptr -1087Ch
var_1084C= dword ptr -1084Ch
var_10834= dword ptr -10834h
var_10830= dword ptr -10830h
MultiByteStr= byte ptr -1081Ch
Dst= byte ptr -10718h
var_10717= byte	ptr -10717h
var_10615= byte	ptr -10615h
ProcName= byte ptr -10614h
WideCharStr= word ptr -10414h
Filename= word ptr -1020Ch
Buffer=	byte ptr -10004h
var_4= dword ptr -4
arg_0= dword ptr  4
arg_4= dword ptr  8

; FUNCTION CHUNK AT 00402AD0 SIZE 00000258 BYTES

mov	eax, 108C4h
call	__alloca_probe
mov	eax, ___security_cookie
xor	eax, esp
mov	[esp+108C4h+var_4], eax
mov	eax, [esp+108C4h+arg_4]
push	ebx
mov	ebx, [esp+108C8h+arg_0]
push	ebp
mov	ebp, ds:GetEnvironmentVariableW
push	esi
push	edi
push	0		; nSize
push	0		; lpBuffer
push	offset Name	; "PATH"
mov	[esp+108E0h+var_108B8],	ebx
mov	[esp+108E0h+var_108BC],	eax
call	ebp ; GetEnvironmentVariableW
test	eax, eax
jz	loc_4017D1
xor	ecx, ecx
mov	esi, eax
mov	edx, 2
mul	edx
seto	cl
neg	ecx
or	ecx, eax
push	ecx
call	sub_4021F0
add	esp, 4
push	esi		; nSize
mov	edi, eax
push	edi		; lpBuffer
push	offset Name	; "PATH"
call	ebp ; GetEnvironmentVariableW
dec	esi
cmp	esi, eax
jnz	short loc_4017C7
mov	ebp, ds:ExpandEnvironmentStringsW
push	0		; nSize
push	0		; lpDst
push	edi		; lpSrc
call	ebp ; ExpandEnvironmentStringsW
test	eax, eax
jz	short loc_4017C7
xor	ecx, ecx
mov	esi, eax
mov	edx, 2
mul	edx
seto	cl
neg	ecx
or	ecx, eax
push	ecx
call	sub_4021F0
add	esp, 4
push	esi		; nSize
mov	ebx, eax
push	ebx		; lpDst
push	edi		; lpSrc
call	ebp ; ExpandEnvironmentStringsW
test	eax, eax
jz	short loc_4017B9
push	ebx		; lpValue
push	offset Name	; "PATH"
call	ds:SetEnvironmentVariableW

loc_4017B9:
push	ebx
call	ds:??_V@YAXPAX@Z ; operator delete[](void *)
mov	ebx, [esp+108D8h+var_108B8]
add	esp, 4

loc_4017C7:
push	edi
call	ds:??_V@YAXPAX@Z ; operator delete[](void *)
add	esp, 4

loc_4017D1:
push	offset unk_40458C
call	ds:SetDllDirectoryW
xor	ecx, ecx
lea	edi, [ebx+1]
mov	eax, edi
mov	edx, 4
mul	edx
seto	cl
neg	ecx
or	ecx, eax
push	ecx
call	sub_4021F0
add	esp, 4
test	eax, eax
jz	loc_402BE0
mov	esi, eax
mov	[esp+108D4h+var_108B0],	esi
test	ebx, ebx
jle	loc_4018C2
mov	eax, [esp+108D4h+var_108BC]
sub	eax, esi
mov	[esp+108D4h+NumberOfBytesRead],	edi
mov	[esp+108D4h+File], 0
mov	[esp+108D4h+Dest], esi
mov	[esp+108D4h+var_108BC],	eax
lea	ebx, [ebx+0]

loc_401830:
mov	eax, [esp+108D4h+var_108BC]
mov	ebx, [eax+esi]
push	ebx		; Str
call	ds:wcslen
mov	edi, eax
lea	ecx, [edi+edi*2+1]
push	ecx
call	sub_4021F0
add	esp, 8
test	eax, eax
jz	loc_402AD0
lea	edi, [ebx+edi*2]
mov	ebp, eax
mov	esi, ebp
cmp	ebx, edi
jnb	short loc_401889
mov	edx, ebx
jmp	short loc_401870
db 8Dh,	0A4h, 24h, 4 dup(0)
jmp	short loc_401870
align 10h

loc_401870:
movzx	ecx, word ptr [edx]
test	ecx, 0FF80h
jnz	loc_402AD7
mov	[esi], cl
inc	esi

loc_401882:
add	edx, 2
cmp	edx, edi
jb	short loc_401870

loc_401889:
mov	byte ptr [esi],	0
mov	esi, [esp+108D4h+Dest]
mov	eax, ebp

loc_401892:
mov	[esi], eax
test	eax, eax
jz	loc_402BE0
mov	eax, [esp+108D4h+File]
inc	eax
add	esi, 4
mov	[esp+108D4h+File], eax
mov	[esp+108D4h+Dest], esi
cmp	eax, [esp+108D4h+var_108B8]
jl	loc_401830
mov	esi, [esp+108D4h+var_108B0]
mov	edi, [esp+108D4h+NumberOfBytesRead]
mov	ebx, [esp+108D4h+var_108B8]

loc_4018C2:
xor	ecx, ecx
mov	eax, edi
mov	edx, 4
mul	edx
seto	cl
mov	dword ptr [esi+ebx*4], 0
neg	ecx
or	ecx, eax
push	ecx
call	sub_4021F0
add	esp, 4
test	eax, eax
jz	loc_402BD6
mov	[esp+108D4h+var_108BC],	eax
test	ebx, ebx
jle	short loc_40190B
mov	ecx, esi
sub	ecx, eax
mov	edx, ebx
lea	ebx, [ebx+0]

loc_401900:
mov	esi, [ecx+eax]
mov	[eax], esi
add	eax, 4
dec	edx
jnz	short loc_401900

loc_40190B:
lea	eax, [esp+108D4h+Frequency]
push	eax		; lpFrequency
call	ds:QueryPerformanceFrequency
push	offset ModuleName ; "kernel32.dll"
call	ds:GetModuleHandleW
mov	ebx, ds:GetProcAddress
push	offset ProcName	; "GetTickCount64"
push	eax		; hModule
call	ebx ; GetProcAddress
mov	dword_40548C, eax
test	eax, eax
jz	loc_402BFB

loc_40193C:
call	eax
mov	ecx, dword ptr [esp+108D4h+Frequency+4]
push	ecx
mov	ecx, dword ptr [esp+108D8h+Frequency]
push	ecx
push	edx
push	eax
call	__allmul
mov	dword ptr [esp+108D4h+Frequency+4], edx
lea	edx, [esp+108D4h+IoCounters]
push	edx		; lpIoCounters
mov	dword ptr [esp+108D8h+Frequency], eax
call	ds:GetCurrentProcess
push	eax		; hProcess
call	ds:GetProcessIoCounters
mov	[esp+108D4h+var_1088C],	eax
push	104h		; nSize
lea	eax, [esp+108D8h+WideCharStr]
push	eax		; lpFilename
push	0		; hModule
call	ds:GetModuleFileNameW
test	eax, eax
jz	loc_402C0A
xor	esi, esi

loc_40198C:
test	esi, esi
js	loc_402C14
push	0		; lpUsedDefaultChar
push	0		; lpDefaultChar
push	104h		; cbMultiByte
lea	ecx, [esp+108E0h+MultiByteStr]
push	ecx		; lpMultiByteStr
push	0FFFFFFFFh	; cchWideChar
lea	edx, [esp+108E8h+WideCharStr]
push	edx		; lpWideCharStr
push	0		; dwFlags
push	0FDE9h		; CodePage
call	ds:WideCharToMultiByte
xor	esi, esi
test	esi, esi
js	loc_402C14
lea	eax, [esp+108D4h+MultiByteStr]
push	5Ch		; Ch
push	eax		; Str
call	ds:strrchr
add	esp, 8
test	eax, eax
jz	loc_402C33
mov	ecx, eax
lea	edx, [esp+108D4h+MultiByteStr]
sub	ecx, edx
cmp	ecx, 0FBh
ja	loc_402C33
mov	[esp+108D4h+var_10894],	eax
inc	eax
push	offset Source	; "xul.dll"
push	eax		; Dest
call	ds:strcpy
mov	ebp, ds:MultiByteToWideChar
add	esp, 8
push	104h		; cchWideChar
lea	eax, [esp+108D8h+WideCharStr]
push	eax		; lpWideCharStr
push	0FFFFFFFFh	; cbMultiByte
lea	ecx, [esp+108E0h+MultiByteStr]
push	ecx		; lpMultiByteStr
push	esi		; dwFlags
push	0FDE9h		; CodePage
call	ebp ; MultiByteToWideChar
lea	edx, [esp+108D4h+WideCharStr]
push	edx		; lpFileName
call	ds:GetFileAttributesW
cmp	eax, 0FFFFFFFFh
jz	loc_402C26
mov	dl, [esp+108D4h+MultiByteStr]
mov	byte_405490, 1
mov	dword_405398, 1
mov	dword_40539C, 0E8h
test	dl, dl
jz	loc_402C3D
lea	esi, [esp+108D4h+MultiByteStr]
xor	edi, edi
jmp	short loc_401A80
align 10h

loc_401A80:		; "/\\"
mov	ecx, offset asc_404740
mov	al, 2Fh

loc_401A87:
cmp	al, dl
jz	loc_401F42

loc_401A8F:
mov	al, [ecx+1]
inc	ecx
test	al, al
jnz	short loc_401A87
mov	dl, [esi+1]
inc	esi
test	dl, dl
jnz	short loc_401A80
test	edi, edi
jz	loc_402C3D
lea	eax, [esp+108D4h+MultiByteStr]
sub	edi, eax
mov	esi, edi
cmp	esi, 0F0h
ja	loc_402C69
push	esi		; Size
push	eax		; Src
lea	edx, [esp+108DCh+Dst]
push	edx		; Dst
call	ds:memcpy
lea	eax, [esp+esi+108E0h+Dst]
push	offset aDependentlibs_ ; "\\dependentlibs.list"
push	eax		; Dest
call	ds:strcpy
add	esp, 14h
lea	esi, [esp+esi+108D4h+var_10717]

loc_401AEB:		; cchWideChar
push	104h
lea	edx, [esp+108D8h+Filename]
push	edx		; lpWideCharStr
push	0FFFFFFFFh	; cbMultiByte
lea	eax, [esp+108E0h+Dst]
push	eax		; lpMultiByteStr
push	0		; dwFlags
push	0FDE9h		; CodePage
mov	[esp+108ECh+Dest], esi
call	ebp ; MultiByteToWideChar
lea	ecx, [esp+108D4h+Filename]
push	offset Mode	; "rt"
push	ecx		; Filename
call	ds:_wfopen
add	esp, 8
test	eax, eax
jz	loc_402C5F
push	eax		; File
lea	edx, [esp+108D8h+ProcName]
push	104h		; MaxCount
push	edx		; Buf
mov	[esp+108E0h+File], eax
mov	byte ptr [esi],	0
call	ds:fgets
add	esp, 0Ch
test	eax, eax
jz	loc_401CDE
mov	ebp, ds:ReadFile
mov	ebx, 10000h
mov	edi, edi

loc_401B60:
lea	eax, [esp+108D4h+ProcName]
push	eax		; Str
call	ds:strlen
add	esp, 4
test	eax, eax
jz	loc_401CBB
cmp	[esp+108D4h+ProcName], 23h
jz	loc_401CBB
cmp	[esp+eax+108D4h+var_10615], 0Ah
jnz	short loc_401B99
mov	[esp+eax+108D4h+var_10615], 0

loc_401B99:
lea	ecx, [esp+108D4h+Dst]
sub	eax, ecx
mov	ecx, [esp+108D4h+Dest]
add	eax, ecx
cmp	eax, 104h
ja	loc_402C9B
lea	edx, [esp+108D4h+ProcName]
push	edx		; Source
push	ecx		; Dest
call	ds:strcpy
mov	al, byte_405490
add	esp, 8
push	104h		; cchWideChar
lea	ecx, [esp+108D8h+WideCharStr]
push	ecx		; lpWideCharStr
push	0FFFFFFFFh	; cbMultiByte
lea	edx, [esp+108E0h+Dst]
push	edx		; lpMultiByteStr
push	0		; dwFlags
push	0FDE9h		; CodePage
mov	[esp+108ECh+var_108C0],	al
call	ds:MultiByteToWideChar
cmp	[esp+108D4h+var_108C0],	0
jz	loc_401C80
push	0		; hTemplateFile
push	8000000h	; dwFlagsAndAttributes
push	3		; dwCreationDisposition
push	0		; lpSecurityAttributes
push	1		; dwShareMode
push	80000000h	; dwDesiredAccess
lea	eax, [esp+108ECh+WideCharStr]
push	eax		; lpFileName
call	ds:CreateFileW
cmp	eax, 0FFFFFFFFh
jz	short loc_401C80
push	1		; dwMoveMethod
lea	edx, [esp+108D8h+NewFilePointer]
push	edx		; lpNewFilePointer
mov	edi, eax
xor	ecx, ecx
push	ecx
xor	eax, eax
push	eax		; liDistanceToMove
push	edi		; hFile
call	ds:SetFilePointerEx
test	eax, eax
jz	short loc_401C79
xor	esi, esi
mov	edi, edi

loc_401C40:		; lpOverlapped
push	0
lea	eax, [esp+108D8h+NumberOfBytesRead]
push	eax		; lpNumberOfBytesRead
push	ebx		; nNumberOfBytesToRead
lea	ecx, [esp+108E0h+Buffer]
push	ecx		; lpBuffer
push	edi		; hFile
call	ebp ; ReadFile
test	eax, eax
jz	short loc_401C64
cmp	[esp+108D4h+NumberOfBytesRead],	ebx
jnz	short loc_401C64
add	esi, ebx
cmp	esi, 0FFFFFFFFh
jb	short loc_401C40

loc_401C64:
mov	edx, dword ptr [esp+108D4h+NewFilePointer+4]
mov	eax, dword ptr [esp+108D4h+NewFilePointer]
push	0		; dwMoveMethod
push	0		; lpNewFilePointer
push	edx
push	eax		; liDistanceToMove
push	edi		; hFile
call	ds:SetFilePointerEx

loc_401C79:		; hObject
push	edi
call	ds:CloseHandle

loc_401C80:		; dwFlags
push	8
push	0		; hFile
lea	ecx, [esp+108DCh+WideCharStr]
push	ecx		; lpLibFileName
call	ds:LoadLibraryExW
test	eax, eax
jz	loc_402C73
push	8
mov	esi, eax
call	ds:??2@YAPAXI@Z	; operator new(uint)
add	esp, 4
test	eax, eax
jz	short loc_401CBB
mov	edx, dword_405480
mov	[eax+4], edx
mov	[eax], esi
mov	dword_405480, eax

loc_401CBB:
mov	eax, [esp+108D4h+File]
push	eax		; File
lea	ecx, [esp+108D8h+ProcName]
push	104h		; MaxCount
push	ecx		; Buf
call	ds:fgets
add	esp, 0Ch
test	eax, eax
jnz	loc_401B60

loc_401CDE:
mov	ecx, dword_405480
mov	eax, [ecx]
mov	ebx, ds:GetProcAddress
push	offset aNs_getfrozenfu ; "NS_GetFrozenFunctions"
push	eax		; hModule
call	ebx ; GetProcAddress
test	eax, eax
jz	loc_402CB8
mov	esi, eax
mov	eax, [esp+108D4h+File]
push	eax		; File
call	ds:fclose
push	0
push	offset dword_405398
call	esi
add	esp, 0Ch
test	eax, eax
js	loc_402CD4
xor	esi, esi

loc_401D1F:
test	esi, esi
js	loc_402CE0
xor	ebp, ebp
cmp	ds:off_404538, ebp
jz	short loc_401D85
mov	edi, ds:_snprintf
mov	esi, offset off_404538
lea	esp, [esp+0]

loc_401D40:
mov	ecx, [esi]
push	ecx
push	offset Format	; "%s"
lea	edx, [esp+108DCh+ProcName]
push	200h		; Count
push	edx		; Dest
call	edi ; _snprintf
mov	eax, dword_405480
mov	eax, [eax]
add	esp, 10h
lea	ecx, [esp+108D4h+ProcName]
push	ecx		; lpProcName
push	eax		; hModule
call	ebx ; GetProcAddress
mov	edx, [esi+4]
mov	[edx], eax
mov	eax, [esi+4]
cmp	dword ptr [eax], 0
jz	loc_402CF2

loc_401D7D:
add	esi, 8
cmp	dword ptr [esi], 0
jnz	short loc_401D40

loc_401D85:
test	ebp, ebp
js	loc_402CFC
mov	eax, dword_405434
test	eax, eax
jz	short loc_401D98
call	eax ; dword_405434

loc_401D98:
mov	ecx, [esp+108D4h+var_10894]
mov	byte ptr [ecx],	0
mov	eax, dword_4053D0
test	eax, eax
jz	short loc_401DB2
lea	edx, [esp+108D4h+NewFilePointer]
push	edx
call	eax ; dword_4053D0
add	esp, 4

loc_401DB2:
mov	eax, dword_405420
test	eax, eax
jz	short loc_401DD1
push	2
push	0FFFFFFFFh
lea	ecx, [esp+108DCh+MultiByteStr]
push	ecx
lea	edx, [esp+108E0h+var_10888]
push	edx
call	eax ; dword_405420
add	esp, 10h

loc_401DD1:
mov	eax, dword_405400
test	eax, eax
jz	short loc_401DEB
lea	ecx, [esp+108D4h+NewFilePointer]
push	ecx
lea	edx, [esp+108D8h+var_10888]
push	1
push	edx
call	eax ; dword_405400
add	esp, 0Ch

loc_401DEB:
mov	eax, dword_4053EC
test	eax, eax
jz	short loc_401DFE
lea	ecx, [esp+108D4h+var_10888]
push	ecx
call	eax ; dword_4053EC
add	esp, 4

loc_401DFE:
mov	eax, dword_4053B8
test	eax, eax
jz	loc_402D10
lea	edx, [esp+108D4h+var_10890]
push	edx
lea	ecx, [esp+108D8h+NewFilePointer]
push	0
push	ecx
call	eax ; dword_4053B8
add	esp, 0Ch
mov	esi, eax

loc_401E1E:
mov	eax, dword_4053D4
test	eax, eax
jz	short loc_401E31
lea	edx, [esp+108D4h+NewFilePointer]
push	edx
call	eax ; dword_4053D4
add	esp, 4

loc_401E31:
test	esi, esi
js	loc_402D1A
mov	eax, dword ptr [esp+108D4h+Frequency+4]
mov	ecx, dword ptr [esp+108D4h+Frequency]
push	eax
push	ecx
push	1
call	dword_40538C
add	esp, 0Ch
call	dword_405388
cmp	[esp+108D4h+var_1088C],	0
jz	short loc_401ED3
mov	edx, dword ptr [esp+108D4h+IoCounters.ReadOperationCount]
push	edx
push	32h
call	dword_405380
mov	eax, dword ptr [esp+108DCh+IoCounters.ReadTransferCount]
mov	ecx, dword ptr [esp+108DCh+IoCounters.ReadTransferCount+4]
shrd	eax, ecx, 0Ah
push	eax
push	33h
call	dword_405380
add	esp, 10h
lea	edx, [esp+108D4h+var_1084C]
push	edx		; lpIoCounters
call	ds:GetCurrentProcess
push	eax		; hProcess
call	ds:GetProcessIoCounters
test	eax, eax
jz	short loc_401ED3
mov	eax, [esp+108D4h+var_1084C]
sub	eax, dword ptr [esp+108D4h+IoCounters.ReadOperationCount]
push	eax
push	34h
call	dword_405380
mov	ecx, [esp+108DCh+var_10834]
sub	ecx, dword ptr [esp+108DCh+IoCounters.ReadTransferCount]
mov	edx, [esp+108DCh+var_10830]
sbb	edx, dword ptr [esp+108DCh+IoCounters.ReadTransferCount+4]
shrd	ecx, edx, 0Ah
push	ecx
push	35h
call	dword_405380
add	esp, 10h

loc_401ED3:
mov	eax, [esp+108D4h+var_10890]
mov	ecx, [esp+108D4h+var_108B8]
mov	ebp, [esp+108D4h+var_108B0]
push	eax
push	ecx
mov	ecx, ebp
call	sub_401000
mov	esi, eax
mov	eax, dword_405438
add	esp, 8
test	eax, eax
jz	short loc_401EF8
call	eax ; dword_405438

loc_401EF8:
mov	edi, esi

loc_401EFA:		; operator delete[](void *)
mov	ebx, ds:??_V@YAXPAX@Z
push	ebp
call	ebx ; operator delete[](void *)	; operator delete[](void *)
mov	esi, [esp+108D8h+var_108B8]
mov	ebp, [esp+108D8h+var_108BC]
add	esp, 4
test	esi, esi
jz	short loc_401F21

loc_401F12:
mov	edx, [ebp+esi*4-4]
dec	esi
push	edx
call	ebx ; operator delete[](void *)	; operator delete[](void *)
add	esp, 4
test	esi, esi
jnz	short loc_401F12

loc_401F21:
push	ebp
call	ebx ; operator delete[](void *)	; operator delete[](void *)
add	esp, 4
mov	eax, edi

loc_401F29:
mov	ecx, [esp+108D4h+var_4]
pop	edi
pop	esi
pop	ebp
pop	ebx
xor	ecx, esp
call	@__security_check_cookie@4 ; __security_check_cookie(x)
add	esp, 108C4h
retn

loc_401F42:
mov	edi, esi
jmp	loc_401A8F
_wmain endp

; [0000004B BYTES: COLLAPSED FUNCTION _pre_cpp_init. PRESS KEYPAD "+" TO EXPAND]
; [00000189 BYTES: COLLAPSED FUNCTION ___tmainCRTStartup. PRESS	KEYPAD "+" TO EXPAND]
; [000000BA BYTES: COLLAPSED FUNCTION $LN33. PRESS KEYPAD "+" TO EXPAND]
; [0000000A BYTES: COLLAPSED FUNCTION start. PRESS KEYPAD "+" TO EXPAND]
; [0000000F BYTES: COLLAPSED FUNCTION __security_check_cookie(x). PRESS	KEYPAD "+" TO EXPAND]


; Attributes: bp-based frame

sub_4021F0 proc	near
mov	edi, edi
push	ebp
mov	ebp, esp
pop	ebp
jmp	loc_4021FC
align 4

loc_4021FC:		; operator new(uint)
jmp	ds:??2@YAPAXI@Z
sub_4021F0 endp

; [00000042 BYTES: COLLAPSED FUNCTION __CxxUnhandledExceptionFilter(_EXCEPTION_POINTERS	*). PRESS KEYPAD "+" TO	EXPAND]
; [0000000E BYTES: COLLAPSED FUNCTION $LN5. PRESS KEYPAD "+" TO	EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _amsg_exit. PRESS	KEYPAD "+" TO EXPAND]
; [000000A1 BYTES: COLLAPSED FUNCTION __onexit.	PRESS KEYPAD "+" TO EXPAND]


; Attributes: library function bp-based	frame

; int __cdecl atexit(void (__cdecl *)())
_atexit	proc near

arg_0= dword ptr  8

mov	edi, edi
push	ebp
mov	ebp, esp
push	[ebp+arg_0]	; _onexit_t
call	__onexit
neg	eax
sbb	eax, eax
neg	eax
pop	ecx
dec	eax
pop	ebp
retn
_atexit	endp




sub_402310 proc	near
mov	edi, edi
push	esi
mov	eax, offset unk_404858
mov	esi, offset unk_404858
push	edi
mov	edi, eax
cmp	eax, esi
jnb	short loc_402333

loc_402324:
mov	eax, [edi]
test	eax, eax
jz	short loc_40232C
call	eax

loc_40232C:
add	edi, 4
cmp	edi, esi
jb	short loc_402324

loc_402333:
pop	edi
pop	esi
retn
sub_402310 endp




; void __cdecl sub_402336()
sub_402336 proc	near
mov	edi, edi
push	esi
mov	eax, offset unk_404860
mov	esi, offset unk_404860
push	edi
mov	edi, eax
cmp	eax, esi
jnb	short loc_402359

loc_40234A:
mov	eax, [edi]
test	eax, eax
jz	short loc_402352
call	eax

loc_402352:
add	edi, 4
cmp	edi, esi
jb	short loc_40234A

loc_402359:
pop	edi
pop	esi
retn
sub_402336 endp

; [00000006 BYTES: COLLAPSED FUNCTION _XcptFilter. PRESS KEYPAD	"+" TO EXPAND]
align 10h
; [00000035 BYTES: COLLAPSED FUNCTION __ValidateImageBase. PRESS KEYPAD	"+" TO EXPAND]
align 10h
; [00000044 BYTES: COLLAPSED FUNCTION __FindPESection. PRESS KEYPAD "+"	TO EXPAND]
align 10h
; [000000BC BYTES: COLLAPSED FUNCTION __IsNonwritableInCurrentImage. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _initterm. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _initterm_e. PRESS KEYPAD	"+" TO EXPAND]
align 10h
; [00000045 BYTES: COLLAPSED FUNCTION __SEH_prolog4. PRESS KEYPAD "+" TO EXPAND]
; [00000014 BYTES: COLLAPSED FUNCTION __SEH_epilog4. PRESS KEYPAD "+" TO EXPAND]
; [00000025 BYTES: COLLAPSED FUNCTION __except_handler4. PRESS KEYPAD "+" TO EXPAND]
; [00000028 BYTES: COLLAPSED FUNCTION __setdefaultprecision. PRESS KEYPAD "+" TO EXPAND]
; [00000003 BYTES: COLLAPSED FUNCTION $LN7_0. PRESS KEYPAD "+" TO EXPAND]
; [0000009B BYTES: COLLAPSED FUNCTION ___security_init_cookie. PRESS KEYPAD "+"	TO EXPAND]
; [00000106 BYTES: COLLAPSED FUNCTION ___report_gsfailure. PRESS KEYPAD	"+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION terminate(void). PRESS KEYPAD "+"	TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _unlock. PRESS KEYPAD "+"	TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION __dllonexit. PRESS KEYPAD	"+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _lock. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _except_handler4_common. PRESS KEYPAD "+"	TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _invoke_watson. PRESS KEYPAD "+" TO EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _controlfp_s. PRESS KEYPAD "+" TO	EXPAND]
; [00000006 BYTES: COLLAPSED FUNCTION _crt_debugger_hook. PRESS	KEYPAD "+" TO EXPAND]
align 10h
; [0000002B BYTES: COLLAPSED FUNCTION __alloca_probe. PRESS KEYPAD "+" TO EXPAND]
align 10h
; [00000034 BYTES: COLLAPSED FUNCTION __allmul.	PRESS KEYPAD "+" TO EXPAND]
; START	OF FUNCTION CHUNK FOR sub_401000

loc_4027B4:
cmp	byte ptr [eax],	0
jz	loc_401045
mov	esi, eax
lea	eax, [esp+280h+var_270]
push	eax
call	sub_402F5B
push	eax
push	esi
call	dword_405394
add	esp, 8
test	eax, eax
jns	loc_40107D
push	esi		; ArgList
push	offset aInvalidPathFou ; "Invalid path found: '%s'"
call	sub_402DC7
add	esp, 8
lea	ecx, [esp+280h+var_270]
push	ecx
call	sub_402EA0
mov	eax, 0FFh
jmp	loc_4016E4

loc_4027FE:
inc	eax
jmp	loc_401066

loc_402804:
cmp	cl, 2Fh
jnz	loc_40107D
inc	eax
push	offset Str2	; "app"
push	eax		; Str1
call	ds:_stricmp
add	esp, 8
test	eax, eax
jnz	loc_40107D

loc_402825:
mov	esi, 2
cmp	[esp+280h+arg_0], esi
jnz	loc_4028AE
push	offset aIncorrectNumbe ; "Incorrect number of arguments	passed to"...
call	sub_402DC7
add	esp, 4
lea	edx, [esp+280h+var_270]
push	edx
call	sub_402EA0
mov	eax, 0FFh
jmp	loc_4016E4

loc_402858:		; "Couldn't read application.ini"
push	offset aCouldnTReadApp
call	sub_402DC7
add	esp, 4
lea	edx, [esp+280h+var_270]
push	edx
call	sub_402EA0
mov	eax, 0FFh
jmp	loc_4016E4

loc_402879:		; "Couldn't find the application directory"...
push	offset aCouldnTFindThe
call	sub_402DC7
add	esp, 4
lea	ecx, [esp+280h+var_224]
push	ecx
call	sub_402EA0
lea	edx, [esp+280h+Dst]
push	edx
call	sub_402F6C
lea	eax, [esp+280h+var_270]
push	eax
call	sub_402EA0
mov	eax, 0FFh
jmp	loc_4016E4

loc_4028AE:
lea	eax, [esp+280h+var_270]
push	eax
call	sub_402F5B
mov	ecx, [ebx+8]
push	eax
push	ecx
call	dword_405394
add	esp, 8
test	eax, eax
jns	loc_4028F3
mov	edx, [ebx+8]
push	edx		; ArgList
push	offset aApplication_in ; "application.ini path not recognized: '%"...
call	sub_402DC7
add	esp, 8
lea	eax, [esp+280h+var_270]
push	eax
call	sub_402EA0
mov	eax, 0FFh
jmp	loc_4016E4

loc_4028F3:
mov	ecx, [ebx+8]
push	ecx
push	offset aXul_app_fileS ;	"XUL_APP_FILE=%s"
lea	edx, [esp+288h+Dest]
push	104h		; Count
push	edx		; Dest
call	ds:_snprintf
lea	eax, [esp+290h+Dest]
push	eax		; EnvString
call	ds:_putenv
add	esp, 14h
test	eax, eax
jz	loc_40294B
lea	ecx, [esp+280h+Dest]
push	ecx		; ArgList
push	offset aCouldnTSetS_ ; "Couldn't set %s.\n"
call	sub_402DC7
add	esp, 8
lea	edx, [esp+280h+var_270]
push	edx
call	sub_402EA0
mov	eax, 0FFh
jmp	loc_4016E4

loc_40294B:
mov	eax, [ebx]
mov	[ebx+8], eax
add	ebx, 8
sub	[esp+280h+arg_0], esi
mov	[esp+280h+var_220], ebx
jmp	loc_40107D

loc_402963:
lea	ecx, [esp+280h+var_26C]
push	ecx
push	eax
call	dword_40537C
add	esp, 8
test	eax, eax
js	loc_402858
mov	eax, [esp+280h+var_26C]
mov	edx, [esp+280h+arg_0]
mov	[eax+24h], ebp
mov	ecx, [esp+280h+var_26C]
push	edi
push	ecx
push	ebx
push	edx
call	dword_405390
mov	esi, eax
mov	eax, [esp+290h+var_26C]
push	eax
call	dword_405384
add	esp, 14h
lea	ecx, [esp+280h+var_270]
push	ecx
call	sub_402EA0
mov	eax, esi
jmp	loc_4016E4

loc_4029B7:
xor	esi, esi
jmp	loc_401102

loc_4029BE:
mov	[esp+280h+var_25C], edi
jmp	loc_40110B

loc_4029C7:
xor	esi, esi
jmp	loc_401160

loc_4029CE:
mov	[esp+280h+var_258], 0
jmp	loc_401169

loc_4029DB:
xor	esi, esi
jmp	loc_4011BE

loc_4029E2:
mov	[esp+280h+var_254], 0
jmp	loc_4011C7

loc_4029EF:
xor	esi, esi
jmp	loc_40121C

loc_4029F6:
mov	[esp+280h+var_250], 0
jmp	loc_401225

loc_402A03:
mov	[esp+280h+var_24C], esi
jmp	loc_401283

loc_402A0C:
mov	eax, [ecx]
push	ecx
mov	ecx, [eax+8]
call	ecx
mov	eax, dword_405418
jmp	loc_4012BD

loc_402A1E:
mov	edx, [ecx]
mov	eax, [edx+8]
push	ecx
call	eax
mov	eax, dword_405418
jmp	loc_4012D5

loc_402A30:
xor	esi, esi
jmp	loc_40132E

loc_402A37:
mov	[esp+280h+var_23C], 0
jmp	loc_401337

loc_402A44:
xor	esi, esi
jmp	loc_40138C

loc_402A4B:
mov	[esp+280h+var_238], 0
jmp	loc_401395

loc_402A58:
mov	[esp+280h+var_234], esi
jmp	loc_4013F3

loc_402A61:		; Src
push	edi
call	sub_402EB8
add	esp, 4
mov	[esp+280h+var_22C], eax
jmp	loc_401413

loc_402A73:
mov	edi, 80004005h
jmp	loc_401438

loc_402A7D:
lea	eax, [esp+280h+var_268]
push	eax
call	sub_402EA0
jmp	loc_4014C9

loc_402A8C:
mov	ecx, [eax]
mov	edx, [ecx+8]
push	eax
call	edx
jmp	loc_401450

loc_402A99:
mov	edi, 0C1F30001h
jmp	loc_40148C

loc_402AA3:
lea	edx, [esp+280h+var_268]
push	edx
call	sub_402EA0
jmp	loc_4014C9

loc_402AB2:
mov	ecx, [eax]
mov	edx, [ecx+8]
push	eax
call	edx
jmp	loc_40154D

loc_402ABF:
mov	[esp+280h+var_22C], esi
mov	ecx, [eax]
mov	edx, [ecx+8]
push	eax
call	edx
jmp	loc_4016E2
; END OF FUNCTION CHUNK	FOR sub_401000
; START	OF FUNCTION CHUNK FOR _wmain

loc_402AD0:
xor	eax, eax
jmp	loc_401892

loc_402AD7:
test	ecx, 0F800h
jnz	loc_402AFD
mov	eax, ecx
shr	eax, 6
and	cl, 3Fh
or	al, 0C0h
or	cl, 80h
mov	[esi], al
mov	[esi+1], cl
add	esi, 2
jmp	loc_401882

loc_402AFD:
mov	ebx, ecx
mov	eax, ecx
and	eax, 0FFFFF800h
cmp	eax, 0D800h
jz	loc_402B39
mov	ax, cx
shr	ax, 0Ch
or	al, 0E0h
mov	[esi], al
mov	eax, ecx
shr	eax, 6
and	al, 3Fh
and	cl, 3Fh
or	al, 80h
or	cl, 80h
mov	[esi+1], al
mov	[esi+2], cl
add	esi, 3
jmp	loc_401882

loc_402B39:
and	ebx, 0FFFFFC00h
cmp	ebx, 0D800h
jnz	loc_402BC5
add	edx, 2
cmp	edx, edi
jz	loc_402BEA
movzx	ebx, word ptr [edx]
mov	eax, ebx
and	eax, 0FFFFFC00h
cmp	eax, 0DC00h
jnz	loc_402BB1
and	ecx, 3FFh
add	ecx, 40h
shl	ecx, 0Ah
and	ebx, 3FFh
add	ecx, ebx
mov	eax, ecx
shr	eax, 12h
or	al, 0F0h
mov	[esi], al
mov	eax, ecx
shr	eax, 0Ch
and	al, 3Fh
or	al, 80h
mov	[esi+1], al
mov	eax, ecx
shr	eax, 6
and	al, 3Fh
and	cl, 3Fh
or	al, 80h
or	cl, 80h
mov	[esi+2], al
mov	[esi+3], cl
add	esi, 4
jmp	loc_401882

loc_402BB1:
mov	word ptr [esi],	0BFEFh
mov	byte ptr [esi+2], 0BDh
add	esi, 3
sub	edx, 2
jmp	loc_401882

loc_402BC5:
mov	word ptr [esi],	0BFEFh
mov	byte ptr [esi+2], 0BDh
add	esi, 3
jmp	loc_401882

loc_402BD6:
push	esi
push	ebx
call	sub_402E54
add	esp, 8

loc_402BE0:
mov	eax, 7Fh
jmp	loc_401F29

loc_402BEA:
mov	word ptr [esi],	0BFEFh
mov	byte ptr [esi+2], 0BDh
add	esi, 3
jmp	loc_401889

loc_402BFB:
mov	eax, offset sub_402D90
mov	dword_40548C, eax
jmp	loc_40193C

loc_402C0A:
mov	esi, 80004005h
jmp	loc_40198C

loc_402C14:		; "Couldn't find the application directory"...
push	offset aCouldnTFindThe
call	sub_402DC7
add	esp, 4
jmp	loc_401E31

loc_402C26:		; "Could not find the Mozilla runtime.\n"
push	offset aCouldNotFindTh
call	sub_402DC7
add	esp, 4

loc_402C33:
mov	esi, 80004005h
jmp	loc_401E31

loc_402C3D:
lea	ecx, [esp+108D4h+Dst]
push	offset aDependentlib_0 ; "dependentlibs.list"
push	ecx		; Dest
call	ds:strcpy
add	esp, 8
lea	esi, [esp+108D4h+Dst]
jmp	loc_401AEB

loc_402C5F:
push	0
call	sub_402D40
add	esp, 4

loc_402C69:
mov	esi, 80040111h
jmp	loc_401D1F

loc_402C73:
call	ds:GetLastError
call	sub_402F20
mov	eax, [esp+108D4h+File]
push	eax
call	sub_402D40
mov	ebx, ds:GetProcAddress
add	esp, 4
mov	esi, 80040111h
jmp	loc_401D1F

loc_402C9B:
mov	edx, [esp+108D4h+File]
push	edx
call	sub_402D40
mov	ebx, ds:GetProcAddress
add	esp, 4
mov	esi, 80040111h
jmp	loc_401D1F

loc_402CB8:
call	sub_402F20
mov	edx, [esp+108D4h+File]
push	edx
call	sub_402D40
add	esp, 4
mov	esi, 80040111h
jmp	loc_401D1F

loc_402CD4:
mov	esi, eax
call	sub_402F20
jmp	loc_401D1F

loc_402CE0:		; "Couldn't load XPCOM.\n"
push	offset aCouldnTLoadXpc
call	sub_402DC7
add	esp, 4
jmp	loc_401E31

loc_402CF2:
mov	ebp, 80460003h
jmp	loc_401D7D

loc_402CFC:		; "Couldn't load XRE functions.\n"
push	offset aCouldnTLoadXre
call	sub_402DC7
add	esp, 4
mov	esi, ebp
jmp	loc_401E31

loc_402D10:
mov	esi, 0C1F30001h
jmp	loc_401E1E

loc_402D1A:
mov	ebp, [esp+108D4h+var_108B0]
mov	edi, 0FFh
jmp	loc_401EFA
; END OF FUNCTION CHUNK	FOR _wmain



sub_402D28 proc	near
mov	eax, dword_405418
test	eax, eax
jz	short locret_402D33
jmp	eax

locret_402D33:
retn
sub_402D28 endp




sub_402D34 proc	near
mov	eax, dword_405410
test	eax, eax
jnz	short loc_402D3E
retn

loc_402D3E:
jmp	eax
sub_402D34 endp




sub_402D40 proc	near

arg_0= dword ptr  4

mov	eax, [esp+arg_0]
test	eax, eax
jz	short locret_402D52
mov	[esp+arg_0], eax
jmp	ds:fclose

locret_402D52:
retn
sub_402D40 endp




sub_402D53 proc	near

arg_0= dword ptr  4

mov	eax, [esp+arg_0]
test	eax, eax
jz	short locret_402D63
mov	ecx, [eax]
mov	edx, [ecx+4]
push	eax
call	edx

locret_402D63:
retn
sub_402D53 endp




sub_402D64 proc	near

arg_0= dword ptr  4
arg_4= dword ptr  8

push	esi
mov	esi, [esp+4+arg_0]
mov	eax, [esi]
push	edi
mov	edi, [esp+8+arg_4]
test	eax, eax
jz	short loc_402D82
mov	ecx, [eax]
mov	edx, [ecx+8]
push	eax
call	edx
mov	dword ptr [esi], 0

loc_402D82:
push	edi
mov	[esi], edi
call	sub_402D53
add	esp, 4
pop	edi
pop	esi
retn
sub_402D64 endp




sub_402D90 proc	near
call	ds:GetTickCount
mov	ecx, eax
mov	eax, dword_405484
cmp	eax, ecx
jbe	short loc_402DB0
sub	eax, ecx
cmp	eax, 40000000h
jbe	short loc_402DB0
inc	dword_405488

loc_402DB0:
mov	edx, dword_405488
push	esi
xor	esi, esi
xor	eax, eax
or	edx, esi
mov	dword_405484, ecx
or	eax, ecx
pop	esi
retn
sub_402D90 endp




; int __cdecl sub_402DC7(char *Format, char ArgList)
sub_402DC7 proc	near

MultiByteStr= byte ptr -1804h
Text= word ptr -1004h
var_4= dword ptr -4
Format=	dword ptr  4
ArgList= byte ptr  8

mov	eax, 1804h
call	__alloca_probe
mov	eax, ___security_cookie
xor	eax, esp
mov	[esp+1804h+var_4], eax
mov	ecx, [esp+1804h+Format]
lea	eax, [esp+1804h+ArgList]
push	eax		; ArgList
push	ecx		; Format
push	0FFFFFFFFh	; MaxCount
lea	edx, [esp+1810h+MultiByteStr]
push	800h		; DstSize
push	edx		; DstBuf
call	ds:_vsnprintf_s
add	esp, 14h
push	800h		; cchWideChar
lea	eax, [esp+1808h+Text]
push	eax		; lpWideCharStr
push	0FFFFFFFFh	; cbMultiByte
lea	ecx, [esp+1810h+MultiByteStr]
push	ecx		; lpMultiByteStr
push	0		; dwFlags
push	0FDE9h		; CodePage
call	ds:MultiByteToWideChar
push	10010h		; uType
push	offset Caption	; "Firefox"
lea	edx, [esp+180Ch+Text]
push	edx		; lpText
push	0		; hWnd
call	ds:MessageBoxW
mov	ecx, [esp+1804h+var_4]
xor	ecx, esp
call	@__security_check_cookie@4 ; __security_check_cookie(x)
add	esp, 1804h
retn
sub_402DC7 endp




sub_402E54 proc	near

arg_0= dword ptr  4
arg_4= dword ptr  8

push	ebx
mov	ebx, ds:??_V@YAXPAX@Z ;	operator delete[](void *)
push	esi
mov	esi, [esp+8+arg_0]
push	edi
mov	edi, [esp+0Ch+arg_4]
test	esi, esi
jz	short loc_402E78

loc_402E69:
mov	eax, [edi+esi*4-4]
dec	esi
push	eax
call	ebx ; operator delete[](void *)	; operator delete[](void *)
add	esp, 4
test	esi, esi
jnz	short loc_402E69

loc_402E78:
push	edi
call	ebx ; operator delete[](void *)	; operator delete[](void *)
add	esp, 4
pop	edi
pop	esi
pop	ebx
retn
sub_402E54 endp




sub_402E82 proc	near

arg_0= dword ptr  4

mov	ecx, [esp+arg_0]
mov	eax, [ecx]
mov	dword ptr [ecx], 0
test	eax, eax
jz	short locret_402E9D
mov	ecx, [eax]
mov	edx, [ecx+8]
mov	[esp+arg_0], eax
jmp	edx

locret_402E9D:
retn	4
sub_402E82 endp




sub_402EA0 proc	near

arg_0= dword ptr  4

mov	eax, [esp+arg_0]
mov	eax, [eax]
test	eax, eax
jz	short locret_402EB5
mov	ecx, [eax]
mov	edx, [ecx+8]
mov	[esp+arg_0], eax
jmp	edx

locret_402EB5:
retn	4
sub_402EA0 endp




; int __cdecl sub_402EB8(char *Src)
sub_402EB8 proc	near

Src= dword ptr	4

push	ebx
mov	ebx, [esp+4+Src]
push	esi
push	edi
push	ebx		; Str
call	ds:strlen
mov	edi, eax
lea	eax, [edi+1]
push	eax
call	sub_402D34
mov	esi, eax
add	esp, 8
test	esi, esi
jz	short loc_402EEC
push	edi		; Size
push	ebx		; Src
push	esi		; Dst
call	ds:memcpy
add	esp, 0Ch
mov	byte ptr [esi+edi], 0
mov	eax, esi

loc_402EEC:
pop	edi
pop	esi
pop	ebx
retn
sub_402EB8 endp




; int __cdecl sub_402EF0(int, char *Src)
sub_402EF0 proc	near

arg_0= dword ptr  4
Src= dword ptr	8

push	esi
mov	esi, [esp+4+arg_0]
mov	eax, [esi]
push	edi
mov	edi, [esp+8+Src]
push	eax
call	sub_402D28
add	esp, 4
test	edi, edi
jz	short loc_402F17
push	edi		; Src
call	sub_402EB8
add	esp, 4
pop	edi
mov	[esi], eax
pop	esi
retn

loc_402F17:
pop	edi
mov	dword ptr [esi], 0
pop	esi
retn
sub_402EF0 endp




sub_402F20 proc	near
mov	eax, dword_405480
test	eax, eax
jz	short locret_402F5A
lea	esp, [esp+0]

loc_402F30:
mov	eax, [eax]
push	eax		; hLibModule
call	ds:FreeLibrary
mov	eax, dword_405480
mov	ecx, [eax+4]
push	eax
mov	dword_405480, ecx
call	ds:??3@YAXPAX@Z	; operator delete(void *)
mov	eax, dword_405480
add	esp, 4
test	eax, eax
jnz	short loc_402F30

locret_402F5A:
retn
sub_402F20 endp




sub_402F5B proc	near

arg_0= dword ptr  4

push	esi
mov	esi, [esp+4+arg_0]
push	esi
call	sub_402E82
mov	eax, esi
pop	esi
retn	4
sub_402F5B endp




sub_402F6C proc	near

arg_0= dword ptr  4

push	esi
mov	esi, [esp+4+arg_0]
lea	eax, [esi+8]
push	0		; Src
push	eax		; int
call	sub_402EF0
lea	ecx, [esi+0Ch]
push	0		; Src
push	ecx		; int
call	sub_402EF0
lea	edx, [esi+10h]
push	0		; Src
push	edx		; int
call	sub_402EF0
lea	eax, [esi+14h]
push	0		; Src
push	eax		; int
call	sub_402EF0
lea	ecx, [esi+18h]
push	0		; Src
push	ecx		; int
call	sub_402EF0
lea	edx, [esi+1Ch]
push	0		; Src
push	edx		; int
call	sub_402EF0
lea	eax, [esi+34h]
push	0		; Src
push	eax		; int
call	sub_402EF0
mov	eax, [esi+4]
add	esp, 38h
test	eax, eax
jz	short loc_402FD7
mov	ecx, [eax]
mov	edx, [ecx+8]
push	eax
call	edx
mov	dword ptr [esi+4], 0

loc_402FD7:
lea	eax, [esi+24h]
push	0
push	eax
call	sub_402D64
lea	ecx, [esi+28h]
push	0		; Src
push	ecx		; int
call	sub_402EF0
lea	edx, [esi+2Ch]
push	0		; Src
push	edx		; int
call	sub_402EF0
lea	eax, [esi+30h]
push	0		; Src
push	eax		; int
call	sub_402EF0
push	0		; Src
add	esi, 38h
push	esi		; int
call	sub_402EF0
add	esp, 28h
pop	esi
retn	4
sub_402F6C endp

align 4
dd 7Ah dup(0)
dd 380h	dup(?)
_text ends

; Section 2. (virtual address 00004000)
; Virtual size			: 00000F76 (   3958.)
; Section size in file		: 00001000 (   4096.)
; Offset to raw	data for section: 00002600
; Flags	40000040: Data Readable
; Alignment	: default
;
; Imports from KERNEL32.dll
;

; Segment type:	Externs
; _idata
; DWORD	__stdcall GetEnvironmentVariableW(LPCWSTR lpName, LPWSTR lpBuffer, DWORD nSize)
extrn GetEnvironmentVariableW:dword
; BOOL __stdcall GetProcessIoCounters(HANDLE hProcess, PIO_COUNTERS lpIoCounters)
extrn GetProcessIoCounters:dword
extrn SetDllDirectoryW:dword
; HANDLE __stdcall GetCurrentProcess()
extrn GetCurrentProcess:dword
; BOOL __stdcall SetEnvironmentVariableW(LPCWSTR lpName, LPCWSTR lpValue)
extrn SetEnvironmentVariableW:dword
; HMODULE __stdcall GetModuleHandleW(LPCWSTR lpModuleName)
extrn GetModuleHandleW:dword
; DWORD	__stdcall GetTickCount()
extrn GetTickCount:dword
; int __stdcall	WideCharToMultiByte(UINT CodePage, DWORD dwFlags, LPCWSTR lpWideCharStr, int cchWideChar, LPSTR	lpMultiByteStr,	int cbMultiByte, LPCSTR	lpDefaultChar, LPBOOL lpUsedDefaultChar)
extrn WideCharToMultiByte:dword
; DWORD	__stdcall GetFileAttributesW(LPCWSTR lpFileName)
extrn GetFileAttributesW:dword
; DWORD	__stdcall GetModuleFileNameW(HMODULE hModule, LPWCH lpFilename,	DWORD nSize)
extrn GetModuleFileNameW:dword
; int __stdcall	MultiByteToWideChar(UINT CodePage, DWORD dwFlags, LPCSTR lpMultiByteStr, int cbMultiByte, LPWSTR lpWideCharStr,	int cchWideChar)
extrn MultiByteToWideChar:dword
; FARPROC __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName)
extrn GetProcAddress:dword
; BOOL __stdcall QueryPerformanceFrequency(LARGE_INTEGER *lpFrequency)
extrn QueryPerformanceFrequency:dword
; DWORD	__stdcall ExpandEnvironmentStringsW(LPCWSTR lpSrc, LPWSTR lpDst, DWORD nSize)
extrn ExpandEnvironmentStringsW:dword
; BOOL __stdcall IsDebuggerPresent()
extrn IsDebuggerPresent:dword
; LONG __stdcall UnhandledExceptionFilter(struct _EXCEPTION_POINTERS *ExceptionInfo)
extrn UnhandledExceptionFilter:dword
; void __stdcall GetSystemTimeAsFileTime(LPFILETIME lpSystemTimeAsFileTime)
extrn GetSystemTimeAsFileTime:dword
; DWORD	__stdcall GetCurrentProcessId()
extrn GetCurrentProcessId:dword
; DWORD	__stdcall GetCurrentThreadId()
extrn GetCurrentThreadId:dword
; BOOL __stdcall QueryPerformanceCounter(LARGE_INTEGER *lpPerformanceCount)
extrn QueryPerformanceCounter:dword
; PVOID	__stdcall DecodePointer(PVOID Ptr)
extrn DecodePointer:dword
; LPTOP_LEVEL_EXCEPTION_FILTER __stdcall SetUnhandledExceptionFilter(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter)
extrn SetUnhandledExceptionFilter:dword
; PVOID	__stdcall EncodePointer(PVOID Ptr)
extrn EncodePointer:dword
; BOOL __stdcall HeapSetInformation(HANDLE HeapHandle, HEAP_INFORMATION_CLASS HeapInformationClass, PVOID HeapInformation, SIZE_T HeapInformationLength)
extrn HeapSetInformation:dword
; LONG __stdcall InterlockedCompareExchange(volatile LONG *Destination,	LONG Exchange, LONG Comperand)
extrn InterlockedCompareExchange:dword
; void __stdcall Sleep(DWORD dwMilliseconds)
extrn Sleep:dword
; LONG __stdcall InterlockedExchange(volatile LONG *Target, LONG Value)
extrn InterlockedExchange:dword
; BOOL __stdcall CloseHandle(HANDLE hObject)
extrn CloseHandle:dword
; HANDLE __stdcall CreateFileW(LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD	dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile)
extrn CreateFileW:dword
; BOOL __stdcall ReadFile(HANDLE hFile,	LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped)
extrn ReadFile:dword
; BOOL __stdcall SetFilePointerEx(HANDLE hFile,	LARGE_INTEGER liDistanceToMove,	PLARGE_INTEGER lpNewFilePointer, DWORD dwMoveMethod)
extrn SetFilePointerEx:dword
; DWORD	__stdcall GetLastError()
extrn GetLastError:dword
; HMODULE __stdcall LoadLibraryExW(LPCWSTR lpLibFileName, HANDLE hFile,	DWORD dwFlags)
extrn LoadLibraryExW:dword
; BOOL __stdcall FreeLibrary(HMODULE hLibModule)
extrn FreeLibrary:dword
; BOOL __stdcall TerminateProcess(HANDLE hProcess, UINT	uExitCode)
extrn TerminateProcess:dword

;
; Imports from MSVCR100.dll
;
extrn __wgetmainargs:dword
; void __cdecl cexit()
extrn _cexit:dword
; void __cdecl exit(int	Code)
extrn _exit:dword
extrn __imp__amsg_exit:dword
; void __cdecl exit(int	Code)
extrn exit:dword
extrn __winitenv:dword
extrn __imp__initterm:dword
extrn __imp__initterm_e:dword
extrn _configthreadlocale:dword
extrn __setusermatherr:dword
extrn _commode:dword
; int fmode
extrn _fmode:dword
extrn __set_app_type:dword
; int __cdecl vsnprintf_s(char *DstBuf,	size_t DstSize,	size_t MaxCount, const char *Format, va_list ArgList)
extrn _vsnprintf_s:dword
; __declspec(dllimport)	void __cdecl terminate(void)
extrn __imp_?terminate@@YAXXZ:dword
extrn __imp__unlock:dword
extrn __imp___dllonexit:dword
extrn __imp__lock:dword
; _onexit_t __cdecl onexit(_onexit_t Func)
extrn _onexit:dword
extrn __imp__except_handler4_common:dword
extrn __imp__invoke_watson:dword
; errno_t __cdecl _controlfp_s(unsigned	int *CurrentState, unsigned int	NewValue, unsigned int Mask)
extrn __imp__controlfp_s:dword
extrn __imp__crt_debugger_hook:dword
; void *__cdecl	memset(void *Dst, int Val, size_t Size)
extrn memset:dword
; void * __cdecl operator new(unsigned int)
extrn ??2@YAPAXI@Z:dword
; int __cdecl fclose(FILE *File)
extrn fclose:dword
; void __cdecl operator	delete(void *)
extrn ??3@YAXPAX@Z:dword
; char *__cdecl	fgets(char *Buf, int MaxCount, FILE *File)
extrn fgets:dword
; FILE *__cdecl	wfopen(const wchar_t *Filename,	const wchar_t *Mode)
extrn _wfopen:dword
; size_t __cdecl strlen(const char *Str)
extrn strlen:dword
; void *__cdecl	memcpy(void *Dst, const	void *Src, size_t Size)
extrn memcpy:dword
; char *__cdecl	getenv(const char *VarName)
extrn getenv:dword
; char *__cdecl	strrchr(const char *Str, int Ch)
extrn strrchr:dword
; void __cdecl operator	delete[](void *)
extrn ??_V@YAXPAX@Z:dword
; size_t __cdecl wcslen(const wchar_t *Str)
extrn wcslen:dword
; int snprintf(char *Dest, size_t Count, const char *Format, ...)
extrn _snprintf:dword
; char *__cdecl	strcpy(char *Dest, const char *Source)
extrn strcpy:dword
; int __cdecl stricmp(const char *Str1,	const char *Str2)
extrn _stricmp:dword
extrn __imp__XcptFilter:dword
; int __cdecl putenv(const char	*EnvString)
extrn _putenv:dword

;
; Imports from USER32.dll
;
; int __stdcall	MessageBoxW(HWND hWnd, LPCWSTR lpText, LPCWSTR lpCaption, UINT uType)
extrn MessageBoxW:dword



; Segment type:	Pure data
; Segment permissions: Read
_rdata segment para public 'DATA' use32
assume cs:_rdata
;org 40413Ch
unk_40413C db	 0
db    0
db    0
db    0
dd offset _pre_cpp_init
unk_404144 db	 0
db    0
db    0
db    0
unk_404148 db	 0
db    0
db    0
db    0
dd offset $LN33		; _pre_c_init
dd offset $LN5
unk_404154 db	 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db  49h	; I
db  40h	; @
db 0F8h	; ¯
db  51h	; Q
db    0
db    0
db    0
db    0
db    2
db    0
db    0
db    0
db  76h	; v
db    0
db    0
db    0
db 0D8h	; ÿ
db  47h	; G
db    0
db    0
db 0D8h	; ÿ
db  2Dh	; -
db    0
db    0
; struct _EXCEPTION_POINTERS ExceptionInfo
ExceptionInfo _EXCEPTION_POINTERS <offset dword_405050,\
		     offset dword_4050A8>
aXre_disablewri	db 'XRE_DisableWritePoisoning',0
align 10h
aXre_main db 'XRE_main',0
align 4
aXre_startuptim	db 'XRE_StartupTimelineRecord',0
align 4
aXre_telemetrya	db 'XRE_TelemetryAccumulate',0
aXre_setupdllbl	db 'XRE_SetupDllBlocklist',0
align 4
aXre_freeappdat	db 'XRE_FreeAppData',0
aXre_createappd	db 'XRE_CreateAppData',0
align 4
aXre_getfilefro	db 'XRE_GetFileFromPath',0
aHttpsCrashRepo	db 'https://crash-reports.mozilla.com/s'
db 'ubmit?id={ec8030f7-c20a-464f-9b0e-1'
db '3a3a9e97384}&version=23.0&buildid=2'
db '0130730113002',0
align 4
aEc8030f7C20a46	db '{ec8030f7-c20a-464f-9b0e-13a3a9e973'
db '84}',0
align 10h
a20130730113002	db '20130730113002',0
align 10h
a23_0 db '23.0',0
align 4
aFirefox_0 db 'Firefox',0
aMozilla db 'Mozilla',0
db    0
db    1
db    2
db    3
db    4
db    5
db    6
db    7
db    8
db    9
db  0Ah
db  0Bh
db  0Ch
db  0Dh
db  0Eh
db  0Fh
db  10h
db  11h
db  12h
db  13h
db  14h
db  15h
db  16h
db  17h
db  18h
db  19h
db  1Ah
db  1Bh
db  1Ch
db  1Dh
db  1Eh
db  1Fh
db  20h
db  21h	; !
db  22h	; "
db  23h	; #
db  24h	; $
db  25h	; %
db  26h	; &
db  27h	; '
db  28h	; (
db  29h	; )
db  2Ah	; *
db  2Bh	; +
db  2Ch	; ,
db  2Dh	; -
db  2Eh	; .
db  2Fh	; /
db  30h	; 0
db  31h	; 1
db  32h	; 2
db  33h	; 3
db  34h	; 4
db  35h	; 5
db  36h	; 6
db  37h	; 7
db  38h	; 8
db  39h	; 9
db  3Ah	; :
db  3Bh	; ;
db  3Ch	; <
db  3Dh	; =
db  3Eh	; >
db  3Fh	; ?
db  40h	; @
db  61h	; a
db  62h	; b
db  63h	; c
db  64h	; d
db  65h	; e
db  66h	; f
db  67h	; g
db  68h	; h
db  69h	; i
db  6Ah	; j
db  6Bh	; k
db  6Ch	; l
db  6Dh	; m
db  6Eh	; n
db  6Fh	; o
db  70h	; p
db  71h	; q
db  72h	; r
db  73h	; s
db  74h	; t
db  75h	; u
db  76h	; v
db  77h	; w
db  78h	; x
db  79h	; y
db  7Ah	; z
db  5Bh	; [
db  5Ch	; \
db  5Dh	; ]
db  5Eh	; ^
db  5Fh	; _
db  60h	; `
db  61h	; a
db  62h	; b
db  63h	; c
db  64h	; d
db  65h	; e
db  66h	; f
db  67h	; g
db  68h	; h
db  69h	; i
db  6Ah	; j
db  6Bh	; k
db  6Ch	; l
db  6Dh	; m
db  6Eh	; n
db  6Fh	; o
db  70h	; p
db  71h	; q
db  72h	; r
db  73h	; s
db  74h	; t
db  75h	; u
db  76h	; v
db  77h	; w
db  78h	; x
db  79h	; y
db  7Ah	; z
db  7Bh	; {
db  7Ch	; |
db  7Dh	; }
db  7Eh	; ~
db  7Fh	; 
db  80h	; Ä
db  81h	; Å
db  82h	; Ç
db  83h	; É
db  84h	; Ñ
db  85h	; Ö
db  86h	; Ü
db  87h	; á
db  88h	; à
db  89h	; â
db  8Ah	; ä
db  8Bh	; ã
db  8Ch	; å
db  8Dh	; ç
db  8Eh	; é
db  8Fh	; è
db  90h	; ê
db  91h	; ë
db  92h	; í
db  93h	; ì
db  94h	; î
db  95h	; ï
db  96h	; ñ
db  97h	; ó
db  98h	; ò
db  99h	; ô
db  9Ah	; ö
db  9Bh	; õ
db  9Ch	; ú
db  9Dh	; ù
db  9Eh	; û
db  9Fh	; ü
db 0A0h	; †
db 0A1h	; °
db 0A2h	; ¢
db 0A3h	; £
db 0A4h	; §
db 0A5h	; •
db 0A6h	; ¶
db 0A7h	; ß
db 0A8h	; ®
db 0A9h	; ©
db 0AAh	; ™
db 0ABh	; ´
db 0ACh	; ¨
db 0ADh	; ≠
db 0AEh	; Æ
db 0AFh	; Ø
db 0B0h	; ∞
db 0B1h	; ±
db 0B2h	; ≤
db 0B3h	; ≥
db 0B4h	; ¥
db 0B5h	; µ
db 0B6h	; ∂
db 0B7h	; ∑
db 0B8h	; ∏
db 0B9h	; π
db 0BAh	; ∫
db 0BBh	; ª
db 0BCh	; º
db 0BDh	; Ω
db 0BEh	; æ
db 0BFh	; ø
db 0C0h	; ¿
db 0C1h	; ¡
db 0C2h	; ¬
db 0C3h	; √
db 0C4h	; ƒ
db 0C5h	; ≈
db 0C6h	; ∆
db 0C7h	; «
db 0C8h	; »
db 0C9h	; …
db 0CAh	;  
db 0CBh	; À
db 0CCh	; Ã
db 0CDh	; Õ
db 0CEh	; Œ
db 0CFh	; œ
db 0D0h	; –
db 0D1h	; —
db 0D2h	; “
db 0D3h	; ”
db 0D4h	; ‘
db 0D5h	; ’
db 0D6h	; ÷
db 0D7h	; ◊
db 0D8h	; ÿ
db 0D9h	; Ÿ
db 0DAh	; ⁄
db 0DBh	; €
db 0DCh	; ‹
db 0DDh	; ›
db 0DEh	; ﬁ
db 0DFh	; ﬂ
db 0E0h	; ‡
db 0E1h	; ·
db 0E2h	; ‚
db 0E3h	; „
db 0E4h	; ‰
db 0E5h	; Â
db 0E6h	; Ê
db 0E7h	; Á
db 0E8h	; Ë
db 0E9h	; È
db 0EAh	; Í
db 0EBh	; Î
db 0ECh	; Ï
db 0EDh	; Ì
db 0EEh	; Ó
db 0EFh	; Ô
db 0F0h	; 
db 0F1h	; Ò
db 0F2h	; Ú
db 0F3h	; Û
db 0F4h	; Ù
db 0F5h	; ı
db 0F6h	; ˆ
db 0F7h	; ˜
db 0F8h	; ¯
db 0F9h	; ˘
db 0FAh	; ˙
db 0FBh	; ˚
db 0FCh	; ¸
db 0FDh	; ˝
db 0FEh	; ˛
db 0FFh
db    0
db    1
db    2
db    3
db    4
db    5
db    6
db    7
db    8
db    9
db  0Ah
db  0Bh
db  0Ch
db  0Dh
db  0Eh
db  0Fh
db  10h
db  11h
db  12h
db  13h
db  14h
db  15h
db  16h
db  17h
db  18h
db  19h
db  1Ah
db  1Bh
db  1Ch
db  1Dh
db  1Eh
db  1Fh
db  20h
db  21h	; !
db  22h	; "
db  23h	; #
db  24h	; $
db  25h	; %
db  26h	; &
db  27h	; '
db  28h	; (
db  29h	; )
db  2Ah	; *
db  2Bh	; +
db  2Ch	; ,
db  2Dh	; -
db  2Eh	; .
db  2Fh	; /
db  30h	; 0
db  31h	; 1
db  32h	; 2
db  33h	; 3
db  34h	; 4
db  35h	; 5
db  36h	; 6
db  37h	; 7
db  38h	; 8
db  39h	; 9
db  3Ah	; :
db  3Bh	; ;
db  3Ch	; <
db  3Dh	; =
db  3Eh	; >
db  3Fh	; ?
db  40h	; @
db  41h	; A
db  42h	; B
db  43h	; C
db  44h	; D
db  45h	; E
db  46h	; F
db  47h	; G
db  48h	; H
db  49h	; I
db  4Ah	; J
db  4Bh	; K
db  4Ch	; L
db  4Dh	; M
db  4Eh	; N
db  4Fh	; O
db  50h	; P
db  51h	; Q
db  52h	; R
db  53h	; S
db  54h	; T
db  55h	; U
db  56h	; V
db  57h	; W
db  58h	; X
db  59h	; Y
db  5Ah	; Z
db  5Bh	; [
db  5Ch	; \
db  5Dh	; ]
db  5Eh	; ^
db  5Fh	; _
db  60h	; `
db  41h	; A
db  42h	; B
db  43h	; C
db  44h	; D
db  45h	; E
db  46h	; F
db  47h	; G
db  48h	; H
db  49h	; I
db  4Ah	; J
db  4Bh	; K
db  4Ch	; L
db  4Dh	; M
db  4Eh	; N
db  4Fh	; O
db  50h	; P
db  51h	; Q
db  52h	; R
db  53h	; S
db  54h	; T
db  55h	; U
db  56h	; V
db  57h	; W
db  58h	; X
db  59h	; Y
db  5Ah	; Z
db  7Bh	; {
db  7Ch	; |
db  7Dh	; }
db  7Eh	; ~
db  7Fh	; 
db  80h	; Ä
db  81h	; Å
db  82h	; Ç
db  83h	; É
db  84h	; Ñ
db  85h	; Ö
db  86h	; Ü
db  87h	; á
db  88h	; à
db  89h	; â
db  8Ah	; ä
db  8Bh	; ã
db  8Ch	; å
db  8Dh	; ç
db  8Eh	; é
db  8Fh	; è
db  90h	; ê
db  91h	; ë
db  92h	; í
db  93h	; ì
db  94h	; î
db  95h	; ï
db  96h	; ñ
db  97h	; ó
db  98h	; ò
db  99h	; ô
db  9Ah	; ö
db  9Bh	; õ
db  9Ch	; ú
db  9Dh	; ù
db  9Eh	; û
db  9Fh	; ü
db 0A0h	; †
db 0A1h	; °
db 0A2h	; ¢
db 0A3h	; £
db 0A4h	; §
db 0A5h	; •
db 0A6h	; ¶
db 0A7h	; ß
db 0A8h	; ®
db 0A9h	; ©
db 0AAh	; ™
db 0ABh	; ´
db 0ACh	; ¨
db 0ADh	; ≠
db 0AEh	; Æ
db 0AFh	; Ø
db 0B0h	; ∞
db 0B1h	; ±
db 0B2h	; ≤
db 0B3h	; ≥
db 0B4h	; ¥
db 0B5h	; µ
db 0B6h	; ∂
db 0B7h	; ∑
db 0B8h	; ∏
db 0B9h	; π
db 0BAh	; ∫
db 0BBh	; ª
db 0BCh	; º
db 0BDh	; Ω
db 0BEh	; æ
db 0BFh	; ø
db 0C0h	; ¿
db 0C1h	; ¡
db 0C2h	; ¬
db 0C3h	; √
db 0C4h	; ƒ
db 0C5h	; ≈
db 0C6h	; ∆
db 0C7h	; «
db 0C8h	; »
db 0C9h	; …
db 0CAh	;  
db 0CBh	; À
db 0CCh	; Ã
db 0CDh	; Õ
db 0CEh	; Œ
db 0CFh	; œ
db 0D0h	; –
db 0D1h	; —
db 0D2h	; “
db 0D3h	; ”
db 0D4h	; ‘
db 0D5h	; ’
db 0D6h	; ÷
db 0D7h	; ◊
db 0D8h	; ÿ
db 0D9h	; Ÿ
db 0DAh	; ⁄
db 0DBh	; €
db 0DCh	; ‹
db 0DDh	; ›
db 0DEh	; ﬁ
db 0DFh	; ﬂ
db 0E0h	; ‡
db 0E1h	; ·
db 0E2h	; ‚
db 0E3h	; „
db 0E4h	; ‰
db 0E5h	; Â
db 0E6h	; Ê
db 0E7h	; Á
db 0E8h	; Ë
db 0E9h	; È
db 0EAh	; Í
db 0EBh	; Î
db 0ECh	; Ï
db 0EDh	; Ì
db 0EEh	; Ó
db 0EFh	; Ô
db 0F0h	; 
db 0F1h	; Ò
db 0F2h	; Ú
db 0F3h	; Û
db 0F4h	; Ù
db 0F5h	; ı
db 0F6h	; ˆ
db 0F7h	; ˜
db 0F8h	; ¯
db 0F9h	; ˘
db 0FAh	; ˙
db 0FBh	; ˚
db 0FCh	; ¸
db 0FDh	; ˝
db 0FEh	; ˛
db 0FFh
db  3Ch	; <
db    0
db    0
db    0
db    0
db    0
db    0
db    0
; char *Str
Str dd offset aMozilla	; "Mozilla"
; char *off_404504
off_404504 dd offset aFirefox_0	; "Firefox"
; char *off_404508
off_404508 dd offset a23_0 ; "23.0"
; char *off_40450C
off_40450C dd offset a20130730113002 ; "20130730113002"
; char *off_404510
off_404510 dd offset aEc8030f7C20a46 ; "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}"
align 8
db  0Eh
db    0
db    0
db    0
db    0
db    0
db    0
db    0
; char *off_404520
off_404520 dd offset a23_0 ; "23.0"
; char *off_404524
off_404524 dd offset a23_0 ; "23.0"
; char *off_404528
off_404528 dd offset aHttpsCrashRepo ; "https://crash-reports.mozilla.com/submi"...
align 10h
dword_404530 dd	0
align 8
off_404538 dd offset aXre_getfilefro ; "XRE_GetFileFromPath"
dd offset dword_405394
dd offset aXre_createappd ; "XRE_CreateAppData"
dd offset dword_40537C
dd offset aXre_freeappdat ; "XRE_FreeAppData"
dd offset dword_405384
dd offset aXre_setupdllbl ; "XRE_SetupDllBlocklist"
dd offset dword_405388
dd offset aXre_telemetrya ; "XRE_TelemetryAccumulate"
dd offset dword_405380
dd offset aXre_startuptim ; "XRE_StartupTimelineRecord"
dd offset dword_40538C
dd offset aXre_main	; "XRE_main"
dd offset dword_405390
dd offset aXre_disablewri ; "XRE_DisableWritePoisoning"
dd offset unk_405378
align 10h
; const	WCHAR Name
Name:
unicode	0, <PATH>,0
align 4
unk_40458C db	 0
db    0
db    0
db    0
; const	WCHAR Caption
Caption:
unicode	0, <Firefox>,0
; char VarName[]
VarName	db 'XUL_APP_FILE',0
align 10h
; char aInvalidPathFou[]
aInvalidPathFou	db 'Invalid path found: ',27h,'%s',27h,0
align 4
; char Str2[]
Str2 db	'app',0
; char aIncorrectNumbe[]
aIncorrectNumbe	db 'Incorrect number of arguments passe'
db 'd to -app',0
align 10h
; char aApplication_in[]
aApplication_in	db 'application.ini path not recognized'
db ': ',27h,'%s',27h,0
align 4
; char aXul_app_fileS[]
aXul_app_fileS db 'XUL_APP_FILE=%s',0
; char aCouldnTSetS_[]
aCouldnTSetS_ db 'Couldn',27h,'t set %s.',0Ah,0
align 10h
; char aCouldnTReadApp[]
aCouldnTReadApp	db 'Couldn',27h,'t read application.ini',0
align 10h
; char aCouldnTFindThe[]
aCouldnTFindThe	db 'Couldn',27h,'t find the application di'
db 'rectory.',0Ah,0
align 4
aBrowser:
unicode	0, <browser>,0
; const	WCHAR ModuleName
ModuleName:
unicode	0, <kernel32.dll>,0
align 4
; char ProcName[]
ProcName db 'GetTickCount64',0
align 4
; char Source[]
Source db 'xul.dll',0
; char aCouldNotFindTh[]
aCouldNotFindTh	db 'Could not find the Mozilla runtime.'
db 0Ah,0
align 4
; char aCouldnTLoadXpc[]
aCouldnTLoadXpc	db 'Couldn',27h,'t load XPCOM.',0Ah,0
align 10h
; char aCouldnTLoadXre[]
aCouldnTLoadXre	db 'Couldn',27h,'t load XRE functions.',0Ah,0
align 10h
asc_404740 db '/\',0
align 4
; char aDependentlibs_[]
aDependentlibs_	db '\dependentlibs.list',0
; char aDependentlib_0[]
aDependentlib_0	db 'dependentlibs.list',0
align 4
; wchar_t Mode
Mode:
unicode	0, <rt>,0
align 4
; char aNs_getfrozenfu[]
aNs_getfrozenfu	db 'NS_GetFrozenFunctions',0
align 4
; char Format[]
Format db '%s',0
align 10h
__load_config_used dd 48h ; Size
dd 0			; Time stamp
dw 2 dup(0)		; Version: 0.0
dd 0			; GlobalFlagsClear
dd 0			; GlobalFlagsSet
dd 0			; CriticalSectionDefaultTimeout
dd 0			; DeCommitFreeBlockThreshold
dd 0			; DeCommitTotalFreeThreshold
dd 0			; LockPrefixTable
dd 0			; MaximumAllocationSize
dd 0			; VirtualMemoryThreshold
dd 0			; ProcessAffinityMask
dd 0			; ProcessHeapFlags
dw 0			; CSDVersion
dw 0			; Reserved1
dd 0			; EditList
dd offset ___security_cookie ; SecurityCookie
dd offset ___safe_se_handler_table ; SEHandlerTable
dd 1			; SEHandlerCount
db  52h	; R
db  53h	; S
db  44h	; D
db  53h	; S
db  5Bh	; [
db  46h	; F
db 0AFh	; Ø
db  27h	; '
db 0C0h	; ¿
db 0D4h	; ‘
db 0FEh	; ˛
db  42h	; B
db  88h	; à
db  8Bh	; ã
db 0E1h	; ·
db  81h	; Å
db 0CCh	; Ã
db 0DCh	; ‹
db  5Fh	; _
db  4Eh	; N
db    2
db    0
db    0
db    0
db  65h	; e
db  3Ah	; :
db  5Ch	; \
db  62h	; b
db  75h	; u
db  69h	; i
db  6Ch	; l
db  64h	; d
db  73h	; s
db  5Ch	; \
db  6Dh	; m
db  6Fh	; o
db  7Ah	; z
db  32h	; 2
db  5Fh	; _
db  73h	; s
db  6Ch	; l
db  61h	; a
db  76h	; v
db  65h	; e
db  5Ch	; \
db  72h	; r
db  65h	; e
db  6Ch	; l
db  2Dh	; -
db  6Dh	; m
db  2Dh	; -
db  72h	; r
db  65h	; e
db  6Ch	; l
db  2Dh	; -
db  77h	; w
db  33h	; 3
db  32h	; 2
db  5Fh	; _
db  62h	; b
db  6Ch	; l
db  64h	; d
db  2Dh	; -
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  30h	; 0
db  5Ch	; \
db  62h	; b
db  75h	; u
db  69h	; i
db  6Ch	; l
db  64h	; d
db  5Ch	; \
db  6Fh	; o
db  62h	; b
db  6Ah	; j
db  2Dh	; -
db  66h	; f
db  69h	; i
db  72h	; r
db  65h	; e
db  66h	; f
db  6Fh	; o
db  78h	; x
db  5Ch	; \
db  62h	; b
db  72h	; r
db  6Fh	; o
db  77h	; w
db  73h	; s
db  65h	; e
db  72h	; r
db  5Ch	; \
db  61h	; a
db  70h	; p
db  70h	; p
db  5Ch	; \
db  66h	; f
db  69h	; i
db  72h	; r
db  65h	; e
db  66h	; f
db  6Fh	; o
db  78h	; x
db  2Eh	; .
db  70h	; p
db  64h	; d
db  62h	; b
db    0
db    0
db    0
___safe_se_handler_table dd rva	__except_handler4
align 8
unk_404858 db	 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
unk_404860 db	 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
stru_404868 dd 0FFFFFFFEh	    ; GSCookieOffset ; SEH scope table for function 401F94
dd 0			; GSCookieXOROffset
dd 0FFFFFFD0h		; EHCookieOffset
dd 0			; EHCookieXOROffset
dd 0FFFFFFFEh		; ScopeRecord.EnclosingLevel
dd offset $LN35		; ScopeRecord.FilterFunc
dd offset $LN22		; ScopeRecord.HandlerFunc
align 8
stru_404888 dd 0FFFFFFFEh	    ; GSCookieOffset ; SEH scope table for function 402258
dd 0			; GSCookieXOROffset
dd 0FFFFFFCCh		; EHCookieOffset
dd 0			; EHCookieXOROffset
dd 0FFFFFFFEh		; ScopeRecord.EnclosingLevel
dd 0			; ScopeRecord.FilterFunc
dd offset $LN8		; ScopeRecord.HandlerFunc
align 8
unk_4048A8 db 0FEh ; ˛
db 0FFh
db 0FFh
db 0FFh
db    0
db    0
db    0
db    0
db 0D8h	; ÿ
db 0FFh
db 0FFh
db 0FFh
db    0
db    0
db    0
db    0
db 0FEh	; ˛
db 0FFh
db 0FFh
db 0FFh
dd offset $LN13
dd offset $LN8_0
__IMPORT_DESCRIPTOR_KERNEL32 dd	rva off_404914 ; Import	Name Table
dd 0			; Time stamp
dd 0			; Forwarder Chain
dd rva aKernel32_dll	; DLL Name
dd rva GetEnvironmentVariableW ; Import	Address	Table
__IMPORT_DESCRIPTOR_USER32 dd rva off_404A48 ; Import Name Table
dd 0			; Time stamp
dd 0			; Forwarder Chain
dd rva aUser32_dll	; DLL Name
dd rva MessageBoxW	; Import Address Table
__IMPORT_DESCRIPTOR_MSVCR100 dd	rva off_4049A4 ; Import	Name Table
dd 0			; Time stamp
dd 0			; Forwarder Chain
dd rva aMsvcr100_dll	; DLL Name
dd rva __wgetmainargs	; Import Address Table
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
;
; Import names for KERNEL32.dll
;
off_404914 dd rva word_404A50
dd rva word_404A6A
dd rva word_404A82
dd rva word_404A96
dd rva word_404AAA
dd rva word_404AC4
dd rva word_404AD8
dd rva word_404AE8
dd rva word_404AFE
dd rva word_404B14
dd rva word_404B2A
dd rva word_404B40
dd rva word_404B52
dd rva word_404B6E
dd rva word_404F58
dd rva word_404F3C
dd rva word_404F0E
dd rva word_404EF8
dd rva word_404EE2
dd rva word_404EC8
dd rva word_404EB8
dd rva word_404E9A
dd rva word_404E8A
dd rva word_404E74
dd rva word_404E56
dd rva word_404E4E
dd rva word_404E38
dd rva word_404E2A
dd rva word_404E1C
dd rva word_404E10
dd rva word_404DFC
dd rva word_404DEC
dd rva word_404DDA
dd rva word_404DCC
dd rva word_404F28
dd 0
;
; Import names for MSVCR100.dll
;
off_4049A4 dd rva word_404C6A
dd rva word_404C7C
dd rva word_404C86
dd rva word_404C5C
dd rva word_404C9C
dd rva word_404CA4
dd rva word_404CB2
dd rva word_404CBE
dd rva word_404CCC
dd rva word_404CE2
dd rva word_404CF6
dd rva word_404D02
dd rva word_404D0C
dd rva word_404D2C
dd rva word_404D3C
dd rva word_404D50
dd rva word_404D5A
dd rva word_404D68
dd rva word_404D70
dd rva word_404D7A
dd rva word_404D94
dd rva word_404DA6
dd rva word_404DB6
dd rva word_404C52
dd rva word_404C42
dd rva word_404C38
dd rva word_404C28
dd rva word_404C20
dd rva word_404C16
dd rva word_404C0C
dd rva word_404C02
dd rva word_404BF8
dd rva word_404BEE
dd rva word_404BDE
dd rva word_404BD4
dd rva word_404BC8
dd rva word_404BBE
dd rva word_404BB2
dd rva word_404C8E
dd rva word_404F6C
dd 0
;
; Import names for USER32.dll
;
off_404A48 dd rva word_404B98
dd 0
word_404A50 dw 242h
db 'GetEnvironmentVariableW',0
word_404A6A dw 2BFh
db 'GetProcessIoCounters',0
align 2
word_404A82 dw 4F4h
db 'SetDllDirectoryW',0
align 2
word_404A96 dw 223h
db 'GetCurrentProcess',0
word_404AAA dw 4FAh
db 'SetEnvironmentVariableW',0
word_404AC4 dw 281h
db 'GetModuleHandleW',0
align 4
word_404AD8 dw 310h
db 'GetTickCount',0
align 4
word_404AE8 dw 5DDh
db 'WideCharToMultiByte',0
word_404AFE dw 24Eh
db 'GetFileAttributesW',0
align 4
word_404B14 dw 27Dh
db 'GetModuleFileNameW',0
align 2
word_404B2A dw 3ECh
db 'MultiByteToWideChar',0
word_404B40 dw 2B5h
db 'GetProcAddress',0
align 2
word_404B52 dw 43Dh
db 'QueryPerformanceFrequency',0
word_404B6E dw 171h
db 'ExpandEnvironmentStringsW',0
aKernel32_dll db 'KERNEL32.dll',0
align 4
word_404B98 dw 24Bh
db 'MessageBoxW',0
aUser32_dll db 'USER32.dll',0
align 2
word_404BB2 dw 441h
db '_stricmp',0
align 2
word_404BBE dw 5FAh
db 'strcpy',0
align 4
word_404BC8 dw 410h
db '_snprintf',0
word_404BD4 dw 637h
db 'wcslen',0
align 2
word_404BDE dw 7Ah
db '??_V@YAXPAX@Z',0
word_404BEE dw 608h
db 'strrchr',0
word_404BF8 dw 59Bh
db 'getenv',0
align 2
word_404C02 dw 5CFh
db 'memcpy',0
align 4
word_404C0C dw 600h
db 'strlen',0
align 2
word_404C16 dw 513h
db '_wfopen',0
word_404C20 dw 57Ch
db 'fgets',0
word_404C28 dw 65h
db '??3@YAXPAX@Z',0
align 4
word_404C38 dw 576h
db 'fclose',0
align 2
word_404C42 dw 63h
db '??2@YAPAXI@Z',0
align 2
word_404C52 dw 5D3h
db 'memset',0
align 4
word_404C5C dw 1C5h
db '_amsg_exit',0
align 2
word_404C6A dw 1B6h
db '__wgetmainargs',0
align 4
word_404C7C dw 1DCh
db '_cexit',0
align 2
word_404C86 dw 22Ah
db '_exit',0
word_404C8E dw 12Dh
db '_XcptFilter',0
word_404C9C dw 573h
db 'exit',0
align 4
word_404CA4 dw 1B7h
db '__winitenv',0
align 2
word_404CB2 dw 2B0h
db '_initterm',0
word_404CBE dw 2B1h
db '_initterm_e',0
word_404CCC dw 1ECh
db '_configthreadlocale',0
word_404CE2 dw 1A2h
db '__setusermatherr',0
align 2
word_404CF6 dw 1EBh
db '_commode',0
align 2
word_404D02 dw 245h
db '_fmode',0
align 4
word_404D0C dw 19Fh
db '__set_app_type',0
align 2
aMsvcr100_dll db 'MSVCR100.dll',0
align 4
word_404D2C dw 4B5h
db '_vsnprintf_s',0
align 4
word_404D3C dw 102h
db '?terminate@@YAXXZ',0
word_404D50 dw 48Dh
db '_unlock',0
word_404D5A dw 15Bh
db '__dllonexit',0
word_404D68 dw 323h
db '_lock',0
word_404D70 dw 3C9h
db '_onexit',0
word_404D7A dw 221h
db '_except_handler4_common',0
word_404D94 dw 2B8h
db '_invoke_watson',0
align 2
word_404DA6 dw 1EFh
db '_controlfp_s',0
align 2
word_404DB6 dw 1FBh
db '_crt_debugger_hook',0
align 4
word_404DCC dw 1B8h
db 'FreeLibrary',0
word_404DDA dw 3C2h
db 'LoadLibraryExW',0
align 4
word_404DEC dw 26Ah
db 'GetLastError',0
align 4
word_404DFC dw 509h
db 'SetFilePointerEx',0
align 10h
word_404E10 dw 458h
db 'ReadFile',0
align 4
word_404E1C dw 0D6h
db 'CreateFileW',0
word_404E2A dw 8Eh
db 'CloseHandle',0
word_404E38 dw 36Eh
db 'InterlockedExchange',0
word_404E4E dw 55Fh
db 'Sleep',0
word_404E56 dw 36Bh
db 'InterlockedCompareExchange',0
align 4
word_404E74 dw 355h
db 'HeapSetInformation',0
align 2
word_404E8A dw 13Ch
db 'EncodePointer',0
word_404E9A dw 550h
db 'SetUnhandledExceptionFilter',0
word_404EB8 dw 117h
db 'DecodePointer',0
word_404EC8 dw 43Ch
db 'QueryPerformanceCounter',0
word_404EE2 dw 228h
db 'GetCurrentThreadId',0
align 4
word_404EF8 dw 224h
db 'GetCurrentProcessId',0
word_404F0E dw 2F4h
db 'GetSystemTimeAsFileTime',0
word_404F28 dw 56Fh
db 'TerminateProcess',0
align 4
word_404F3C dw 590h
db 'UnhandledExceptionFilter',0
align 4
word_404F58 dw 383h
db 'IsDebuggerPresent',0
word_404F6C dw 3DBh
db '_putenv',0
align 100h
_rdata ends

; Section 3. (virtual address 00005000)
; Virtual size			: 000004AC (   1196.)
; Section size in file		: 00000200 (	512.)
; Offset to raw	data for section: 00003600
; Flags	C0000040: Data Readable	Writable
; Alignment	: default

; Segment type:	Pure data
; Segment permissions: Read/Write
_data segment para public 'DATA' use32
assume cs:_data
;org 405000h
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db 0FFh
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
dword_405010 dd	0FFFFFFFEh
dword_405014 dd	1
___security_cookie dd 0BB40E64Eh
dword_40501C dd	44BF19B1h
dword_405020 dd	0
dword_405024 dd	0
dword_405028 dd	0
dword_40502C dd	0
dword_405030 dd	0
dword_405034 dd	0
dword_405038 dd	0
dword_40503C dd	0
dword_405040 dd	0
dword_405044 dd	0
dword_405048 dd	0
dword_40504C dd	0
dword_405050 dd	0
dword_405054 dd	0
db    0
db    0
db    0
db    0
dword_40505C dd	0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
dword_4050A0 dd	0
align 8
dword_4050A8 dd	0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
word_405134 dw 0
align 4
word_405138 dw 0
align 4
word_40513C dw 0
align 10h
word_405140 dw 0
align 4
dword_405144 dd	0
dword_405148 dd	0
dword_40514C dd	0
dword_405150 dd	0
dword_405154 dd	0
dword_405158 dd	0
dword_40515C dd	0
dword_405160 dd	0
word_405164 dw 0
align 4
dword_405168 dd	0
dword_40516C dd	0
word_405170 dw 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
unk_405378 db	 ? ;
db    ?	;
db    ?	;
db    ?	;
dword_40537C dd	?
dword_405380 dd	?
dword_405384 dd	?
dword_405388 dd	?
dword_40538C dd	?
dword_405390 dd	?
dword_405394 dd	?
dword_405398 dd	?
dword_40539C dd	?
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
dword_4053B8 dd	?
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
dword_4053D0 dd	?
dword_4053D4 dd	?
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
dword_4053EC dd	?
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
dword_405400 dd	?
align 10h
dword_405410 dd	?
align 8
dword_405418 dd	?
dword_40541C dd	?
dword_405420 dd	?
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
dword_405434 dd	?
dword_405438 dd	?
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
dword_405480 dd	?
dword_405484 dd	?
dword_405488 dd	?
dword_40548C dd	?
byte_405490 db ?
align 4
dword_405494 dd	?
; volatile LONG	Destination
Destination dd ?
; PVOID	dword_40549C
dword_40549C dd	?
; PVOID	Ptr
Ptr dd ?
dword_4054A4 dd	?
dword_4054A8 dd	?
align 1000h
_data ends


end start
