;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2010 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-B231-7414-99			    |
; |		       NCFTA Canada/Concordia University		    |
; +-------------------------------------------------------------------------+
;
;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2010 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-B231-7414-99			    |
; |		       NCFTA Canada/Concordia University		    |
; +-------------------------------------------------------------------------+
_SHRegCloseUSKey@4 proc	near		; CODE XREF: Ext_IEExtFixUpExtUpgrade(_GUID const &)+1B24p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
_SHRegCloseUSKey@4 endp

_SHRegCloseUSKey@4 proc	near		; CODE XREF: Ext_IEExtFixUpExtUpgrade(_GUID const &)+1B24p
		mov	edi, edi
		push	ebp
		mov	ebp, esp
_SHRegCloseUSKey@4 endp